.TH "keylaunch" "1" "1.x.x" "" ""
.SH "NAME"
.LP 
keylaunch \- A utility for binding commands to a hot key.
.SH "SYNTAX"
.LP 
keylaunch [\fIno options\fP] <\fIno arguments\fP>

.SH "DESCRIPTION"
.LP 
KeyLaunch is a utility for binding commands to a hot key.
See the example rc file for information
.SH "FILES"
.LP 
\fI$HOME/.keylaunchrc\fP 
.SH "EXAMPLES"
.LP 
To use keylaunch add it to your .xinitrc
.LP 
Keylaunch reads a users .keylaunchrc file

.SH "AUTHORS"
.LP 
Brandon L. Griffith <brandon@debian.org>
.br 
This manual page was written for Debian GNU/Linux by the above mentioned name.
.br 
Keylaunch was written by Ken Lynch
.SH "SEE ALSO"
.LP 
desklauncy(1) deskmenu(1) oroborus(1)
