/* game_pixmaps.h  by Michael Berg
 * pixmap definitions for use in the code_breaker program
 */

/* XPM */
static char * winner_xpm[] = {
"48 48 4 1",
" 	c None",
".	c #000000",
"+	c #F9E907",
"@	c #FFFF00",
"                                                ",
"      ....  ........................  ....      ",
"    ..++++. .++++++++++++++++++++++. .++++..    ",
"   .+++++++..+@@@@@@+++++++++++++++..+++++++.   ",
"  .+++++++++.+@@@@@@@++++++++++++++.+++++++++.  ",
"  .++++++..+++@@@@@@@++++++++++++++++..++++++.  ",
"  .+++++.  .++@@@@@@@+++++++++++++++.  .+++++.  ",
"  .++++.    .+@@@@@@@++++++++++++++.    .++++.  ",
"  .++++.    .+@@@@@@@++++++++++++++.    .++++.  ",
"  .++++.    .++@@@@@@++++++++++++++.    .++++.  ",
"  .++++.    .++@@@@@+++++++++++++++.    .++++.  ",
"   .+++.    .++@@@@@+++++++++++++++.    .+++.   ",
"   .++++.    .++@@@@++++++++++++++.    .++++.   ",
"    .+++.    .++@@@@++++++++++++++.    .+++.    ",
"     .+++.   .++@@@@++++++++++++++.   .+++.     ",
"      .+++.  .+++@@@++++++++++++++.  .+++.      ",
"       .+++.  .+++@@+++++++++++++.  .+++.       ",
"        .+++. .++++@@++++++++++++. .+++.        ",
"         .+++. .++++@+++++++++++. .+++.         ",
"          .+++..++++@+++++++++++..+++.          ",
"           ..++.++++++++++++++++.++..           ",
"             .++++++++++++++++++++.             ",
"              .++++++++++++++++++.              ",
"               .++++++++++++++++.               ",
"                ..++++++++++++..                ",
"                  .++++++++++.                  ",
"                   .++++++++.                   ",
"                    .++++++.                    ",
"                     .++++.                     ",
"                     .++++.                     ",
"                     .++++.                     ",
"                     .++++.                     ",
"                     .++++.                     ",
"                    .++++++.                    ",
"                   .++@+++++.                   ",
"                  .++@@++++++.                  ",
"                 .++@@@+++++++.                 ",
"                .++@@@+++++++++.                ",
"               .++@@@@++++++++++.               ",
"              ..++@@@+++++++++++..              ",
"              .++++++++++++++++++.              ",
"              .++++++++++++++++++.              ",
"              .++++++++++++++++++.              ",
"              .++++++++++++++++++.              ",
"             .++++++++++++++++++++.             ",
"            .++++++++++++++++++++++.            ",
"            ........................            ",
"                                                "};


/* XPM */
static char * loser_xpm[] = {
"48 48 3 1",
" 	c None",
".	c #000000",
"X	c #FFFF00",
"                                                ",
"                                                ",
"                   ..........                   ",
"                ...XXXXXXXXXX...                ",
"              ..XXXXXXXXXXXXXXXX..              ",
"            ..XXXXXXXXXXXXXXXXXXXX..            ",
"           .XXXXXXXXXXXXXXXXXXXXXXXX.           ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXXX.          ",
"         .XXXXXXXXXXXXXXXXXXXXXXXXXXXX.         ",
"        .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"       .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.       ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.      ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"     .XXXXXXXXXX...XXXXXXXXXX...XXXXXXXXXX.     ",
"    .XXXXXXXXXXX...XXXXXXXXXX...XXXXXXXXXXX.    ",
"    .XXXXXXXXXX.....XXXXXXXX.....XXXXXXXXXX.    ",
"   .XXXXXXXXXXX.....XXXXXXXX.....XXXXXXXXXXX.   ",
"   .XXXXXXXXXXX.....XXXXXXXX.....XXXXXXXXXXX.   ",
"   .XXXXXXXXXXX.....XXXXXXXX.....XXXXXXXXXXX.   ",
"  .XXXXXXXXXXXX.....XXXXXXXX.....XXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXX.....XXXXXXXX.....XXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXX...XXXXXXXXXX...XXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXX...XXXXXXXXXX...XXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"  .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.  ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"   .XXXXXXXXXXXXXXXX........XXXXXXXXXXXXXXXX.   ",
"    .XXXXXXXXXXXXX...XXXXXX...XXXXXXXXXXXXX.    ",
"    .XXXXXXXXXXXX..XXXXXXXXXX..XXXXXXXXXXXX.    ",
"     .XXXXXXXXXX..XXXXXXXXXXXX..XXXXXXXXXX.     ",
"     .XXXXXXXXX..XXXXXXXXXXXXXX..XXXXXXXXX.     ",
"      .XXXXXXX..XXXXXXXXXXXXXXXX..XXXXXXX.      ",
"       .XXXXXX.XXXXXXXXXXXXXXXXXX.XXXXXX.       ",
"        .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"         .XXXXXXXXXXXXXXXXXXXXXXXXXXXX.         ",
"          .XXXXXXXXXXXXXXXXXXXXXXXXXX.          ",
"           .XXXXXXXXXXXXXXXXXXXXXXXX.           ",
"            ..XXXXXXXXXXXXXXXXXXXX..            ",
"              ..XXXXXXXXXXXXXXXX..              ",
"                ...XXXXXXXXXX...                ",
"                   ..........                   ",
"                                                ",
"                                                "};


/* XPM */
static char * question_xpm[] = {
"48 48 3 1",
" 	c None",
".	c #000000",
"+	c #0000FF",
"                                                ",
"                                                ",
"                                                ",
"                  ............                  ",
"                ..++++++++++++..                ",
"              ..++++++++++++++++.               ",
"             .++++++++...++++++++.              ",
"            .++++++++.   .++++++++.             ",
"            .+++++++.     .++++++++.            ",
"           .++++++++.     .++++++++.            ",
"           .+++++++.      .++++++++.            ",
"           .+++++++.      .++++++++.            ",
"            .++++++.      .++++++++.            ",
"             ..+++.       .++++++++.            ",
"               ...       .+++++++++.            ",
"                         .++++++++.             ",
"                        .++++++++.              ",
"                       .++++++++.               ",
"                      .+++++++..                ",
"                    ..++++++..                  ",
"                   .+++++++.                    ",
"                  .+++++++.                     ",
"                 .+++++++.                      ",
"                .++++++++.                      ",
"                .++++++++.                      ",
"               .+++++++++.                      ",
"               .+++++++++.                      ",
"                .+++++++++.                     ",
"                .++++++++++.                    ",
"                 .++++++++++.                   ",
"                  .+++++++++.                   ",
"                   .........                    ",
"                                                ",
"                                                ",
"                                                ",
"                      ...                       ",
"                    ..+++..                     ",
"                   .+++++++.                    ",
"                  .+++++++++.                   ",
"                  .+++++++++.                   ",
"                  .+++++++++.                   ",
"                  .+++++++++.                   ",
"                  .+++++++++.                   ",
"                  .+++++++++.                   ",
"                   .+++++++.                    ",
"                    ..+++..                     ",
"                      ...                       ",
"                                                "};

