#!/bin/sh

# No action if .mbdock exists
if [ ! -f $HOME/.matchbox/mbdock.session ]; then
  mkdir -p $HOME/.matchbox
  cp /etc/gpe/gpe.mbdock $HOME/.matchbox/mbdock.session

  gpe-question --icon !gtk-dialog-info --question "<b>Welcome to GPE!</b>

I have added some standard programs to the panel at 
the bottom of the screen.

To remove these, or add
more,  tap and hold on an 
empty area of the panel." --buttons !gtk-ok &
fi
