/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_GPE_Alarm (void)
{
  GtkWidget *GPE_Alarm;
  GtkWidget *Vbox3;
  GtkWidget *MainMenu;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *exit1;
  GtkWidget *options1;
  GtkWidget *options1_menu;
  GtkAccelGroup *options1_menu_accels;
  GtkWidget *preferences1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about1;
  GtkWidget *PseudoMain;
  GtkWidget *vbox1;
  GtkWidget *CurDateTime;
  GtkWidget *scrolledwindow1;
  GtkWidget *AlarmCList;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *hbuttonbox1;
  GtkWidget *AlarmEdit;
  GtkWidget *AlarmDelete;
  GtkWidget *NewAlarm;
  GtkWidget *scrolledwindow2;
  GtkWidget *viewport1;
  GtkWidget *vbox2;
  GtkWidget *table1;
  GtkWidget *hbox3;
  GtkWidget *AlarmType;
  GtkWidget *AlarmType_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *AlarmTry;
  GtkWidget *AlarmOptions;
  GtkWidget *hbox2;
  GtkObject *AlarmHour_adj;
  GtkWidget *AlarmHour;
  GtkWidget *label10;
  GtkObject *AlarmMinute_adj;
  GtkWidget *AlarmMinute;
  GtkWidget *AlarmComment;
  GtkWidget *AlarmReoccurence;
  GtkWidget *AlarmReoccurence_menu;
  GtkWidget *AlarmDate;
  GtkWidget *label6;
  GtkWidget *label8;
  GtkWidget *label25;
  GtkWidget *label9;
  GtkWidget *hseparator1;
  GtkWidget *hbuttonbox2;
  GtkWidget *AlarmCancel;
  GtkWidget *AlarmOK;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport2;
  GtkWidget *vbox4;
  GtkWidget *frame1;
  GtkWidget *table3;
  GtkObject *Tone1Pitch_adj;
  GtkWidget *Tone1Pitch;
  GtkObject *Tone1Duration_adj;
  GtkWidget *Tone1Duration;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *frame2;
  GtkWidget *table4;
  GtkWidget *vbox3;
  GSList *AlTone2_group = NULL;
  GtkWidget *AlTone2On;
  GtkWidget *AlTone2Off;
  GtkObject *Tone2Pitch_adj;
  GtkWidget *Tone2Pitch;
  GtkObject *Tone2Duration_adj;
  GtkWidget *Tone2Duration;
  GtkObject *ToneCount_adj;
  GtkWidget *ToneCount;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label22;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *hbox5;
  GtkWidget *label23;
  GtkObject *TonePause_adj;
  GtkWidget *TonePause;
  GtkWidget *label24;
  GtkWidget *hseparator2;
  GtkWidget *hbuttonbox4;
  GtkWidget *AlarmOptTry;
  GtkWidget *AlarmOptOK;

  GPE_Alarm = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (GPE_Alarm, "GPE_Alarm");
  gtk_object_set_data (GTK_OBJECT (GPE_Alarm), "GPE_Alarm", GPE_Alarm);
  gtk_window_set_title (GTK_WINDOW (GPE_Alarm), _("GPE Alarm"));
  gtk_window_set_default_size (GTK_WINDOW (GPE_Alarm), 240, 300);

  Vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (Vbox3, "Vbox3");
  gtk_widget_ref (Vbox3);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "Vbox3", Vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Vbox3);
  gtk_container_add (GTK_CONTAINER (GPE_Alarm), Vbox3);

  MainMenu = gtk_menu_bar_new ();
  gtk_widget_set_name (MainMenu, "MainMenu");
  gtk_widget_ref (MainMenu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "MainMenu", MainMenu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MainMenu);
  gtk_box_pack_start (GTK_BOX (Vbox3), MainMenu, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_set_name (file1, "file1");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (MainMenu), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  exit1 = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit1);

  options1 = gtk_menu_item_new_with_label (_("Options"));
  gtk_widget_set_name (options1, "options1");
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (MainMenu), options1);

  options1_menu = gtk_menu_new ();
  gtk_widget_set_name (options1_menu, "options1_menu");
  gtk_widget_ref (options1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "options1_menu", options1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options1), options1_menu);
  options1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (options1_menu));

  preferences1 = gtk_menu_item_new_with_label (_("Preferences"));
  gtk_widget_set_name (preferences1, "preferences1");
  gtk_widget_ref (preferences1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "preferences1", preferences1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (options1_menu), preferences1);

  help1 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_set_name (help1, "help1");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (MainMenu), help1);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help1));

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about1 = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  PseudoMain = gtk_notebook_new ();
  gtk_widget_set_name (PseudoMain, "PseudoMain");
  gtk_widget_ref (PseudoMain);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "PseudoMain", PseudoMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (PseudoMain);
  gtk_box_pack_start (GTK_BOX (Vbox3), PseudoMain, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (PseudoMain, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (PseudoMain), FALSE);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (PseudoMain), FALSE);
  gtk_notebook_set_tab_hborder (GTK_NOTEBOOK (PseudoMain), 0);
  gtk_notebook_set_tab_vborder (GTK_NOTEBOOK (PseudoMain), 0);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (PseudoMain), vbox1);

  CurDateTime = gtk_label_new (_("Sat, June 8, 15:54:32"));
  gtk_widget_set_name (CurDateTime, "CurDateTime");
  gtk_widget_ref (CurDateTime);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "CurDateTime", CurDateTime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (CurDateTime);
  gtk_box_pack_start (GTK_BOX (vbox1), CurDateTime, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (CurDateTime), 2, 2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  AlarmCList = gtk_clist_new (2);
  gtk_widget_set_name (AlarmCList, "AlarmCList");
  gtk_widget_ref (AlarmCList);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmCList", AlarmCList,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmCList);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), AlarmCList);
  gtk_container_set_border_width (GTK_CONTAINER (AlarmCList), 2);
  gtk_clist_set_column_width (GTK_CLIST (AlarmCList), 0, 74);
  gtk_clist_set_column_width (GTK_CLIST (AlarmCList), 1, 48);
  gtk_clist_column_titles_show (GTK_CLIST (AlarmCList));

  label2 = gtk_label_new (_("Date/Time"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_clist_set_column_widget (GTK_CLIST (AlarmCList), 0, label2);

  label3 = gtk_label_new (_("Comment"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_clist_set_column_widget (GTK_CLIST (AlarmCList), 1, label3);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 8);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox1), 60, 25);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox1), 5, 0);

  AlarmEdit = gtk_button_new_with_label (_("Edit"));
  gtk_widget_set_name (AlarmEdit, "AlarmEdit");
  gtk_widget_ref (AlarmEdit);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmEdit", AlarmEdit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmEdit);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), AlarmEdit);
  GTK_WIDGET_SET_FLAGS (AlarmEdit, GTK_CAN_DEFAULT);

  AlarmDelete = gtk_button_new_with_label (_("Delete"));
  gtk_widget_set_name (AlarmDelete, "AlarmDelete");
  gtk_widget_ref (AlarmDelete);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmDelete", AlarmDelete,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmDelete);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), AlarmDelete);
  GTK_WIDGET_SET_FLAGS (AlarmDelete, GTK_CAN_DEFAULT);

  NewAlarm = gtk_button_new_with_label (_("New"));
  gtk_widget_set_name (NewAlarm, "NewAlarm");
  gtk_widget_ref (NewAlarm);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "NewAlarm", NewAlarm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (NewAlarm);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), NewAlarm);
  GTK_WIDGET_SET_FLAGS (NewAlarm, GTK_CAN_DEFAULT);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (PseudoMain), scrolledwindow2);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), viewport1);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_NONE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (viewport1), vbox2);

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox2), table1, TRUE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 1);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_table_attach (GTK_TABLE (table1), hbox3, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  AlarmType = gtk_option_menu_new ();
  gtk_widget_set_name (AlarmType, "AlarmType");
  gtk_widget_ref (AlarmType);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmType", AlarmType,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmType);
  gtk_box_pack_start (GTK_BOX (hbox3), AlarmType, FALSE, FALSE, 0);
  AlarmType_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("None"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Tone 1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Tone 2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Tone 3"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Melody 1"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Melody 2"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Melody 3"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Custom"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmType_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (AlarmType), AlarmType_menu);

  AlarmTry = gtk_button_new_with_label (_("Try"));
  gtk_widget_set_name (AlarmTry, "AlarmTry");
  gtk_widget_ref (AlarmTry);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmTry", AlarmTry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmTry);
  gtk_box_pack_start (GTK_BOX (hbox3), AlarmTry, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (AlarmTry, FALSE);

  AlarmOptions = gtk_button_new_with_label (_("Customize"));
  gtk_widget_set_name (AlarmOptions, "AlarmOptions");
  gtk_widget_ref (AlarmOptions);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmOptions", AlarmOptions,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmOptions);
  gtk_box_pack_start (GTK_BOX (hbox3), AlarmOptions, TRUE, FALSE, 0);
  gtk_widget_set_sensitive (AlarmOptions, FALSE);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table1), hbox2, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  AlarmHour_adj = gtk_adjustment_new (1, 0, 23, 1, 10, 10);
  AlarmHour = gtk_spin_button_new (GTK_ADJUSTMENT (AlarmHour_adj), 1, 0);
  gtk_widget_set_name (AlarmHour, "AlarmHour");
  gtk_widget_ref (AlarmHour);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmHour", AlarmHour,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmHour);
  gtk_box_pack_start (GTK_BOX (hbox2), AlarmHour, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (AlarmHour), TRUE);

  label10 = gtk_label_new (_(":"));
  gtk_widget_set_name (label10, "label10");
  gtk_widget_ref (label10);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label10", label10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox2), label10, TRUE, FALSE, 0);

  AlarmMinute_adj = gtk_adjustment_new (1, 0, 59, 1, 10, 10);
  AlarmMinute = gtk_spin_button_new (GTK_ADJUSTMENT (AlarmMinute_adj), 1, 0);
  gtk_widget_set_name (AlarmMinute, "AlarmMinute");
  gtk_widget_ref (AlarmMinute);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmMinute", AlarmMinute,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmMinute);
  gtk_box_pack_start (GTK_BOX (hbox2), AlarmMinute, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (AlarmMinute), TRUE);

  AlarmComment = gtk_entry_new_with_max_length (127);
  gtk_widget_set_name (AlarmComment, "AlarmComment");
  gtk_widget_ref (AlarmComment);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmComment", AlarmComment,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmComment);
  gtk_table_attach (GTK_TABLE (table1), AlarmComment, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  AlarmReoccurence = gtk_option_menu_new ();
  gtk_widget_set_name (AlarmReoccurence, "AlarmReoccurence");
  gtk_widget_ref (AlarmReoccurence);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmReoccurence", AlarmReoccurence,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmReoccurence);
  gtk_table_attach (GTK_TABLE (table1), AlarmReoccurence, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  AlarmReoccurence_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Once"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmReoccurence_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Weekdays"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmReoccurence_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Daily"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmReoccurence_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Weekly"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmReoccurence_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Monthly"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmReoccurence_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Yearly"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (AlarmReoccurence_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (AlarmReoccurence), AlarmReoccurence_menu);

  AlarmDate = gtk_calendar_new ();
  gtk_widget_set_name (AlarmDate, "AlarmDate");
  gtk_widget_ref (AlarmDate);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmDate", AlarmDate,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmDate);
  gtk_table_attach (GTK_TABLE (table1), AlarmDate, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 2, 6);
  gtk_calendar_display_options (GTK_CALENDAR (AlarmDate),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label6 = gtk_label_new (_("Time"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  label8 = gtk_label_new (_("Alarm"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  label25 = gtk_label_new (_("Type"));
  gtk_widget_set_name (label25, "label25");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table1), label25, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label9 = gtk_label_new (_("Comment"));
  gtk_widget_set_name (label9, "label9");
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table1), label9, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator1, "hseparator1");
  gtk_widget_ref (hseparator1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hseparator1", hseparator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator1, TRUE, TRUE, 0);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, FALSE, TRUE, 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 20);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox2), 65, 25);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox2), 5, 0);

  AlarmCancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_set_name (AlarmCancel, "AlarmCancel");
  gtk_widget_ref (AlarmCancel);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmCancel", AlarmCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmCancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), AlarmCancel);
  GTK_WIDGET_SET_FLAGS (AlarmCancel, GTK_CAN_DEFAULT);

  AlarmOK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (AlarmOK, "AlarmOK");
  gtk_widget_ref (AlarmOK);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmOK", AlarmOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), AlarmOK);
  GTK_WIDGET_SET_FLAGS (AlarmOK, GTK_CAN_DEFAULT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (PseudoMain), scrolledwindow3);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport2, "viewport2");
  gtk_widget_ref (viewport2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "viewport2", viewport2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport2);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport2), GTK_SHADOW_NONE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (viewport2), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 2);

  frame1 = gtk_frame_new (_("Tone 1"));
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox4), frame1, TRUE, TRUE, 2);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (frame1), table3);

  Tone1Pitch_adj = gtk_adjustment_new (500, 10, 44100, 10, 100, 1000);
  Tone1Pitch = gtk_spin_button_new (GTK_ADJUSTMENT (Tone1Pitch_adj), 1, 0);
  gtk_widget_set_name (Tone1Pitch, "Tone1Pitch");
  gtk_widget_ref (Tone1Pitch);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "Tone1Pitch", Tone1Pitch,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Tone1Pitch);
  gtk_table_attach (GTK_TABLE (table3), Tone1Pitch, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (Tone1Pitch), TRUE);

  Tone1Duration_adj = gtk_adjustment_new (100, 10, 100000, 10, 100, 10);
  Tone1Duration = gtk_spin_button_new (GTK_ADJUSTMENT (Tone1Duration_adj), 1, 0);
  gtk_widget_set_name (Tone1Duration, "Tone1Duration");
  gtk_widget_ref (Tone1Duration);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "Tone1Duration", Tone1Duration,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Tone1Duration);
  gtk_table_attach (GTK_TABLE (table3), Tone1Duration, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (Tone1Duration), TRUE);

  label12 = gtk_label_new (_("Pitch"));
  gtk_widget_set_name (label12, "label12");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table3), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("Duration"));
  gtk_widget_set_name (label13, "label13");
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table3), label13, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("HZ"));
  gtk_widget_set_name (label14, "label14");
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table3), label14, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("ms"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table3), label15, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  frame2 = gtk_frame_new (_("Tone 2"));
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox4), frame2, TRUE, TRUE, 2);

  table4 = gtk_table_new (4, 3, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_ref (table4);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "table4", table4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (frame2), table4);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_table_attach (GTK_TABLE (table4), vbox3, 1, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  AlTone2On = gtk_radio_button_new_with_label (AlTone2_group, _("On"));
  AlTone2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (AlTone2On));
  gtk_widget_set_name (AlTone2On, "AlTone2On");
  gtk_widget_ref (AlTone2On);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlTone2On", AlTone2On,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlTone2On);
  gtk_box_pack_start (GTK_BOX (vbox3), AlTone2On, FALSE, FALSE, 0);

  AlTone2Off = gtk_radio_button_new_with_label (AlTone2_group, _("Off"));
  AlTone2_group = gtk_radio_button_group (GTK_RADIO_BUTTON (AlTone2Off));
  gtk_widget_set_name (AlTone2Off, "AlTone2Off");
  gtk_widget_ref (AlTone2Off);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlTone2Off", AlTone2Off,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlTone2Off);
  gtk_box_pack_start (GTK_BOX (vbox3), AlTone2Off, FALSE, FALSE, 0);

  Tone2Pitch_adj = gtk_adjustment_new (800, 10, 44100, 10, 100, 1000);
  Tone2Pitch = gtk_spin_button_new (GTK_ADJUSTMENT (Tone2Pitch_adj), 1, 0);
  gtk_widget_set_name (Tone2Pitch, "Tone2Pitch");
  gtk_widget_ref (Tone2Pitch);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "Tone2Pitch", Tone2Pitch,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Tone2Pitch);
  gtk_table_attach (GTK_TABLE (table4), Tone2Pitch, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (Tone2Pitch), TRUE);

  Tone2Duration_adj = gtk_adjustment_new (100, 10, 100000, 10, 100, 10);
  Tone2Duration = gtk_spin_button_new (GTK_ADJUSTMENT (Tone2Duration_adj), 1, 0);
  gtk_widget_set_name (Tone2Duration, "Tone2Duration");
  gtk_widget_ref (Tone2Duration);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "Tone2Duration", Tone2Duration,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Tone2Duration);
  gtk_table_attach (GTK_TABLE (table4), Tone2Duration, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (Tone2Duration), TRUE);

  ToneCount_adj = gtk_adjustment_new (10, 1, 100, 1, 10, 10);
  ToneCount = gtk_spin_button_new (GTK_ADJUSTMENT (ToneCount_adj), 1, 0);
  gtk_widget_set_name (ToneCount, "ToneCount");
  gtk_widget_ref (ToneCount);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "ToneCount", ToneCount,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ToneCount);
  gtk_table_attach (GTK_TABLE (table4), ToneCount, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new (_("Enable"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table4), label17, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Pitch"));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table4), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Duration"));
  gtk_widget_set_name (label19, "label19");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table4), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label22 = gtk_label_new (_("Count"));
  gtk_widget_set_name (label22, "label22");
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table4), label22, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  label20 = gtk_label_new (_("HZ"));
  gtk_widget_set_name (label20, "label20");
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table4), label20, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("ms"));
  gtk_widget_set_name (label21, "label21");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table4), label21, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox5, "hbox5");
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("Pause"));
  gtk_widget_set_name (label23, "label23");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox5), label23, FALSE, FALSE, 9);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  TonePause_adj = gtk_adjustment_new (1000, 10, 100000, 10, 100, 10);
  TonePause = gtk_spin_button_new (GTK_ADJUSTMENT (TonePause_adj), 1, 0);
  gtk_widget_set_name (TonePause, "TonePause");
  gtk_widget_ref (TonePause);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "TonePause", TonePause,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (TonePause);
  gtk_box_pack_start (GTK_BOX (hbox5), TonePause, TRUE, TRUE, 0);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (TonePause), TRUE);

  label24 = gtk_label_new (_("ms"));
  gtk_widget_set_name (label24, "label24");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 2);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_set_name (hseparator2, "hseparator2");
  gtk_widget_ref (hseparator2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hseparator2", hseparator2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator2, TRUE, TRUE, 0);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox4, "hbuttonbox4");
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox4, FALSE, FALSE, 2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox4), 20);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox4), 65, 25);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox4), 5, 0);

  AlarmOptTry = gtk_button_new_with_label (_("Try"));
  gtk_widget_set_name (AlarmOptTry, "AlarmOptTry");
  gtk_widget_ref (AlarmOptTry);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmOptTry", AlarmOptTry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmOptTry);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), AlarmOptTry);
  GTK_WIDGET_SET_FLAGS (AlarmOptTry, GTK_CAN_DEFAULT);

  AlarmOptOK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (AlarmOptOK, "AlarmOptOK");
  gtk_widget_ref (AlarmOptOK);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Alarm), "AlarmOptOK", AlarmOptOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmOptOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), AlarmOptOK);
  GTK_WIDGET_SET_FLAGS (AlarmOptOK, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (GPE_Alarm), "delete_event",
                      GTK_SIGNAL_FUNC (on_GPE_Alarm_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_Alarm), "destroy_event",
                      GTK_SIGNAL_FUNC (on_GPE_Alarm_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_Alarm), "destroy",
                      GTK_SIGNAL_FUNC (on_GPE_Alarm_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_Alarm), "key_press_event",
                      GTK_SIGNAL_FUNC (on_GPE_Alarm_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_Alarm), "button_press_event",
                      GTK_SIGNAL_FUNC (on_GPE_Alarm_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MainMenu), "deactivate",
                      GTK_SIGNAL_FUNC (on_MainMenu_deactivate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (file1), "activate",
                      GTK_SIGNAL_FUNC (on_file1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (preferences1), "activate",
                      GTK_SIGNAL_FUNC (on_preferences1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmCList), "select_row",
                      GTK_SIGNAL_FUNC (on_AlarmCList_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmCList), "unselect_row",
                      GTK_SIGNAL_FUNC (on_AlarmCList_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmEdit), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmEdit_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmDelete), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmDelete_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (NewAlarm), "clicked",
                      GTK_SIGNAL_FUNC (on_NewAlarm_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmTry), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmTry_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmOptions), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmOptions_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmHour), "changed",
                      GTK_SIGNAL_FUNC (on_AlarmHour_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmMinute), "changed",
                      GTK_SIGNAL_FUNC (on_AlarmMinute_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmComment), "changed",
                      GTK_SIGNAL_FUNC (on_AlarmComment_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmCancel), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmCancel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmOK), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmOK_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlTone2On), "toggled",
                      GTK_SIGNAL_FUNC (on_AlTone2On_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlTone2Off), "toggled",
                      GTK_SIGNAL_FUNC (on_AlTone2Off_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmOptTry), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmOptTry_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmOptOK), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmOptOK_clicked),
                      NULL);

  gtk_widget_grab_default (NewAlarm);
  return GPE_Alarm;
}

GtkWidget*
create_StopAlarmWin (void)
{
  GtkWidget *StopAlarmWin;
  GtkWidget *frame3;
  GtkWidget *hbuttonbox3;
  GtkWidget *StopAlarm;

  StopAlarmWin = gtk_window_new (GTK_WINDOW_POPUP);
  gtk_widget_set_name (StopAlarmWin, "StopAlarmWin");
  gtk_object_set_data (GTK_OBJECT (StopAlarmWin), "StopAlarmWin", StopAlarmWin);
  gtk_window_set_title (GTK_WINDOW (StopAlarmWin), _("Stop!"));
  gtk_window_set_position (GTK_WINDOW (StopAlarmWin), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (StopAlarmWin), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (StopAlarmWin), 140, 86);

  frame3 = gtk_frame_new (_("Alarm Testsound"));
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (StopAlarmWin), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_container_add (GTK_CONTAINER (StopAlarmWin), frame3);
  gtk_container_set_border_width (GTK_CONTAINER (frame3), 10);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox3, "hbuttonbox3");
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (StopAlarmWin), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_container_add (GTK_CONTAINER (frame3), hbuttonbox3);

  StopAlarm = gtk_button_new_with_label (_("Stop!"));
  gtk_widget_set_name (StopAlarm, "StopAlarm");
  gtk_widget_ref (StopAlarm);
  gtk_object_set_data_full (GTK_OBJECT (StopAlarmWin), "StopAlarm", StopAlarm,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (StopAlarm);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), StopAlarm);
  GTK_WIDGET_SET_FLAGS (StopAlarm, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (StopAlarm), "clicked",
                      GTK_SIGNAL_FUNC (on_StopAlarm_clicked),
                      NULL);

  return StopAlarmWin;
}

GtkWidget*
create_AlarmsPrefs (void)
{
  GtkWidget *AlarmsPrefs;
  GtkWidget *dialog_vbox1;
  GtkWidget *table5;
  GtkWidget *label28;
  GtkObject *AlarmMuteTimeout_adj;
  GtkWidget *AlarmMuteTimeout;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *AlarmVolume;
  GtkWidget *label27;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *table7;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *checkbutton8;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *AlwaysShowMenubar;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox5;
  GtkWidget *PrefsCancel;
  GtkWidget *PrefsOK;

  AlarmsPrefs = gtk_dialog_new ();
  gtk_widget_set_name (AlarmsPrefs, "AlarmsPrefs");
  gtk_object_set_data (GTK_OBJECT (AlarmsPrefs), "AlarmsPrefs", AlarmsPrefs);
  gtk_window_set_title (GTK_WINDOW (AlarmsPrefs), _("Alarms Preferences"));
  GTK_WINDOW (AlarmsPrefs)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (AlarmsPrefs), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (AlarmsPrefs), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (AlarmsPrefs), 235, 150);

  dialog_vbox1 = GTK_DIALOG (AlarmsPrefs)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_object_set_data (GTK_OBJECT (AlarmsPrefs), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  table5 = gtk_table_new (4, 3, FALSE);
  gtk_widget_set_name (table5, "table5");
  gtk_widget_ref (table5);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "table5", table5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), table5, TRUE, TRUE, 2);
  gtk_container_set_border_width (GTK_CONTAINER (table5), 2);

  label28 = gtk_label_new (_("Mute alarm\nsound after"));
  gtk_widget_set_name (label28, "label28");
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table5), label28, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_label_set_justify (GTK_LABEL (label28), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label28), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label28), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label28), 2, 2);

  AlarmMuteTimeout_adj = gtk_adjustment_new (60, 1, 100000, 1, 10, 10);
  AlarmMuteTimeout = gtk_spin_button_new (GTK_ADJUSTMENT (AlarmMuteTimeout_adj), 1, 0);
  gtk_widget_set_name (AlarmMuteTimeout, "AlarmMuteTimeout");
  gtk_widget_ref (AlarmMuteTimeout);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "AlarmMuteTimeout", AlarmMuteTimeout,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmMuteTimeout);
  gtk_table_attach (GTK_TABLE (table5), AlarmMuteTimeout, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);

  label29 = gtk_label_new (_("%"));
  gtk_widget_set_name (label29, "label29");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table5), label29, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label29), 0, 0.5);

  label30 = gtk_label_new (_("Sec."));
  gtk_widget_set_name (label30, "label30");
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table5), label30, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  AlarmVolume = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (60, 0, 101, 1, 1, 1)));
  gtk_widget_set_name (AlarmVolume, "AlarmVolume");
  gtk_widget_ref (AlarmVolume);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "AlarmVolume", AlarmVolume,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmVolume);
  gtk_table_attach (GTK_TABLE (table5), AlarmVolume, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_scale_set_value_pos (GTK_SCALE (AlarmVolume), GTK_POS_RIGHT);
  gtk_scale_set_digits (GTK_SCALE (AlarmVolume), 0);
  gtk_range_set_update_policy (GTK_RANGE (AlarmVolume), GTK_UPDATE_DELAYED);

  label27 = gtk_label_new (_("Alarm\nVolume"));
  gtk_widget_set_name (label27, "label27");
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table5), label27, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label27), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label27), 2, 2);

  label39 = gtk_label_new (_("Always\nshow\nmenubar"));
  gtk_widget_set_name (label39, "label39");
  gtk_widget_ref (label39);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label39", label39,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table5), label39, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label39), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label39), 2, 2);

  label40 = gtk_label_new (_("Weekdays"));
  gtk_widget_set_name (label40, "label40");
  gtk_widget_ref (label40);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label40", label40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table5), label40, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label40), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label40), 2, 2);

  table7 = gtk_table_new (2, 7, FALSE);
  gtk_widget_set_name (table7, "table7");
  gtk_widget_ref (table7);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "table7", table7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table7);
  gtk_table_attach (GTK_TABLE (table5), table7, 1, 3, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  checkbutton2 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton2, "checkbutton2");
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_table_attach (GTK_TABLE (table7), checkbutton2, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  checkbutton3 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton3, "checkbutton3");
  gtk_widget_ref (checkbutton3);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton3", checkbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton3);
  gtk_table_attach (GTK_TABLE (table7), checkbutton3, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton3), TRUE);

  checkbutton4 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton4, "checkbutton4");
  gtk_widget_ref (checkbutton4);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton4", checkbutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton4);
  gtk_table_attach (GTK_TABLE (table7), checkbutton4, 2, 3, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton4), TRUE);

  checkbutton5 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton5, "checkbutton5");
  gtk_widget_ref (checkbutton5);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton5", checkbutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton5);
  gtk_table_attach (GTK_TABLE (table7), checkbutton5, 3, 4, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton5), TRUE);

  checkbutton6 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton6, "checkbutton6");
  gtk_widget_ref (checkbutton6);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton6", checkbutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton6);
  gtk_table_attach (GTK_TABLE (table7), checkbutton6, 4, 5, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton6), TRUE);

  checkbutton7 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton7, "checkbutton7");
  gtk_widget_ref (checkbutton7);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton7", checkbutton7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton7);
  gtk_table_attach (GTK_TABLE (table7), checkbutton7, 5, 6, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton7), TRUE);

  checkbutton8 = gtk_check_button_new ();
  gtk_widget_set_name (checkbutton8, "checkbutton8");
  gtk_widget_ref (checkbutton8);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "checkbutton8", checkbutton8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton8);
  gtk_table_attach (GTK_TABLE (table7), checkbutton8, 6, 7, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label41 = gtk_label_new (_("S"));
  gtk_widget_set_name (label41, "label41");
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_table_attach (GTK_TABLE (table7), label41, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label41), 0, 0.5);

  label42 = gtk_label_new (_("M"));
  gtk_widget_set_name (label42, "label42");
  gtk_widget_ref (label42);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label42", label42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label42);
  gtk_table_attach (GTK_TABLE (table7), label42, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label42), 0, 0.5);

  label43 = gtk_label_new (_("T"));
  gtk_widget_set_name (label43, "label43");
  gtk_widget_ref (label43);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label43", label43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table7), label43, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label43), 0, 0.5);

  label44 = gtk_label_new (_("W"));
  gtk_widget_set_name (label44, "label44");
  gtk_widget_ref (label44);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label44", label44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table7), label44, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);

  label45 = gtk_label_new (_("T"));
  gtk_widget_set_name (label45, "label45");
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table7), label45, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label45), 0, 0.5);

  label46 = gtk_label_new (_("F"));
  gtk_widget_set_name (label46, "label46");
  gtk_widget_ref (label46);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label46", label46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table7), label46, 5, 6, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  label47 = gtk_label_new (_("S"));
  gtk_widget_set_name (label47, "label47");
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table7), label47, 6, 7, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 3, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  AlwaysShowMenubar = gtk_check_button_new ();
  gtk_widget_set_name (AlwaysShowMenubar, "AlwaysShowMenubar");
  gtk_widget_ref (AlwaysShowMenubar);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "AlwaysShowMenubar", AlwaysShowMenubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlwaysShowMenubar);
  gtk_table_attach (GTK_TABLE (table5), AlwaysShowMenubar, 1, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (AlwaysShowMenubar), 2);

  dialog_action_area1 = GTK_DIALOG (AlarmsPrefs)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (AlarmsPrefs), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox5, "hbuttonbox5");
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox5, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox5), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox5), 20);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox5), 70, 25);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox5), 5, 0);

  PrefsCancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_set_name (PrefsCancel, "PrefsCancel");
  gtk_widget_ref (PrefsCancel);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "PrefsCancel", PrefsCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (PrefsCancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), PrefsCancel);
  GTK_WIDGET_SET_FLAGS (PrefsCancel, GTK_CAN_DEFAULT);

  PrefsOK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (PrefsOK, "PrefsOK");
  gtk_widget_ref (PrefsOK);
  gtk_object_set_data_full (GTK_OBJECT (AlarmsPrefs), "PrefsOK", PrefsOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (PrefsOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), PrefsOK);
  GTK_WIDGET_SET_FLAGS (PrefsOK, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (AlarmsPrefs), "delete_event",
                      GTK_SIGNAL_FUNC (on_AlarmsPrefs_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmsPrefs), "destroy_event",
                      GTK_SIGNAL_FUNC (on_AlarmsPrefs_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmsPrefs), "destroy",
                      GTK_SIGNAL_FUNC (on_AlarmsPrefs_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (PrefsCancel), "clicked",
                      GTK_SIGNAL_FUNC (on_PrefsCancel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (PrefsOK), "clicked",
                      GTK_SIGNAL_FUNC (on_PrefsOK_clicked),
                      NULL);

  gtk_widget_grab_default (PrefsOK);
  return AlarmsPrefs;
}

GtkWidget*
create_AlarmAbout (void)
{
  GtkWidget *AlarmAbout;
  GtkWidget *dialog_vbox2;
  GtkWidget *vbox5;
  GtkWidget *pixmap1;
  GtkWidget *label31;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox6;
  GtkWidget *AlarmAboutOK;

  AlarmAbout = gtk_dialog_new ();
  gtk_widget_set_name (AlarmAbout, "AlarmAbout");
  gtk_object_set_data (GTK_OBJECT (AlarmAbout), "AlarmAbout", AlarmAbout);
  gtk_window_set_title (GTK_WINDOW (AlarmAbout), _("About"));
  GTK_WINDOW (AlarmAbout)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (AlarmAbout), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (AlarmAbout), TRUE);

  dialog_vbox2 = GTK_DIALOG (AlarmAbout)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_object_set_data (GTK_OBJECT (AlarmAbout), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (AlarmAbout), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), vbox5, TRUE, TRUE, 0);

  pixmap1 = create_pixmap (AlarmAbout, "bell.xpm");
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (AlarmAbout), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_box_pack_start (GTK_BOX (vbox5), pixmap1, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (pixmap1), 0, 7);

  label31 = gtk_label_new (_("GPE-Alarm\n\nAlarm controller application\n(c) 2002 by Nils Faerber\n<nils@kernelconcepts.de>\n\nLicense: GPL\n"));
  gtk_widget_set_name (label31, "label31");
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (AlarmAbout), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (vbox5), label31, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label31), 20, 0);

  dialog_action_area2 = GTK_DIALOG (AlarmAbout)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_object_set_data (GTK_OBJECT (AlarmAbout), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox6, "hbuttonbox6");
  gtk_widget_ref (hbuttonbox6);
  gtk_object_set_data_full (GTK_OBJECT (AlarmAbout), "hbuttonbox6", hbuttonbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox6);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox6, FALSE, FALSE, 0);

  AlarmAboutOK = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (AlarmAboutOK, "AlarmAboutOK");
  gtk_widget_ref (AlarmAboutOK);
  gtk_object_set_data_full (GTK_OBJECT (AlarmAbout), "AlarmAboutOK", AlarmAboutOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmAboutOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), AlarmAboutOK);
  GTK_WIDGET_SET_FLAGS (AlarmAboutOK, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (AlarmAbout), "delete_event",
                      GTK_SIGNAL_FUNC (on_AlarmAbout_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmAbout), "destroy_event",
                      GTK_SIGNAL_FUNC (on_AlarmAbout_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmAbout), "destroy",
                      GTK_SIGNAL_FUNC (on_AlarmAbout_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmAboutOK), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmAboutOK_clicked),
                      NULL);

  return AlarmAbout;
}

GtkWidget*
create_AlarmWin (void)
{
  GtkWidget *AlarmWin;
  GtkWidget *dialog_vbox3;
  GtkWidget *frame4;
  GtkWidget *table6;
  GtkWidget *pixmap2;
  GtkWidget *label38;
  GtkWidget *label37;
  GtkWidget *label36;
  GtkWidget *AlarmComment;
  GtkWidget *AlarmTime;
  GtkWidget *AlarmDate;
  GtkWidget *label32;
  GtkWidget *dialog_action_area3;
  GtkWidget *vbox6;
  GtkWidget *hbuttonbox8;
  GtkWidget *AlarmMute;
  GtkWidget *AlarmDelay;
  GtkWidget *hbuttonbox7;
  GtkWidget *AlarmACK;

  AlarmWin = gtk_dialog_new ();
  gtk_widget_set_name (AlarmWin, "AlarmWin");
  gtk_object_set_data (GTK_OBJECT (AlarmWin), "AlarmWin", AlarmWin);
  gtk_window_set_title (GTK_WINDOW (AlarmWin), _("Alarm!"));
  GTK_WINDOW (AlarmWin)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (AlarmWin), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (AlarmWin), TRUE);

  dialog_vbox3 = GTK_DIALOG (AlarmWin)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_object_set_data (GTK_OBJECT (AlarmWin), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), frame4, TRUE, TRUE, 3);

  table6 = gtk_table_new (5, 2, FALSE);
  gtk_widget_set_name (table6, "table6");
  gtk_widget_ref (table6);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "table6", table6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table6);
  gtk_container_add (GTK_CONTAINER (frame4), table6);

  pixmap2 = create_pixmap (AlarmWin, "bell.xpm");
  gtk_widget_set_name (pixmap2, "pixmap2");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_table_attach (GTK_TABLE (table6), pixmap2, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 6);

  label38 = gtk_label_new (_("Comment"));
  gtk_widget_set_name (label38, "label38");
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table6), label38, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label38), 0, 0.5);

  label37 = gtk_label_new (_("Time"));
  gtk_widget_set_name (label37, "label37");
  gtk_widget_ref (label37);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "label37", label37,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table6), label37, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label37), 0, 0.5);

  label36 = gtk_label_new (_("Date"));
  gtk_widget_set_name (label36, "label36");
  gtk_widget_ref (label36);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "label36", label36,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table6), label36, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  AlarmComment = gtk_entry_new ();
  gtk_widget_set_name (AlarmComment, "AlarmComment");
  gtk_widget_ref (AlarmComment);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "AlarmComment", AlarmComment,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmComment);
  gtk_table_attach (GTK_TABLE (table6), AlarmComment, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 4);
  gtk_entry_set_editable (GTK_ENTRY (AlarmComment), FALSE);

  AlarmTime = gtk_label_new (_("14:50"));
  gtk_widget_set_name (AlarmTime, "AlarmTime");
  gtk_widget_ref (AlarmTime);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "AlarmTime", AlarmTime,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmTime);
  gtk_table_attach (GTK_TABLE (table6), AlarmTime, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_label_set_justify (GTK_LABEL (AlarmTime), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (AlarmTime), 0, 0.5);

  AlarmDate = gtk_label_new (_("06/16/02"));
  gtk_widget_set_name (AlarmDate, "AlarmDate");
  gtk_widget_ref (AlarmDate);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "AlarmDate", AlarmDate,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmDate);
  gtk_table_attach (GTK_TABLE (table6), AlarmDate, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_label_set_justify (GTK_LABEL (AlarmDate), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (AlarmDate), 0, 0.5);

  label32 = gtk_label_new (_("Alarm time has been reached for:"));
  gtk_widget_set_name (label32, "label32");
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table6), label32, 0, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 2, 5);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  dialog_action_area3 = GTK_DIALOG (AlarmWin)->action_area;
  gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_object_set_data (GTK_OBJECT (AlarmWin), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area3), 10);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (dialog_action_area3), vbox6, TRUE, TRUE, 0);

  hbuttonbox8 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox8, "hbuttonbox8");
  gtk_widget_ref (hbuttonbox8);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "hbuttonbox8", hbuttonbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox8);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox8, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox8), 20);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox8), 65, 25);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox8), 3, 0);

  AlarmMute = gtk_button_new_with_label (_("Mute"));
  gtk_widget_set_name (AlarmMute, "AlarmMute");
  gtk_widget_ref (AlarmMute);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "AlarmMute", AlarmMute,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmMute);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), AlarmMute);
  GTK_WIDGET_SET_FLAGS (AlarmMute, GTK_CAN_DEFAULT);

  AlarmDelay = gtk_button_new_with_label (_("Snooze"));
  gtk_widget_set_name (AlarmDelay, "AlarmDelay");
  gtk_widget_ref (AlarmDelay);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "AlarmDelay", AlarmDelay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmDelay);
  gtk_container_add (GTK_CONTAINER (hbuttonbox8), AlarmDelay);
  GTK_WIDGET_SET_FLAGS (AlarmDelay, GTK_CAN_DEFAULT);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox7, "hbuttonbox7");
  gtk_widget_ref (hbuttonbox7);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "hbuttonbox7", hbuttonbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox7);
  gtk_box_pack_start (GTK_BOX (vbox6), hbuttonbox7, TRUE, TRUE, 0);

  AlarmACK = gtk_button_new_with_label (_("Acknowledge"));
  gtk_widget_set_name (AlarmACK, "AlarmACK");
  gtk_widget_ref (AlarmACK);
  gtk_object_set_data_full (GTK_OBJECT (AlarmWin), "AlarmACK", AlarmACK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AlarmACK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), AlarmACK);
  gtk_container_set_border_width (GTK_CONTAINER (AlarmACK), 4);
  GTK_WIDGET_SET_FLAGS (AlarmACK, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (AlarmWin), "delete_event",
                      GTK_SIGNAL_FUNC (on_AlarmWin_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmWin), "destroy_event",
                      GTK_SIGNAL_FUNC (on_AlarmWin_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmWin), "destroy",
                      GTK_SIGNAL_FUNC (on_AlarmWin_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmMute), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmMute_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmDelay), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmDelay_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (AlarmACK), "clicked",
                      GTK_SIGNAL_FUNC (on_AlarmACK_clicked),
                      NULL);

  gtk_widget_grab_default (AlarmACK);
  return AlarmWin;
}

