#!/bin/sh
#

XSERVER=Xipaq
if [ -f /usr/bin/Xfbdev ]; then
  XSERVER=Xfbdev
fi
if [ -f /usr/bin/Xepson ]; then
  XSERVER=Xepson
fi
if [ -f /usr/bin/Xorg ]; then
  XSERVER=Xorg
fi
if [ -f /usr/bin/Xomap ]; then
  XSERVER=Xomap
fi
if [ -f /usr/bin/Xw100 ]; then
  XSERVER=Xw100
fi
if [ -f /usr/bin/Xvesa ]; then
  XSERVER=Xvesa
fi
if [ -f /usr/bin/Ximageon ]; then
  XSERVER=Ximageon
fi

. /etc/profile

module_id() {
    ## used to read from assets, but sometimes assets is corrupted
    # grep "Module ID" /proc/hal/assets | sed "s/.*://"
    ## used to read from /proc/hal/model, but that is removed in 2.6
    # echo ' iPAQ' `cat /proc/hal/model`
    awk 'BEGIN { FS=": " } /Hardware/ { print $2 } ' </proc/cpuinfo
}

export USER=root

ARGS="-br -pn $INPUT_EXTRA_ARGS"

# use ucb 1x00 touchscreen if present
if [ -z "$TSLIB_TSDEVICE" ] && [ -e /dev/touchscreen/ucb1x00 ]; then
  ARGS="$ARGS -mouse /dev/touchscreen/ucb1x00"
fi

# use usb mouse if present
# Xorg doesn't support "-mouse" option, and uses /dev/input/mice automatically
if [ -z "$TSLIB_TSDEVICE" ] && [ -e /dev/input/mice ] && [ "$XSERVER" != "Xorg" ]; then
  ARGS="$ARGS -mouse /dev/input/mice"
fi

# start off server in conventional location.
case `module_id` in
	"HP iPAQ H3100" | "HP iPAQ H3800")
		ARGS="$ARGS -dpi 100 -rgba vrgb -screen 320x240@90" ;;
	"HP iPAQ H3600" | "HP iPAQ H3700" | "HP iPAQ H3900")
		ARGS="$ARGS -dpi 100 -rgba vbgr -screen 320x240@270" ;;
	"HP iPAQ H5400" | "HP iPAQ H2200")
		ARGS="$ARGS -dpi 100 -rgba rgb" ;;
        "HP iPAQ HX4700")
                ARGS="$ARGS -dpi 200" ;;
	"Ramses")
		# What is this "vt2" in aid of?
		ARGS="$ARGS -dpi 100 -rgba vrgb -screen 320x240@90 vt2" ;;
	# both 'Sharp-Collie' and just 'Collie' have been reported
	*Poodle)
		ARGS="$ARGS -dpi 100 -rgba vrgb -screen 320x240@270" ;;
	*Collie)
		ARGS="$ARGS -dpi 100 -rgba vrgb -screen 320x240@270"
		;;
	"SHARP Shepherd" | "SHARP Husky" | "SHARP Corgi")
		ARGS="$ARGS -dpi 200 -rgba rgb" ;;
	"SHARP Spitz" | "SHARP Akita" | "SHARP Borzoi")
		ARGS="$ARGS -dpi 200 -rgba rgb -screen 480x640@270" ;;
	"Simpad")
		ARGS="$ARGS -dpi 100 -rgba rgb" ;;
	"Generic OMAP1510/1610/1710")
		ARGS="$ARGS -dpi 220 -mouse /dev/input/event0" ;;
	"Cellon C8000 Board")
		ARGS="$ARGS -dpi 100 -screen 240x320,10,1" ;;
	"HTC Universal")
		ARGS="$ARGS -dpi 100 -screen 480x640@270" ;;
	"HTC Tornado")
		ARGS="$ARGS -dpi 100 -hide-cursor" ;;
	"Atmel AT91SAM9261-EK" | "Atmel AT91SAM9263-EK")
		ARGS="$ARGS -mouse tslib -dpi 100 -rgba bgr -screen 240x320" ;;	
	"Nokia N800")
		ARGS="$ARGS -dpi 225 -screen 800x480x16 -mouse tslib" ;;
 	"GTA01")
         #we set 100 dpi for the time being, should the -dpi 285
		ARGS="$ARGS -dpi 100 -screen 480x640" ;;
	# This is a fallback for PCs
	"")
		if [ -f /usr/bin/Xvesa ]; then
			ARGS="$ARGS -dpi 100 -mode 0x0117"
		else
			ARGS="$ARGS -dpi 100"
		fi
esac

exec $XSERVER $ARGS $*
