<?php
$addtitle="API Documentation";
$pagename="apidocs";
$author="Florian Boor";
$authoremail="florian@linuxtogo.org";

include ("../includes/head.php");
?>
<h2>GPE API Documentation</h2>
<h3>libcontactsdb</h3>
<pre>29% symbol docs coverage</pre>
<p>
<a href="libcontactsdb/index.html">Reference Manual (html, online)</a><br>
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libcontactsdb/">Source (viewcvs)</a>
</p>

<h3>libeventdb</h3>
<pre>48% symbol docs coverage</pre>
<p>
<a href="libeventdb/index.html">Reference Manual (html, online)</a><br>
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libeventdb/">Source (viewcvs)</a>
</p>

<h3>libschedule</h3>
<pre>100% symbol docs coverage</pre>
<p>
<a href="libschedule/index.html">Reference Manual (html, online)</a><br>
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libschedule/">Source (viewcvs)</a>
</p>

<h3>libtododb</h3>
<pre>92% symbol docs coverage</pre>
<p>
<a href="libtododb/index.html">Reference Manual (html, online)</a><br>
<a href="libtododb/libtodotb-doc-devhelp.tar.gz">Devhelp Book (html,
comtressed tar archive</a><br>
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libtododb/">Source (viewcvs)</a>
</p>

<h3>libgpevtype</h3>
<pre>100% symbol docs coverage</pre>
<p>
<a href="libgpevtype/index.html">Reference Manual (html, online)</a><br>
<a href="libgpevtype/libgpevtype-doc-devhelp.tar.gz">Devhelp Book (html,
comtressed tar archive</a><br>
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libgpevtype/">Source (viewcvs)</a>
</p>

<h3>libgpewidget</h3>
<pre>88% symbol docs coverage (165 symbols documented, 29 symbols incomplete, 23 not documented)</pre>
<p>
<a href="libgpewidget/index.html">Reference Manual (html, online)</a><br>
<!-- <a href="libgpewidget/libgpewidget-doc-devhelp.tar.gz">Devhelp Book (html,
comtressed tar archive</a><br>-->
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libgpewidget/">Source (viewcvs)</a>
</p>

<h3>libgpepimc</h3>
<pre>100% symbol docs coverage</pre>
<p>
<a href="libgpepimc/index.html">Reference Manual (html, online)</a><br>
<!-- <a href="libgpepimc/libgpewidget-doc-devhelp.tar.gz">Devhelp Book (html,
comtressed tar archive</a><br>-->
<a href="http://handhelds.org/cgi-bin/cvsweb.cgi/gpe/base/libgpepimc/">Source (viewcvs)</a>
</p>

<h2>GPE Application Documentation</h2>
<p>
<a href="http://gpe.handhelds.org/documentation.phtml">GPE Application documentation at handhelds.org</a>.
</p>

<?php include ("../includes/foot.php"); ?>
