/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_GPE_Ownerinfo (void)
{
  GtkWidget *GPE_Ownerinfo;
  GtkWidget *frame1;
  GtkWidget *table1;
  GtkWidget *owner_name_label;
  GtkWidget *name;
  GtkWidget *owner_email_label;
  GtkWidget *email;
  GtkWidget *owner_phone_label;
  GtkWidget *phone;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *address;
  GtkWidget *vbox1;
  GtkWidget *owner_address_label;
  GtkWidget *photobutton;
  GtkWidget *pixmap1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  GPE_Ownerinfo = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (GPE_Ownerinfo, "GPE_Ownerinfo");
  gtk_object_set_data (GTK_OBJECT (GPE_Ownerinfo), "GPE_Ownerinfo", GPE_Ownerinfo);
  gtk_window_set_title (GTK_WINDOW (GPE_Ownerinfo), _("GPE Owner Info"));
  gtk_window_set_default_size (GTK_WINDOW (GPE_Ownerinfo), 240, 120);
  gtk_window_set_policy (GTK_WINDOW (GPE_Ownerinfo), TRUE, TRUE, TRUE);

  frame1 = gtk_frame_new (_("Owner Info"));
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_container_add (GTK_CONTAINER (GPE_Ownerinfo), frame1);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame1), table1);

  owner_name_label = gtk_label_new (_("Name"));
  gtk_widget_set_name (owner_name_label, "owner_name_label");
  gtk_widget_ref (owner_name_label);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "owner_name_label", owner_name_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (owner_name_label);
  gtk_table_attach (GTK_TABLE (table1), owner_name_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (owner_name_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (owner_name_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (owner_name_label), 5, 0);

  name = gtk_label_new (_("Foo Bar"));
  gtk_widget_set_name (name, "name");
  gtk_widget_ref (name);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "name", name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (name);
  gtk_table_attach (GTK_TABLE (table1), name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (name), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (name), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (name), 5, 0);

  owner_email_label = gtk_label_new (_("E-Mail"));
  gtk_widget_set_name (owner_email_label, "owner_email_label");
  gtk_widget_ref (owner_email_label);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "owner_email_label", owner_email_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (owner_email_label);
  gtk_table_attach (GTK_TABLE (table1), owner_email_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (owner_email_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (owner_email_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (owner_email_label), 5, 0);

  email = gtk_label_new (_("nobody@localhost"));
  gtk_widget_set_name (email, "email");
  gtk_widget_ref (email);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "email", email,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (email);
  gtk_table_attach (GTK_TABLE (table1), email, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (email), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (email), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (email), 5, 0);

  owner_phone_label = gtk_label_new (_("Phone"));
  gtk_widget_set_name (owner_phone_label, "owner_phone_label");
  gtk_widget_ref (owner_phone_label);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "owner_phone_label", owner_phone_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (owner_phone_label);
  gtk_table_attach (GTK_TABLE (table1), owner_phone_label, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (owner_phone_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (owner_phone_label), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (owner_phone_label), 5, 0);

  phone = gtk_label_new (_("+99 (9999) 999-9999"));
  gtk_widget_set_name (phone, "phone");
  gtk_widget_ref (phone);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "phone", phone,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (phone);
  gtk_table_attach (GTK_TABLE (table1), phone, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (phone), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (phone), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (phone), 5, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow1, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_NONE);

  address = gtk_label_new (_("Nosuch Lane 42\nX-12345 Quux\nFoobarland"));
  gtk_widget_set_name (address, "address");
  gtk_widget_ref (address);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "address", address,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (address);
  gtk_container_add (GTK_CONTAINER (viewport1), address);
  gtk_label_set_justify (GTK_LABEL (address), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (address), 0, 0);
  gtk_misc_set_padding (GTK_MISC (address), 5, 0);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_table_attach (GTK_TABLE (table1), vbox1, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  owner_address_label = gtk_label_new (_("Address"));
  gtk_widget_set_name (owner_address_label, "owner_address_label");
  gtk_widget_ref (owner_address_label);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "owner_address_label", owner_address_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (owner_address_label);
  gtk_box_pack_start (GTK_BOX (vbox1), owner_address_label, FALSE, FALSE, 1);
  gtk_label_set_justify (GTK_LABEL (owner_address_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (owner_address_label), 0, 0);
  gtk_misc_set_padding (GTK_MISC (owner_address_label), 5, 0);

  photobutton = gtk_button_new ();
  gtk_widget_set_name (photobutton, "photobutton");
  gtk_widget_ref (photobutton);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "photobutton", photobutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (photobutton);
  gtk_box_pack_end (GTK_BOX (vbox1), photobutton, TRUE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, photobutton, _("Owner photo"), NULL);
  gtk_button_set_relief (GTK_BUTTON (photobutton), GTK_RELIEF_NONE);

  pixmap1 = gpe_render_icon (GPE_Ownerinfo->style, gpe_find_icon ("tux-48"));
  //  pixmap1 = create_pixmap (GPE_Ownerinfo, NULL);
  gtk_widget_set_name (pixmap1, "pixmap1");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_Ownerinfo), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_container_add (GTK_CONTAINER (photobutton), pixmap1);

  gtk_signal_connect (GTK_OBJECT (GPE_Ownerinfo), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (photobutton), "clicked",
                      GTK_SIGNAL_FUNC (on_photobutton_clicked),
                      NULL);

  gtk_widget_grab_focus (photobutton);
  gtk_object_set_data (GTK_OBJECT (GPE_Ownerinfo), "tooltips", tooltips);

  return GPE_Ownerinfo;
}

