.\" gpe-julia.1 - Julia/Mandelbrot set generator for GPE
.\" Copyright 2003  Moray Allan
.TH gpe-julia 1 "Jun 9 2003" "version 0.0.4"
.SH NAME
gpe-julia \- Julia/Mandelbrot set generator for GPE
.SH SYNOPSIS
.B gpe-julia
.SH DESCRIPTION
.B gpe-julia
is a fixed-point fractal drawing program for the GPE Palmtop
Environment. It can draw the Julia set for a particular point, or the
Mandelbrot set. You can zoom in to look more closely at areas of interest.

.SH AUTHOR
.B gpe-julia
was written by Moray Allan <moray@sermisy.org>.

