#! /bin/sh

#init scrupt for usqld server (nicked(tm) from the ssh ipkg)
test -x /usr/sbin/usqld || exit 0

# Configurable options:

case "$1" in
  start)
 
       echo -n "Starting usqld database server : usqld"
	start-stop-daemon --start --quiet --pidfile /var/run/usqld.pid --exec /usr/sbin/usqld
        echo "."
	;;
  stop)
 
        echo -n "Stopping usqld database server : usqld"
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/usqld.pid --exec /usr/sbin/usqld
        echo "."
	;;

  restart)
        echo -n "restarting usqld database server : usqld"
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/usqld.pid --exec /usr/sbin/usqld
	sleep 3
	start-stop-daemon --start --quiet --pidfile /var/run/usqld.pid --exec /usr/sbin/usqld
	echo "."
	;;

  *)
	echo "Usage: /etc/init.d/usqld {start|stop|restart}"
	exit 1
esac

exit 0
