#!/bin/sh

GEOMETRY=
if [ -x /usr/bin/gpe-ownerinfo ]; then
  GEOMETRY="-geometry 240x200+0+0"
fi
TRANSPARENT=
if [ -x /usr/X11R6/bin/xsetroot ]; then
  TRANSPARENT="--transparent"
fi
#HARD=--hard

GTK2_RC_FILES=/etc/X11/gpe-login.gtkrc /usr/bin/gpe-login $HARD $TRANSPARENT $GEOMETRY
