.\" gpe-contacts.1 - contacts manager for GPE
.\" Copyright 2003  Moray Allan
.TH gpe-todo 1 "Jul 16 2003" "version 0.14"
.SH NAME
gpe-contacts \- contact manager for GPE
.SH SYNOPSIS
.B gpe-contacts
.SH DESCRIPTION
.B gpe-contacts
is a simple contact manager for the GPE Palmtop Environment. It helps
you organise records of people's names, addresses, and other contact
information.

.SH AUTHOR
.B gpe-contacts
was written by Philip Blundell <philb@gnu.org>.

