/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_main (void)
{
  GtkWidget *main;
  GtkWidget *vbox1;
  GtkWidget *nbList;
  GtkWidget *clist1;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *label46a;
  GtkWidget *clist2;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label47;
  GtkWidget *clist3;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *label48;
  GtkWidget *clist4;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label49;
  GtkWidget *clist5;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label50;
  GtkWidget *clist6;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label51;
  GtkWidget *clist7;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label52;
  GtkWidget *hbox3;
  GtkWidget *label83;
  GtkWidget *entry1;
  GtkWidget *frame1;
  GtkWidget *table1;
  GtkWidget *label73;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *lPhone;
  GtkWidget *lMail;
  GtkWidget *lMobile;
  GtkWidget *lFAX;

  main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (main, "main");
  gtk_object_set_data (GTK_OBJECT (main), "main", main);
  gtk_widget_set_usize (main, 240, 320);
  gtk_window_set_title (GTK_WINDOW (main), _("Contacts"));
  gtk_window_set_default_size (GTK_WINDOW (main), 240, 320);
  gtk_window_set_policy (GTK_WINDOW (main), FALSE, FALSE, FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (main), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main), vbox1);

  nbList = gtk_notebook_new ();
  gtk_widget_set_name (nbList, "nbList");
  gtk_widget_ref (nbList);
  gtk_object_set_data_full (GTK_OBJECT (main), "nbList", nbList,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (nbList);
  gtk_box_pack_start (GTK_BOX (vbox1), nbList, TRUE, TRUE, 0);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (nbList), FALSE);
  gtk_notebook_set_tab_hborder (GTK_NOTEBOOK (nbList), 1);
  gtk_notebook_set_tab_vborder (GTK_NOTEBOOK (nbList), 0);

  clist1 = gtk_clist_new (2);
  gtk_widget_set_name (clist1, "clist1");
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (nbList), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist1));

  label45 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label45, "label45");
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (main), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, label45);

  label46 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label46, "label46");
  gtk_widget_ref (label46);
  gtk_object_set_data_full (GTK_OBJECT (main), "label46", label46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, label46);

  label46a = gtk_label_new (_("ABC"));
  gtk_widget_set_name (label46a, "label46a");
  gtk_widget_ref (label46a);
  gtk_object_set_data_full (GTK_OBJECT (main), "label46a", label46a,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label46a);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 0), label46a);

  clist2 = gtk_clist_new (2);
  gtk_widget_set_name (clist2, "clist2");
  gtk_widget_ref (clist2);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist2", clist2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist2);
  gtk_container_add (GTK_CONTAINER (nbList), clist2);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist2));

  label53 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label53, "label53");
  gtk_widget_ref (label53);
  gtk_object_set_data_full (GTK_OBJECT (main), "label53", label53,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label53);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, label53);

  label54 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label54, "label54");
  gtk_widget_ref (label54);
  gtk_object_set_data_full (GTK_OBJECT (main), "label54", label54,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label54);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, label54);

  label47 = gtk_label_new (_("DEF"));
  gtk_widget_set_name (label47, "label47");
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (main), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 1), label47);

  clist3 = gtk_clist_new (2);
  gtk_widget_set_name (clist3, "clist3");
  gtk_widget_ref (clist3);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist3", clist3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist3);
  gtk_container_add (GTK_CONTAINER (nbList), clist3);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist3), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist3));

  label81 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label81, "label81");
  gtk_widget_ref (label81);
  gtk_object_set_data_full (GTK_OBJECT (main), "label81", label81,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label81);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 0, label81);

  label82 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label82, "label82");
  gtk_widget_ref (label82);
  gtk_object_set_data_full (GTK_OBJECT (main), "label82", label82,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label82);
  gtk_clist_set_column_widget (GTK_CLIST (clist3), 1, label82);

  label48 = gtk_label_new (_("GHIJ"));
  gtk_widget_set_name (label48, "label48");
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (main), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 2), label48);

  clist4 = gtk_clist_new (2);
  gtk_widget_set_name (clist4, "clist4");
  gtk_widget_ref (clist4);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist4", clist4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist4);
  gtk_container_add (GTK_CONTAINER (nbList), clist4);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist4), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist4));

  label57 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label57, "label57");
  gtk_widget_ref (label57);
  gtk_object_set_data_full (GTK_OBJECT (main), "label57", label57,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label57);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 0, label57);

  label58 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label58, "label58");
  gtk_widget_ref (label58);
  gtk_object_set_data_full (GTK_OBJECT (main), "label58", label58,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label58);
  gtk_clist_set_column_widget (GTK_CLIST (clist4), 1, label58);

  label49 = gtk_label_new (_("KLMN"));
  gtk_widget_set_name (label49, "label49");
  gtk_widget_ref (label49);
  gtk_object_set_data_full (GTK_OBJECT (main), "label49", label49,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label49);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 3), label49);

  clist5 = gtk_clist_new (2);
  gtk_widget_set_name (clist5, "clist5");
  gtk_widget_ref (clist5);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist5", clist5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist5);
  gtk_container_add (GTK_CONTAINER (nbList), clist5);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist5), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist5));

  label59 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label59, "label59");
  gtk_widget_ref (label59);
  gtk_object_set_data_full (GTK_OBJECT (main), "label59", label59,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label59);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 0, label59);

  label60 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label60, "label60");
  gtk_widget_ref (label60);
  gtk_object_set_data_full (GTK_OBJECT (main), "label60", label60,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label60);
  gtk_clist_set_column_widget (GTK_CLIST (clist5), 1, label60);

  label50 = gtk_label_new (_("OPQR"));
  gtk_widget_set_name (label50, "label50");
  gtk_widget_ref (label50);
  gtk_object_set_data_full (GTK_OBJECT (main), "label50", label50,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label50);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 4), label50);

  clist6 = gtk_clist_new (2);
  gtk_widget_set_name (clist6, "clist6");
  gtk_widget_ref (clist6);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist6", clist6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist6);
  gtk_container_add (GTK_CONTAINER (nbList), clist6);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist6), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist6));

  label61 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label61, "label61");
  gtk_widget_ref (label61);
  gtk_object_set_data_full (GTK_OBJECT (main), "label61", label61,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label61);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 0, label61);

  label62 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label62, "label62");
  gtk_widget_ref (label62);
  gtk_object_set_data_full (GTK_OBJECT (main), "label62", label62,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label62);
  gtk_clist_set_column_widget (GTK_CLIST (clist6), 1, label62);

  label51 = gtk_label_new (_("STUV"));
  gtk_widget_set_name (label51, "label51");
  gtk_widget_ref (label51);
  gtk_object_set_data_full (GTK_OBJECT (main), "label51", label51,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label51);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 5), label51);

  clist7 = gtk_clist_new (2);
  gtk_widget_set_name (clist7, "clist7");
  gtk_widget_ref (clist7);
  gtk_object_set_data_full (GTK_OBJECT (main), "clist7", clist7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist7);
  gtk_container_add (GTK_CONTAINER (nbList), clist7);
  gtk_clist_set_column_width (GTK_CLIST (clist7), 0, 80);
  gtk_clist_set_column_width (GTK_CLIST (clist7), 1, 80);
  gtk_clist_column_titles_hide (GTK_CLIST (clist7));
  gtk_clist_set_shadow_type (GTK_CLIST (clist7), GTK_SHADOW_NONE);

  label63 = gtk_label_new (_("label45"));
  gtk_widget_set_name (label63, "label63");
  gtk_widget_ref (label63);
  gtk_object_set_data_full (GTK_OBJECT (main), "label63", label63,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label63);
  gtk_clist_set_column_widget (GTK_CLIST (clist7), 0, label63);

  label64 = gtk_label_new (_("label46"));
  gtk_widget_set_name (label64, "label64");
  gtk_widget_ref (label64);
  gtk_object_set_data_full (GTK_OBJECT (main), "label64", label64,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label64);
  gtk_clist_set_column_widget (GTK_CLIST (clist7), 1, label64);

  label52 = gtk_label_new (_("WXYZ"));
  gtk_widget_set_name (label52, "label52");
  gtk_widget_ref (label52);
  gtk_object_set_data_full (GTK_OBJECT (main), "label52", label52,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label52);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (nbList), gtk_notebook_get_nth_page (GTK_NOTEBOOK (nbList), 6), label52);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (main), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0);

  label83 = gtk_label_new (_("Find:"));
  gtk_widget_set_name (label83, "label83");
  gtk_widget_ref (label83);
  gtk_object_set_data_full (GTK_OBJECT (main), "label83", label83,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label83);
  gtk_box_pack_start (GTK_BOX (hbox3), label83, FALSE, FALSE, 0);

  entry1 = gtk_entry_new ();
  gtk_widget_set_name (entry1, "entry1");
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (main), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox3), entry1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (_("Contact"));
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (main), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, FALSE, TRUE, 0);

  table1 = gtk_table_new (4, 2, FALSE);
  gtk_widget_set_name (table1, "table1");
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (main), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame1), table1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 6);

  label73 = gtk_label_new (_("Phone"));
  gtk_widget_set_name (label73, "label73");
  gtk_widget_ref (label73);
  gtk_object_set_data_full (GTK_OBJECT (main), "label73", label73,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label73);
  gtk_table_attach (GTK_TABLE (table1), label73, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label73), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label73), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label73), 2, 0);

  label74 = gtk_label_new (_("Mail"));
  gtk_widget_set_name (label74, "label74");
  gtk_widget_ref (label74);
  gtk_object_set_data_full (GTK_OBJECT (main), "label74", label74,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label74);
  gtk_table_attach (GTK_TABLE (table1), label74, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label74), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label74), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label74), 2, 0);

  label75 = gtk_label_new (_("Mobile"));
  gtk_widget_set_name (label75, "label75");
  gtk_widget_ref (label75);
  gtk_object_set_data_full (GTK_OBJECT (main), "label75", label75,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label75);
  gtk_table_attach (GTK_TABLE (table1), label75, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label75), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label75), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label75), 2, 0);

  label76 = gtk_label_new (_("FAX"));
  gtk_widget_set_name (label76, "label76");
  gtk_widget_ref (label76);
  gtk_object_set_data_full (GTK_OBJECT (main), "label76", label76,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label76);
  gtk_table_attach (GTK_TABLE (table1), label76, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label76), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label76), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label76), 2, 0);

  lPhone = gtk_label_new (_("label77"));
  gtk_widget_set_name (lPhone, "lPhone");
  gtk_widget_ref (lPhone);
  gtk_object_set_data_full (GTK_OBJECT (main), "lPhone", lPhone,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lPhone);
  gtk_table_attach (GTK_TABLE (table1), lPhone, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lPhone), 0, 0.5);

  lMail = gtk_label_new (_("label78"));
  gtk_widget_set_name (lMail, "lMail");
  gtk_widget_ref (lMail);
  gtk_object_set_data_full (GTK_OBJECT (main), "lMail", lMail,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lMail);
  gtk_table_attach (GTK_TABLE (table1), lMail, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lMail), 0, 0.5);

  lMobile = gtk_label_new (_("label79"));
  gtk_widget_set_name (lMobile, "lMobile");
  gtk_widget_ref (lMobile);
  gtk_object_set_data_full (GTK_OBJECT (main), "lMobile", lMobile,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lMobile);
  gtk_table_attach (GTK_TABLE (table1), lMobile, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lMobile), 0, 0.5);

  lFAX = gtk_label_new (_("label80"));
  gtk_widget_set_name (lFAX, "lFAX");
  gtk_widget_ref (lFAX);
  gtk_object_set_data_full (GTK_OBJECT (main), "lFAX", lFAX,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (lFAX);
  gtk_table_attach (GTK_TABLE (table1), lFAX, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lFAX), 0, 0.5);

  gtk_signal_connect (GTK_OBJECT (nbList), "switch_page",
                      GTK_SIGNAL_FUNC (on_nbList_switch_page),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist2), "select_row",
                      GTK_SIGNAL_FUNC (selection_made),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist3), "select_row",
                      GTK_SIGNAL_FUNC (selection_made),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist4), "select_row",
                      GTK_SIGNAL_FUNC (selection_made),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist5), "select_row",
                      GTK_SIGNAL_FUNC (selection_made),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist6), "select_row",
                      GTK_SIGNAL_FUNC (selection_made),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist7), "select_row",
                      GTK_SIGNAL_FUNC (selection_made),
                      NULL);

  return main;
}

GtkWidget*
create_detailview (void)
{
  GtkWidget *detailview;
  GtkWidget *vbox2;
  GtkWidget *hbuttonbox2;
  GtkWidget *editone;
  GtkWidget *deleteone;
  GtkWidget *notebook1;
  GtkWidget *vbox4;
  GtkWidget *hbox2;
  GtkWidget *vbox5;
  GtkWidget *det_name;
  GtkWidget *det_desc;
  GtkWidget *det_add;
  GtkWidget *vbox6;
  GtkWidget *det1f;
  GtkWidget *det1;
  GtkWidget *det2f;
  GtkWidget *det2;
  GtkWidget *det3f;
  GtkWidget *det3;
  GtkWidget *det4f;
  GtkWidget *det4;
  GtkWidget *label6;
  GtkWidget *label38;
  GtkWidget *label7;
  GtkWidget *det_notesscroll;
  GtkWidget *det_notes;
  GtkWidget *label8;

  detailview = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (detailview, "detailview");
  gtk_object_set_data (GTK_OBJECT (detailview), "detailview", detailview);
  gtk_widget_set_usize (detailview, 240, 320);
  gtk_window_set_title (GTK_WINDOW (detailview), _("Contact Details"));
  gtk_window_set_default_size (GTK_WINDOW (detailview), 240, 320);
  gtk_window_set_policy (GTK_WINDOW (detailview), FALSE, FALSE, FALSE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (detailview), vbox2);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox2, "hbuttonbox2");
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, FALSE, FALSE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 10);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox2), 50, 20);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox2), 3, 0);

  editone = gtk_button_new_with_label (_("Edit"));
  gtk_widget_set_name (editone, "editone");
  gtk_widget_ref (editone);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "editone", editone,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (editone);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), editone);
  GTK_WIDGET_SET_FLAGS (editone, GTK_CAN_DEFAULT);

  deleteone = gtk_button_new_with_label (_("Delete"));
  gtk_widget_set_name (deleteone, "deleteone");
  gtk_widget_ref (deleteone);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "deleteone", deleteone,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (deleteone);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), deleteone);
  GTK_WIDGET_SET_FLAGS (deleteone, GTK_CAN_DEFAULT);

  notebook1 = gtk_notebook_new ();
  gtk_widget_set_name (notebook1, "notebook1");
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox2), notebook1, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox4);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, FALSE, FALSE, 0);

  vbox5 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox2), vbox5, TRUE, TRUE, 0);

  det_name = gtk_label_new (_("Markus Musterman"));
  gtk_widget_set_name (det_name, "det_name");
  gtk_widget_ref (det_name);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det_name", det_name,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det_name);
  gtk_box_pack_start (GTK_BOX (vbox5), det_name, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (det_name), 0, 3);

  det_desc = gtk_label_new (_("Summary Description"));
  gtk_widget_set_name (det_desc, "det_desc");
  gtk_widget_ref (det_desc);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det_desc", det_desc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det_desc);
  gtk_box_pack_start (GTK_BOX (vbox5), det_desc, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (det_desc), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (det_desc), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (det_desc), 10, 0);

  det_add = gtk_label_new (_("Somestreet No. 10\n12345 Some City\nUnknownCountry"));
  gtk_widget_set_name (det_add, "det_add");
  gtk_widget_ref (det_add);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det_add", det_add,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det_add);
  gtk_box_pack_start (GTK_BOX (vbox5), det_add, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (det_add), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (det_add), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (det_add), 10, 0);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), vbox6, TRUE, TRUE, 0);

  det1f = gtk_frame_new (_("Telephone"));
  gtk_widget_set_name (det1f, "det1f");
  gtk_widget_ref (det1f);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det1f", det1f,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det1f);
  gtk_box_pack_start (GTK_BOX (vbox6), det1f, TRUE, TRUE, 0);

  det1 = gtk_label_new (_("(555) 213 456 78"));
  gtk_widget_set_name (det1, "det1");
  gtk_widget_ref (det1);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det1", det1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det1);
  gtk_container_add (GTK_CONTAINER (det1f), det1);
  gtk_label_set_justify (GTK_LABEL (det1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (det1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (det1), 10, 0);

  det2f = gtk_frame_new (_("Mobile"));
  gtk_widget_set_name (det2f, "det2f");
  gtk_widget_ref (det2f);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det2f", det2f,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det2f);
  gtk_box_pack_start (GTK_BOX (vbox6), det2f, TRUE, TRUE, 0);

  det2 = gtk_label_new (_("(555) 213 456 78"));
  gtk_widget_set_name (det2, "det2");
  gtk_widget_ref (det2);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det2", det2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det2);
  gtk_container_add (GTK_CONTAINER (det2f), det2);
  gtk_label_set_justify (GTK_LABEL (det2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (det2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (det2), 10, 0);

  det3f = gtk_frame_new (_("E-Mail"));
  gtk_widget_set_name (det3f, "det3f");
  gtk_widget_ref (det3f);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det3f", det3f,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det3f);
  gtk_box_pack_start (GTK_BOX (vbox6), det3f, TRUE, TRUE, 0);

  det3 = gtk_label_new (_("dummy@aol.com"));
  gtk_widget_set_name (det3, "det3");
  gtk_widget_ref (det3);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det3", det3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det3);
  gtk_container_add (GTK_CONTAINER (det3f), det3);
  gtk_label_set_justify (GTK_LABEL (det3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (det3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (det3), 10, 0);

  det4f = gtk_frame_new (_("Birthday"));
  gtk_widget_set_name (det4f, "det4f");
  gtk_widget_ref (det4f);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det4f", det4f,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det4f);
  gtk_box_pack_start (GTK_BOX (vbox6), det4f, TRUE, TRUE, 0);

  det4 = gtk_label_new (_("31. 2. 1968"));
  gtk_widget_set_name (det4, "det4");
  gtk_widget_ref (det4);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det4", det4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det4);
  gtk_container_add (GTK_CONTAINER (det4f), det4);
  gtk_label_set_justify (GTK_LABEL (det4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (det4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (det4), 10, 0);

  label6 = gtk_label_new (_("Main Data"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label6);

  label38 = gtk_label_new (_("label38"));
  gtk_widget_set_name (label38, "label38");
  gtk_widget_ref (label38);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "label38", label38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label38);
  gtk_container_add (GTK_CONTAINER (notebook1), label38);

  label7 = gtk_label_new (_("Other Data"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label7);

  det_notesscroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (det_notesscroll, "det_notesscroll");
  gtk_widget_ref (det_notesscroll);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det_notesscroll", det_notesscroll,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det_notesscroll);
  gtk_container_add (GTK_CONTAINER (notebook1), det_notesscroll);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (det_notesscroll), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  det_notes = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (det_notes, "det_notes");
  gtk_widget_ref (det_notes);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "det_notes", det_notes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (det_notes);
  gtk_container_add (GTK_CONTAINER (det_notesscroll), det_notes);
  gtk_text_insert (GTK_TEXT (det_notes), NULL, NULL, NULL,
                   _("\n\n\nThere's some space here for arbitrary notes\nabout a contact.\n\n"), strlen(_("\n\n\nThere's some space here for arbitrary notes\nabout a contact.\n\n")));

  label8 = gtk_label_new (_("Notes"));
  gtk_widget_set_name (label8, "label8");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (detailview), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label8);

  return detailview;
}

