/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main (void);
GtkWidget* create_detailview (void);
GtkWidget* create_edit (void);
GtkWidget* create_structure (void);
GtkWidget* create_structure_item (void);
