/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_wSetup (void)
{
  GtkWidget *wSetup;
  GtkWidget *vbox9;
  GtkWidget *frame2;
  GtkWidget *vbox10;
  GtkWidget *hbox4;
  GtkWidget *cbField;
  GtkWidget *combo_entry1;
  GtkWidget *entry2;
  GtkWidget *bDetAdd;
  GtkWidget *bDetRemove;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist8;
  GtkWidget *label86;
  GtkWidget *label87;
  GtkWidget *frame3;

  wSetup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (wSetup, "wSetup");
  gtk_object_set_data (GTK_OBJECT (wSetup), "wSetup", wSetup);
  gtk_widget_set_usize (wSetup, 240, 320);
  gtk_window_set_title (GTK_WINDOW (wSetup), _("Setup"));
  gtk_window_set_modal (GTK_WINDOW (wSetup), TRUE);
  gtk_window_set_policy (GTK_WINDOW (wSetup), FALSE, FALSE, FALSE);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox9, "vbox9");
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (wSetup), vbox9);

  frame2 = gtk_frame_new (_("Detail panel"));
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox9), frame2, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame2), GTK_SHADOW_NONE);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox10, "vbox10");
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (frame2), vbox10);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox4, FALSE, TRUE, 0);

  cbField = gtk_combo_new ();
  gtk_widget_set_name (cbField, "cbField");
  gtk_widget_ref (cbField);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "cbField", cbField,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (cbField);
  gtk_box_pack_start (GTK_BOX (hbox4), cbField, TRUE, TRUE, 0);

  combo_entry1 = GTK_COMBO (cbField)->entry;
  gtk_widget_set_name (combo_entry1, "combo_entry1");
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_entry_set_text (GTK_ENTRY (combo_entry1), _("NAME"));

  entry2 = gtk_entry_new ();
  gtk_widget_set_name (entry2, "entry2");
  gtk_widget_ref (entry2);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "entry2", entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry2);
  gtk_box_pack_start (GTK_BOX (hbox4), entry2, TRUE, TRUE, 0);

  bDetAdd = gtk_button_new_with_label (_("Add"));
  gtk_widget_set_name (bDetAdd, "bDetAdd");
  gtk_widget_ref (bDetAdd);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "bDetAdd", bDetAdd,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bDetAdd);
  gtk_box_pack_start (GTK_BOX (hbox4), bDetAdd, FALSE, FALSE, 0);

  bDetRemove = gtk_button_new_with_label (_("Remove"));
  gtk_widget_set_name (bDetRemove, "bDetRemove");
  gtk_widget_ref (bDetRemove);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "bDetRemove", bDetRemove,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bDetRemove);
  gtk_box_pack_start (GTK_BOX (hbox4), bDetRemove, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox10), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist8 = gtk_clist_new (2);
  gtk_widget_set_name (clist8, "clist8");
  gtk_widget_ref (clist8);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "clist8", clist8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist8);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist8);
  gtk_clist_set_column_width (GTK_CLIST (clist8), 0, 126);
  gtk_clist_set_column_width (GTK_CLIST (clist8), 1, 80);
  gtk_clist_column_titles_show (GTK_CLIST (clist8));

  label86 = gtk_label_new (_("Data Field"));
  gtk_widget_set_name (label86, "label86");
  gtk_widget_ref (label86);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "label86", label86,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label86);
  gtk_clist_set_column_widget (GTK_CLIST (clist8), 0, label86);

  label87 = gtk_label_new (_("Label"));
  gtk_widget_set_name (label87, "label87");
  gtk_widget_ref (label87);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "label87", label87,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label87);
  gtk_clist_set_column_widget (GTK_CLIST (clist8), 1, label87);

  frame3 = gtk_frame_new (_("Pages"));
  gtk_widget_set_name (frame3, "frame3");
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (wSetup), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (vbox9), frame3, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame3), GTK_SHADOW_NONE);

  gtk_signal_connect (GTK_OBJECT (bDetAdd), "clicked",
                      GTK_SIGNAL_FUNC (on_bDetAdd_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (bDetRemove), "clicked",
                      GTK_SIGNAL_FUNC (on_bDetRemove_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist8), "select_row",
                      GTK_SIGNAL_FUNC (on_clist8_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist8), "unselect_row",
                      GTK_SIGNAL_FUNC (on_clist8_unselect_row),
                      NULL);

  return wSetup;
}

