#!/bin/sh

module_id() {
    ## used to read from assets, but sometimes assets is corrupted
    # grep "Module ID" /proc/hal/assets | sed "s/.*://"
    echo ' iPAQ' `cat /proc/hal/model`
}

case $1 in
'start')
	case `module_id` in
		" iPAQ 3100" )	    ARGS="--mono" ;;
		" iPAQ 3600" )	    ;;
		" iPAQ 3700" )	    ;;
		" iPAQ 3800" )	    ARGS="--flip" ;;
		" iPAQ 3600" )	    ;;
	esac
	/usr/bin/gpe-bootsplash $ARGS
	;;
'stop')
;;
*)
esac
