#!/bin/sh

if [ ! -f $HOME/.mbdock ]; then
gpe-question --question "Add default applications to dock?" --buttons !gtk-no !gtk-yes || (
 mbmenu &
 monolaunch -k /usr/share/pixmaps/xkbd.xpm xkbd &
 xstroke &
 minibat &
 minivol &
 minilite &
 minitheme &
 gpe-what &
 minitime &
)
fi
