#!/bin/sh

# No action if .mbdock exists
if [ ! -f $HOME/.mbdock ]; then
(
  sleep 1
  mbmenu &
  sleep 2
  monolaunch -k /usr/share/pixmaps/xkbd.xpm xkbd &
  xstroke &
  minibat &
  minivol &
  minilite &
  gpe-what &
  minitime -g -5 &

  gpe-question --icon !gtk-dialog-info --question "<b>Welcome to GPE!</b>

I have added some standard programs to the panel at the 
bottom of the screen.

To remove these, or add more, 
tap and hold on an empty area of 
the panel." --buttons !gtk-ok

) &
fi
