.\" gnome-todo.1 - to-do list for GPE
.\" Copyright 2003  Moray Allan
.TH gpe-todo 1 "Aug 29 2003" "version 0.36.1"
.SH NAME
gpe-todo \- to-do list for GPE
.SH SYNOPSIS
.B gpe-todo
.SH DESCRIPTION
.B gpe-todo
is a simple "to do" list manager for the GPE Palmtop Environment. It helps
you organise a list of tasks which you need to carry out. Tasks can be marked
as belonging to categories of your choosing.

.SH AUTHOR
.B gpe-todo
was written by Philip Blundell <philb@gnu.org>.

