.\" gpe-taskmanager.1 - lists windows and kills errant programs
.\" Copyright 2003  Moray Allan
.TH gpe-taskmanager 1 "Jun 28 2003" "version 0.13"
.SH NAME
gpe-taskmanager \- lists windows and kills errant programs
.SH SYNOPSIS
.B gpe-taskmanager
.SH DESCRIPTION
.B gpe-taskmanager
is part of the GPE Palmtop Environment. It displays a list of windows on the 
current display, and allows the user to kill the task which owns a particular
window. This can be helpful if a program has hung and is no longer responding
to direct user actions.

.SH AUTHOR
.B gpe-taskmanager
was written by Philip Blundell <philb@gnu.org>.

