/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *notebook1;
  GtkWidget *fixed7;
  GtkWidget *label26;
  GtkWidget *entry15;
  GtkWidget *button1;
  GtkWidget *label25;
  GtkWidget *fixed2;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label5;
  GtkWidget *radiobutton5;
  GSList *radiobutton5_group = NULL;
  GtkWidget *radiobutton4;
  GtkWidget *label1;
  GtkWidget *fixed3;
  GtkWidget *entry6;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *radiobutton9;
  GSList *radiobutton9_group = NULL;
  GtkWidget *radiobutton6;
  GtkWidget *radiobutton7;
  GtkWidget *radiobutton8;
  GtkWidget *label2;
  GtkWidget *fixed4;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *label3;
  GtkWidget *fixed5;
  GtkWidget *entry11;
  GtkWidget *radiobutton11;
  GSList *radiobutton11_group = NULL;
  GtkWidget *label21;
  GtkWidget *radiobutton10;
  GtkWidget *label12;
  GtkWidget *fixed6;
  GtkWidget *entry12;
  GtkWidget *entry13;
  GtkWidget *entry14;
  GtkWidget *label22;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *radiobutton14;
  GSList *radiobutton14_group = NULL;
  GtkWidget *radiobutton12;
  GtkWidget *radiobutton13;
  GtkWidget *label13;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window1, 240, 288);
  gtk_window_set_title (GTK_WINDOW (window1), _("WiFi Configuration"));
  gtk_window_set_resizable (GTK_WINDOW (window1), FALSE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window1), notebook1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  label26 = gtk_label_new (_("Profile Name"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed7), label26, 64, 16);
  gtk_widget_set_size_request (label26, 104, 17);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed7), entry15, 40, 32);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_editable_set_editable (GTK_EDITABLE (entry15), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entry15), _("None"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  button1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed7), button1, 80, 96);
  gtk_widget_set_size_request (button1, 66, 29);

  label25 = gtk_label_new (_("Profile"));
  gtk_widget_show (label25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label25);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2, 104, 112);
  gtk_widget_set_size_request (entry2, 128, 27);
  gtk_entry_set_text (GTK_ENTRY (entry2), _("192.168.100.255"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3, 104, 72);
  gtk_widget_set_size_request (entry3, 128, 27);
  gtk_entry_set_text (GTK_ENTRY (entry3), _("192.168.100.255"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4, 104, 152);
  gtk_widget_set_size_request (entry4, 128, 27);
  gtk_entry_set_text (GTK_ENTRY (entry4), _("192.168.100.255"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5, 104, 192);
  gtk_widget_set_size_request (entry5, 128, 27);
  gtk_entry_set_text (GTK_ENTRY (entry5), _("192.168.100.255"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label6 = gtk_label_new (_("Netmask:"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 31, 113);
  gtk_widget_set_size_request (label6, 72, 24);

  label7 = gtk_label_new (_("Gateway:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 32, 153);
  gtk_widget_set_size_request (label7, 72, 26);

  label8 = gtk_label_new (_("DNS Server:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 16, 193);
  gtk_widget_set_size_request (label8, 88, 24);

  label5 = gtk_label_new (_("IP Address:"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 19, 73);
  gtk_widget_set_size_request (label5, 88, 24);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("DHCP"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton5, 120, 24);
  gtk_widget_set_size_request (radiobutton5, 72, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton5), TRUE);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Static"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton4, 32, 24);
  gtk_widget_set_size_request (radiobutton4, 72, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton5_group);
  radiobutton5_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  label1 = gtk_label_new (_("Network"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6, 72, 24);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entry6), _("AMLBURNIN"));
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  label9 = gtk_label_new (_("ESSID:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 9, 26);
  gtk_widget_set_size_request (label9, 64, 24);

  label10 = gtk_label_new (_("Security\n   Type"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 24, 104);
  gtk_widget_set_size_request (label10, 56, 48);

  radiobutton9 = gtk_radio_button_new_with_mnemonic (NULL, _("WPA-EAP"));
  gtk_widget_show (radiobutton9);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton9, 112, 152);
  gtk_widget_set_size_request (radiobutton9, 110, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton9), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton9));

  radiobutton6 = gtk_radio_button_new_with_mnemonic (NULL, _("None"));
  gtk_widget_show (radiobutton6);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton6, 112, 80);
  gtk_widget_set_size_request (radiobutton6, 110, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton6), TRUE);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("WEP"));
  gtk_widget_show (radiobutton7);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton7, 112, 104);
  gtk_widget_set_size_request (radiobutton7, 110, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("WPA-PSK"));
  gtk_widget_show (radiobutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton8, 112, 128);
  gtk_widget_set_size_request (radiobutton8, 110, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton9_group);
  radiobutton9_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  label2 = gtk_label_new (_("Radio"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label2);
  gtk_misc_set_alignment (GTK_MISC (label2), 0.5, 0.49);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  spinbutton1_adj = gtk_adjustment_new (0, 0, 4, 1, 1, 1);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 120, 8);
  gtk_widget_set_size_request (spinbutton1, 56, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton1), TRUE);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 4, 56);
  gtk_widget_set_size_request (entry7, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 4, 104);
  gtk_widget_set_size_request (entry8, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9, 4, 156);
  gtk_widget_set_size_request (entry9, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed4), entry10, 4, 206);
  gtk_widget_set_size_request (entry10, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label16 = gtk_label_new (_("Use Key #"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 24, 9);
  gtk_widget_set_size_request (label16, 96, 24);

  label17 = gtk_label_new (_("Key 0"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 0, 40);
  gtk_widget_set_size_request (label17, 48, 16);

  label18 = gtk_label_new (_("Key 1"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 0, 90);
  gtk_widget_set_size_request (label18, 48, 16);

  label20 = gtk_label_new (_("Key 3"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 0, 190);
  gtk_widget_set_size_request (label20, 48, 16);

  label19 = gtk_label_new (_("Key 2"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 0, 140);
  gtk_widget_set_size_request (label19, 48, 16);

  label3 = gtk_label_new (_("WEP"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label3);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed5), entry11, 4, 120);
  gtk_widget_set_size_request (entry11, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  radiobutton11 = gtk_radio_button_new_with_mnemonic (NULL, _("AES-CCMP"));
  gtk_widget_show (radiobutton11);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton11, 48, 56);
  gtk_widget_set_size_request (radiobutton11, 118, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton11), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton11));

  label21 = gtk_label_new (_("Phrase:"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 0, 104);
  gtk_widget_set_size_request (label21, 64, 16);

  radiobutton10 = gtk_radio_button_new_with_mnemonic (NULL, _("TKIP"));
  gtk_widget_show (radiobutton10);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton10, 48, 24);
  gtk_widget_set_size_request (radiobutton10, 118, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton10), radiobutton11_group);
  radiobutton11_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton10));

  label12 = gtk_label_new (_("WPA-PSK"));
  gtk_widget_show (label12);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label12);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed6), entry12, 4, 104);
  gtk_widget_set_size_request (entry12, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed6), entry13, 4, 160);
  gtk_widget_set_size_request (entry13, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed6), entry14, 4, 216);
  gtk_widget_set_size_request (entry14, 230, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  label22 = gtk_label_new (_("Username:"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 0, 88);
  gtk_widget_set_size_request (label22, 87, 16);
  gtk_misc_set_alignment (GTK_MISC (label22), 0.5, 0.48);

  label24 = gtk_label_new (_("Password:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 0, 144);
  gtk_widget_set_size_request (label24, 77, 16);

  label23 = gtk_label_new (_("Phrase:"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 0, 200);
  gtk_widget_set_size_request (label23, 62, 16);

  radiobutton14 = gtk_radio_button_new_with_mnemonic (NULL, _("TTLS"));
  gtk_widget_show (radiobutton14);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton14, 56, 56);
  gtk_widget_set_size_request (radiobutton14, 118, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton14), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton14));

  radiobutton12 = gtk_radio_button_new_with_mnemonic (NULL, _("PEAP"));
  gtk_widget_show (radiobutton12);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton12, 56, 8);
  gtk_widget_set_size_request (radiobutton12, 118, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton12), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton12));

  radiobutton13 = gtk_radio_button_new_with_mnemonic (NULL, _("TLS"));
  gtk_widget_show (radiobutton13);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton13, 56, 32);
  gtk_widget_set_size_request (radiobutton13, 118, 22);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton13), radiobutton14_group);
  radiobutton14_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton13));

  label13 = gtk_label_new (_("WPA-EAP"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 5), label13);

  g_signal_connect_swapped ((gpointer) window1, "show",
                            G_CALLBACK (on_window1_show),
                            GTK_OBJECT (window1));
  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect_swapped ((gpointer) button1, "button_release_event",
                            G_CALLBACK (on_button1_button_release_event),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton5, "toggled",
                            G_CALLBACK (on_radiobutton5_toggled),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton4, "toggled",
                            G_CALLBACK (on_radiobutton5_toggled),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton9, "button_press_event",
                            G_CALLBACK (on_radiobutton9_button_press_event),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton6, "button_press_event",
                            G_CALLBACK (on_radiobutton6_button_press_event),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton7, "button_press_event",
                            G_CALLBACK (on_radiobutton7_button_press_event),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton8, "button_press_event",
                            G_CALLBACK (on_radiobutton8_button_press_event),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton14, "toggled",
                            G_CALLBACK (on_radiobutton12_toggled),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton12, "toggled",
                            G_CALLBACK (on_radiobutton12_toggled),
                            GTK_OBJECT (window1));
  g_signal_connect_swapped ((gpointer) radiobutton13, "toggled",
                            G_CALLBACK (on_radiobutton12_toggled),
                            GTK_OBJECT (window1));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window1, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window1, label26, "label26");
  GLADE_HOOKUP_OBJECT (window1, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, label25, "label25");
  GLADE_HOOKUP_OBJECT (window1, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window1, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window1, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, label8, "label8");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (window1, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window1, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");
  GLADE_HOOKUP_OBJECT (window1, label10, "label10");
  GLADE_HOOKUP_OBJECT (window1, radiobutton9, "radiobutton9");
  GLADE_HOOKUP_OBJECT (window1, radiobutton6, "radiobutton6");
  GLADE_HOOKUP_OBJECT (window1, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (window1, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window1, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window1, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window1, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window1, label16, "label16");
  GLADE_HOOKUP_OBJECT (window1, label17, "label17");
  GLADE_HOOKUP_OBJECT (window1, label18, "label18");
  GLADE_HOOKUP_OBJECT (window1, label20, "label20");
  GLADE_HOOKUP_OBJECT (window1, label19, "label19");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window1, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window1, radiobutton11, "radiobutton11");
  GLADE_HOOKUP_OBJECT (window1, label21, "label21");
  GLADE_HOOKUP_OBJECT (window1, radiobutton10, "radiobutton10");
  GLADE_HOOKUP_OBJECT (window1, label12, "label12");
  GLADE_HOOKUP_OBJECT (window1, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window1, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window1, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (window1, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (window1, label22, "label22");
  GLADE_HOOKUP_OBJECT (window1, label24, "label24");
  GLADE_HOOKUP_OBJECT (window1, label23, "label23");
  GLADE_HOOKUP_OBJECT (window1, radiobutton14, "radiobutton14");
  GLADE_HOOKUP_OBJECT (window1, radiobutton12, "radiobutton12");
  GLADE_HOOKUP_OBJECT (window1, radiobutton13, "radiobutton13");
  GLADE_HOOKUP_OBJECT (window1, label13, "label13");

  return window1;
}

