/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *brightness_hscale;
  GtkWidget *combo1;
  GList *combo1_items = NULL;
  GtkWidget *rotation_entry;
  GtkWidget *calibrate_button;
  GtkWidget *alignment1;
  GtkWidget *closebutton;

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (mainwindow), "mainwindow", mainwindow);
  gtk_window_set_title (GTK_WINDOW (mainwindow), _("Screen Settings"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 8);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox1), table1, TRUE, TRUE, 11);

  label1 = gtk_label_new (_("Brightness"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (label1), 4, 0);

  label2 = gtk_label_new (_("Rotation"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label2), 4, 0);

  brightness_hscale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (100, 0, 100, 2, 5, 0)));
  gtk_widget_ref (brightness_hscale);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "brightness_hscale", brightness_hscale,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (brightness_hscale);
  gtk_table_attach (GTK_TABLE (table1), brightness_hscale, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 4);
  gtk_scale_set_value_pos (GTK_SCALE (brightness_hscale), GTK_POS_RIGHT);
  gtk_scale_set_digits (GTK_SCALE (brightness_hscale), 0);

  combo1 = gtk_combo_new ();
  gtk_widget_ref (combo1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "combo1", combo1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo1);
  gtk_table_attach (GTK_TABLE (table1), combo1, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 4);
  gtk_combo_set_value_in_list (GTK_COMBO (combo1), TRUE, FALSE);
  combo1_items = g_list_append (combo1_items, (gpointer) _("Portrait"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Landscape (left)"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Inverted"));
  combo1_items = g_list_append (combo1_items, (gpointer) _("Landscape (right)"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1), combo1_items);
  g_list_free (combo1_items);

  rotation_entry = GTK_COMBO (combo1)->entry;
  gtk_widget_ref (rotation_entry);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "rotation_entry", rotation_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rotation_entry);
  gtk_entry_set_editable (GTK_ENTRY (rotation_entry), FALSE);
  gtk_entry_set_text (GTK_ENTRY (rotation_entry), _("Portrait"));

  calibrate_button = gtk_button_new_with_label (_("\nCalibrate touchscreen\n"));
  gtk_widget_ref (calibrate_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "calibrate_button", calibrate_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (calibrate_button);
  gtk_box_pack_start (GTK_BOX (vbox1), calibrate_button, FALSE, FALSE, 4);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0.21, 0.160001);
  gtk_widget_ref (alignment1);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "alignment1", alignment1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (vbox1), alignment1, TRUE, TRUE, 0);

  closebutton = gtk_button_new_with_label (_("Close"));
  gtk_widget_ref (closebutton);
  gtk_object_set_data_full (GTK_OBJECT (mainwindow), "closebutton", closebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (closebutton);
  gtk_container_add (GTK_CONTAINER (alignment1), closebutton);
  gtk_container_set_border_width (GTK_CONTAINER (closebutton), 3);

  gtk_signal_connect (GTK_OBJECT (mainwindow), "destroy",
                      GTK_SIGNAL_FUNC (on_mainwindow_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (brightness_hscale), "draw",
                      GTK_SIGNAL_FUNC (on_brightness_hscale_draw),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rotation_entry), "changed",
                      GTK_SIGNAL_FUNC (on_rotation_entry_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (calibrate_button), "clicked",
                      GTK_SIGNAL_FUNC (on_calibrate_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (closebutton), "clicked",
                      GTK_SIGNAL_FUNC (on_closebutton_clicked),
                      NULL);

  return mainwindow;
}

