#!/bin/sh

MACHINE=`awk 'BEGIN { FS=": " } /Hardware/ { print $2 } ' </proc/cpuinfo`

# since kdrive 1.4 there is no default keymap in server
xmodmap - </etc/X11/default.xmodmap

case $MACHINE in
	"SHARP Shepherd" | "SHARP Husky" | "SHARP Corgi")
		xmodmap - < /etc/X11/shepherd.xmodmap
		;;
	"SHARP Akita" | "SHARP Borzoi" | "SHARP Spitz")
		xmodmap - < /etc/X11/slcXXXX.xmodmap
		;;				
	"SHARP Poodle")
		xmodmap - < /etc/X11/poodle.xmodmap
		;;
        "Sharp-Collie")
                xmodmap - < /etc/X11/collie.xmodmap
                ;;
	"HP iPAQ h6300")
		xmodmap - < /etc/X11/h6300.xmodmap
		;;
	"TI-OSK")
		xmodmap - < /etc/X11/omap5912osk.xmodmap
		;;
	# All the rest of keyboardless PDA machines use common buttonmap
	"Simpad" | "HP iPAQ"* | "Asus MyPal"*)
		xmodmap - < /etc/X11/keyboardless.xmodmap
		;;
esac

