#!/bin/sh

MACHINE=`awk 'BEGIN { FS=": " } /Hardware/ { print $2 } ' </proc/cpuinfo`

case $MACHINE in
	"SHARP Shepherd" | "SHARP Husky" | "SHARP Corgi")
		case `uname -r` in
			2.4*)
				xmodmap - < /etc/X11/shepherd.xmodmap
				;;
			esac
		;;
	"SHARP Akita" | "SHARP Borzoi" | "SHARP Spitz")
		case `uname -r` in
			2.4*)
				xmodmap - < /etc/X11/slcXXXX.xmodmap
				;;
			esac
		;;				
        "Sharp-Collie")
                xmodmap - < /etc/X11/collie.xmodmap
                ;;
	"Simpad")
		xmodmap - < /etc/X11/simpad.xmodmap
		;;
	"HP iPAQ H2200")
		xmodmap - < /etc/X11/h2200.xmodmap
		;;
	"HP iPAQ HX4700")
		xmodmap - < /etc/X11/hx4700.xmodmap
		;;
	"HP iPAQ H1910" | "HP iPAQ H4000")
		xmodmap - < /etc/X11/h1910.xmodmap
		;;
	"Asus MyPal A716")
		xmodmap - < /etc/X11/a716.xmodmap
		;;
	"HP iPAQ H6300")
		xmodmap - < /etc/X11/h6300.xmodmap
		;;
esac

