#!/bin/sh

MACHINE=`awk 'BEGIN { FS=": " } /Hardware/ { print $2 } ' </proc/cpuinfo`

case $MACHINE in
	"SHARP Shepherd" | "SHARP Husky" | "SHARP Corgi")
		case `uname -r` in
			2.4*)
				xmodmap - < /etc/X11/shepherd.xmodmap
				;;
			esac
		;;
	"SHARP Akita" | "SHARP Borzoi" | "SHARP Spitz")
		case `uname -r` in
			2.4*)
				xmodmap - < /etc/X11/slcXXXX.xmodmap
				;;
			esac
		;;				
	"SHARP Poodle")
		xmodmap - < /etc/X11/poodle.xmodmap
		;;
        "Sharp-Collie")
                xmodmap - < /etc/X11/collie.xmodmap
                ;;
	"Simpad")
		xmodmap - < /etc/X11/simpad.xmodmap
		;;
	"HP iPAQ h6300")
		xmodmap - < /etc/X11/h6300.xmodmap
		;;
	# All the rest of keyboardless PDA machines use common buttonmap
	"HP iPAQ"* | "Asus MyPal"*)
		xmodmap - < /etc/X11/keyboardless.xmodmap
		;;
esac

