all:

install:
	install -D usbnet     /etc/init.d/usbnet
	install -D S10usbnet  /etc/suspend-scripts/S10usbnet
	install -D R90usbnet  /etc/resume-scripts/R90usbnet
	install -D interfaces /etc/network/interfaces
