.\" gpe-filemanager.1 - filemanager for GPE
.\" Copyright 2003  Moray Allan
.TH gpe-filemanager  1 "Jun 27 2003" "version 0.09"
.SH NAME
gpe-filemanager \- filemanager for GPE
.SH SYNOPSIS
.B gpe-filemanager
.SH DESCRIPTION
.B gpe-filemanager
 provides a simple graphical interface for accessing and manipulating files.
 .
 This filemanager is part of the GPE Palmtop Environment, a free
 environment intended to be used on palmtop computers.

.SH AUTHOR
.B gpe-filemanager
was written by Damien Tanner <dctanner@magenet.com>.

