/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_GPE_DB_Main (void)
{
  GtkWidget *GPE_DB_Main;
  GtkWidget *vbox1;
  GtkWidget *MainMenu;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *select_db1;
  GtkWidget *separator1;
  GtkWidget *exit1;
  GtkWidget *options1;
  GtkWidget *options1_menu;
  GtkAccelGroup *options1_menu_accels;
  GtkWidget *preferences1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about1;
  GtkWidget *PseudoMain;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *vbox2;
  GtkWidget *scrolledwindow2;
  GtkWidget *DBTableCList;
  GtkWidget *label5;
  GtkWidget *hbuttonbox1;
  GtkWidget *SelectDB;
  GtkWidget *CloseDB;
  GtkWidget *label1;

  GPE_DB_Main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (GPE_DB_Main, "GPE_DB_Main");
  gtk_object_set_data (GTK_OBJECT (GPE_DB_Main), "GPE_DB_Main", GPE_DB_Main);
  gtk_window_set_title (GTK_WINDOW (GPE_DB_Main), _("GPE DB"));
  gtk_window_set_default_size (GTK_WINDOW (GPE_DB_Main), 240, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (GPE_DB_Main), vbox1);

  MainMenu = gtk_menu_bar_new ();
  gtk_widget_set_name (MainMenu, "MainMenu");
  gtk_widget_ref (MainMenu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "MainMenu", MainMenu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MainMenu);
  gtk_box_pack_start (GTK_BOX (vbox1), MainMenu, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_set_name (file1, "file1");
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (MainMenu), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_set_name (file1_menu, "file1_menu");
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  select_db1 = gtk_menu_item_new_with_label (_("Select DB"));
  gtk_widget_set_name (select_db1, "select_db1");
  gtk_widget_ref (select_db1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "select_db1", select_db1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (select_db1);
  gtk_container_add (GTK_CONTAINER (file1_menu), select_db1);

  separator1 = gtk_menu_item_new ();
  gtk_widget_set_name (separator1, "separator1");
  gtk_widget_ref (separator1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (file1_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  exit1 = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_set_name (exit1, "exit1");
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit1);

  options1 = gtk_menu_item_new_with_label (_("Options"));
  gtk_widget_set_name (options1, "options1");
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (MainMenu), options1);

  options1_menu = gtk_menu_new ();
  gtk_widget_set_name (options1_menu, "options1_menu");
  gtk_widget_ref (options1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "options1_menu", options1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options1), options1_menu);
  options1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (options1_menu));

  preferences1 = gtk_menu_item_new_with_label (_("Preferences"));
  gtk_widget_set_name (preferences1, "preferences1");
  gtk_widget_ref (preferences1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "preferences1", preferences1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (options1_menu), preferences1);

  help1 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_set_name (help1, "help1");
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (MainMenu), help1);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help1));

  help1_menu = gtk_menu_new ();
  gtk_widget_set_name (help1_menu, "help1_menu");
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about1 = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_set_name (about1, "about1");
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  PseudoMain = gtk_notebook_new ();
  gtk_widget_set_name (PseudoMain, "PseudoMain");
  gtk_widget_ref (PseudoMain);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "PseudoMain", PseudoMain,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (PseudoMain);
  gtk_box_pack_start (GTK_BOX (vbox1), PseudoMain, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (PseudoMain, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (PseudoMain), FALSE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (PseudoMain), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (viewport1), vbox2);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  DBTableCList = gtk_clist_new (1);
  gtk_widget_set_name (DBTableCList, "DBTableCList");
  gtk_widget_ref (DBTableCList);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "DBTableCList", DBTableCList,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (DBTableCList);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), DBTableCList);
  gtk_widget_set_sensitive (DBTableCList, FALSE);
  gtk_clist_set_column_width (GTK_CLIST (DBTableCList), 0, 80);
  gtk_clist_column_titles_show (GTK_CLIST (DBTableCList));

  label5 = gtk_label_new (_("Tables"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_clist_set_column_widget (GTK_CLIST (DBTableCList), 0, label5);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_set_name (hbuttonbox1, "hbuttonbox1");
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox1, FALSE, FALSE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 20);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox1), 65, 25);

  SelectDB = gtk_button_new_with_label (_("Open DB"));
  gtk_widget_set_name (SelectDB, "SelectDB");
  gtk_widget_ref (SelectDB);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "SelectDB", SelectDB,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (SelectDB);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), SelectDB);
  GTK_WIDGET_SET_FLAGS (SelectDB, GTK_CAN_DEFAULT);

  CloseDB = gtk_button_new_with_label (_("Close DB"));
  gtk_widget_set_name (CloseDB, "CloseDB");
  gtk_widget_ref (CloseDB);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "CloseDB", CloseDB,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (CloseDB);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), CloseDB);
  gtk_widget_set_sensitive (CloseDB, FALSE);
  GTK_WIDGET_SET_FLAGS (CloseDB, GTK_CAN_DEFAULT);

  label1 = gtk_label_new (_("Tables"));
  gtk_widget_set_name (label1, "label1");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (GPE_DB_Main), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (PseudoMain), gtk_notebook_get_nth_page (GTK_NOTEBOOK (PseudoMain), 0), label1);

  gtk_signal_connect (GTK_OBJECT (GPE_DB_Main), "delete_event",
                      GTK_SIGNAL_FUNC (on_GPE_DB_Main_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_DB_Main), "destroy_event",
                      GTK_SIGNAL_FUNC (on_GPE_DB_Main_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_DB_Main), "destroy",
                      GTK_SIGNAL_FUNC (on_GPE_DB_Main_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_DB_Main), "key_press_event",
                      GTK_SIGNAL_FUNC (on_GPE_DB_Main_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPE_DB_Main), "button_press_event",
                      GTK_SIGNAL_FUNC (on_GPE_DB_Main_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MainMenu), "deactivate",
                      GTK_SIGNAL_FUNC (on_MainMenu_deactivate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (select_db1), "activate",
                      GTK_SIGNAL_FUNC (on_select_db1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (preferences1), "activate",
                      GTK_SIGNAL_FUNC (on_preferences1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DBTableCList), "select_row",
                      GTK_SIGNAL_FUNC (on_DBTableCList_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DBTableCList), "unselect_row",
                      GTK_SIGNAL_FUNC (on_DBTableCList_unselect_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (SelectDB), "clicked",
                      GTK_SIGNAL_FUNC (on_SelectDB_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (CloseDB), "clicked",
                      GTK_SIGNAL_FUNC (on_CloseDB_clicked),
                      NULL);

  return GPE_DB_Main;
}

GtkWidget*
create_DBSelection (void)
{
  GtkWidget *DBSelection;
  GtkWidget *DBSelectionOK;
  GtkWidget *DBSelectionCancel;

  DBSelection = gtk_file_selection_new (_("Select DB"));
  gtk_widget_set_name (DBSelection, "DBSelection");
  gtk_object_set_data (GTK_OBJECT (DBSelection), "DBSelection", DBSelection);
  gtk_container_set_border_width (GTK_CONTAINER (DBSelection), 2);
  gtk_window_set_modal (GTK_WINDOW (DBSelection), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (DBSelection), 240, 300);
  gtk_file_selection_hide_fileop_buttons (GTK_FILE_SELECTION (DBSelection));

  DBSelectionOK = GTK_FILE_SELECTION (DBSelection)->ok_button;
  gtk_widget_set_name (DBSelectionOK, "DBSelectionOK");
  gtk_object_set_data (GTK_OBJECT (DBSelection), "DBSelectionOK", DBSelectionOK);
  gtk_widget_show (DBSelectionOK);
  GTK_WIDGET_SET_FLAGS (DBSelectionOK, GTK_CAN_DEFAULT);

  DBSelectionCancel = GTK_FILE_SELECTION (DBSelection)->cancel_button;
  gtk_widget_set_name (DBSelectionCancel, "DBSelectionCancel");
  gtk_object_set_data (GTK_OBJECT (DBSelection), "DBSelectionCancel", DBSelectionCancel);
  gtk_widget_show (DBSelectionCancel);
  GTK_WIDGET_SET_FLAGS (DBSelectionCancel, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (DBSelection), "delete_event",
                      GTK_SIGNAL_FUNC (on_DBSelection_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DBSelection), "destroy_event",
                      GTK_SIGNAL_FUNC (on_DBSelection_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DBSelection), "destroy",
                      GTK_SIGNAL_FUNC (on_DBSelection_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DBSelectionOK), "clicked",
                      GTK_SIGNAL_FUNC (on_DBSelectionOK_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (DBSelectionCancel), "clicked",
                      GTK_SIGNAL_FUNC (on_DBSelectionCancel_clicked),
                      NULL);

  return DBSelection;
}

