
enum
{
    IRC_REPLY_FIRST		= 1,

    IRC_REPLY_CHANNEL_TOPIC	= 332,
    IRC_REPLY_CHANNEL_FOUNDER	= 333,
    IRC_REPLY_CHANNEL_FORWARD	= 379,

    IRC_REPLY_WHO		= 352,
    IRC_REPLY_NAMES_DATA	= 353,
    IRC_REPLY_NAMES_END		= 366,

    IRC_REPLY_LIST_START	= 321,
    IRC_REPLY_LIST_DATA		= 322,
    IRC_REPLY_LIST_END		= 323,

    IRC_REPLY_MOTD_START	= 375,
    IRC_REPLY_MOTD_DATA		= 372,
    IRC_REPLY_MOTD_END		= 376,

    IRC_REPLY_NICK_ALREADYINUSE	= 433,

};

