#ifndef _INTERFACE_H
#define	_INTERFACE_H

/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include "conf.h"

GtkWidget* create_GPE_Config_Sleep (ipaq_conf_t *ISconf);
GtkWidget* create_irq_win (ipaq_conf_t *ISconf);

#endif
