<?php
$addtitle="Contacting us";
$pagename="contact";
$author="Colin Marquardt";
$authoremail="gpe-web@marquardt-home.de";

include ("includes/head.php");
?>

<h2>Getting involved</h2> 
<p>
It is easy to become a GPE developer! For a list of open tasks, please
take a look at the 
<a href="http://www.handhelds.org/moin/moin.cgi/CurrentThingsToDo">CurrentThingsToDo
wiki page</a>.
</p>

<h2>Mailing List/Usenet News</h2> 
<p>
The main point of contact for the GPE project is the mailing list
<a href="mailto:gpe@handhelds.org">gpe@handhelds.org</a>.
</p>

<p>
To subscribe to the list go to
<a href="http://handhelds.org/mailman/listinfo/gpe">http://handhelds.org/mailman/listinfo/gpe</a>
and follow the instructions. 
</p>

<p>
You can read past articles in the mailing list archive at
<a href="http://handhelds.org/hypermail/gpe/current/">http://handhelds.org/hypermail/gpe/current/</a>.
</p>

<p>
The mailing list is also accessible via a bi-directional Usenet News/mailing
list gateway, provided by 
<a href="http://gmane.org/">GMANE</a>: 
<a href="news://gmane.comp.handhelds.gpe">news://gmane.comp.handhelds.gpe</a>.
<a
href="http://news.gmane.org/thread.php?group=gmane.comp.handhelds.gpe">Here</a> is a HTTP
view of the newsgroup, with a search function.
</p>


<h2>IRC</h2>
<P>
GPE developers and users can be found on the #gpe channel of irc.handhelds.org (port 6667).
</p>

<h2>GPE around the globe</h2> 
<P>
GPE team members are spread all around the globe. If you're a GPE
user/developer/hacker and are headed somewhere, check here to see if
there's anyone you can visit!
</p>

<p>
<table border="0" width="100%">
<!-- sorted from north to south -->
<tr><th width="15%">IRC nick</th><th width="20%">Real name</th><th width="65%">Location</th></tr>
<tr><td>luc</td>               <td>Luc Pionchon</td>         <td>Helsinki, Finland</td></tr>
<tr><td>elephantum</td>        <td>Andrey Tatarinov</td>     <td>Moscow, Russia</td></tr>
<tr><td>moray</td>             <td>Moray Allan</td>          <td>Edinburgh, Scotland</td></tr>
<tr><td>reenoo</td>            <td>Rene Wagner</td>          <td>Ganderkesee, Germany</td></tr>
<tr><td>paul</td>              <td>Paul Jakma</td>           <td>Leixlip, Ireland</td></tr>
<tr><td>koen</td>              <td>Koen Kooi</td>            <td>Enschede, Netherlands</td></tr>
<tr><td>pb</td>                <td>Philip Blundell</td>      <td>Cambridge, England</td></tr>
<tr><td>zoot</td>              <td>Owen Cliffe</td>          <td>Bath, England</td></tr>
<tr><td>dc</td>                <td>Damien Tanner</td>        <td>London, England</td></tr>
<tr><td>mallum</td>            <td>Matthew Allum</td>        <td>East London, England</td></tr>
<tr><td>nilsf</td>             <td>Nils Faerber</td>         <td>Netphen, Germany</td></tr>
<tr><td>florian</td>           <td>Florian Boor</td>         <td>Netphen, Germany</td></tr>
<tr><td>ole</td>               <td>Ole Reinhardt</td>        <td>Netphen, Germany</td></tr>
<tr><td>colin</td>             <td>Colin Marquardt</td>      <td>Stuttgart, Germany</td></tr>
<tr><td>pierre</td>            <td>Pierre Tardy</td>         <td>Clermont-Ferrand, France</td></tr>
<tr><td>jsmanrique</td>        <td>J. Manrique</td>          <td>Gijón, Spain</td></tr>
<tr><td>jamey</td>             <td>Jamey Hicks</td>          <td>Cambridge, MA, USA</td></tr>
<tr><td>jg</td>                <td>Jim Gettys</td>           <td>Cambridge, MA, USA</td></tr>
<tr><td>wizly</td>             <td>M&agrave;rius Mont&oacute;n</td> <td>Barcelona, Spain</td></tr>
<tr><td>bedboi</td>            <td>Luca De Cicco</td>        <td>Bari, Italy</td></tr>
<tr><td>mccarthy</td>          <td>Joseph McCarthy</td>      <td>Pittsburgh, PA, USA</td></tr>
<tr><td>ED</td>                <td>Erez Doron</td>           <td>Tel Aviv, Israel</td></tr>
<tr><td>mibus</td>             <td>Robert Mibus</td>         <td>Adelaide, Australia</td></tr>
<tr><td>spung</td>             <td>Lu&iacute;s Oliveira</td> <td>Coimbra, Portugal</td></tr>
</table>

<p>
<!-- see people.coord for information on how to generate the images: -->
<img src="images/people.png" alt="There are GPE hackers in the US, Europe, and Australia.">
<br>
<img src="images/people_eu.png" alt="(There are GPE hackers in several European countries, though the most are probably in the UK.)">
</p>

<?php include ("includes/foot.php"); ?>
