<?php
$addtitle="CVS";
$pagename="cvs";
$author="Colin Marquardt";
$authoremail="gpe-web@marquardt-home.de";

include ("includes/head.php");
?>

<H2>Accessing the GPE CVS repository</H2>
<p>
In short, if you are not (yet?) a developer, you do the following to get an initial copy of the GPE sources:
   <pre>
      $ cd gpe_cvs
      $ export CVSROOT=:pserver:anoncvs@cvs.handhelds.org:/cvs
      $ cvs login
      Logging in to :pserver:anoncvs@cvs.handhelds.org:2401/cvs
      CVS Password: anoncvs
      $ cvs checkout gpe
   </pre>
You only have to do this once. The next time you want to update
your copy of the sources, do:
   <pre>
      $ cd gpe_cvs
      $ cvs update
   </pre>

<P>
For a more detailed description about how to use handhelds.org CVS, please see
<a href="http://www.handhelds.org/handhelds-faq/development.html#USING-CVS">
here</a>.
</P>
<P>
You can examine the CVS repository directly 
<A HREF="http://cvs.handhelds.org/cgi-bin/viewcvs.cgi/gpe/">here</A>.
</P>

<H2>Building GPE CVS applications</H2>
<p>
There is no easy recipe for building GPE applications for the ARM
architecture yet. For a start, check the 
<A HREF="http://handhelds.org/z/wiki/GpeCrossCompilation">GpeCrossCompilation
wiki page</A>.
However, GPE can be built like any other application for your
desktop.

A makefile in 'gpe_cvs/base' helps you build (most of) GPE:

   <pre>
      $ make -f Makefile.gpe DESTDIR=`pwd`/tmp-install install
   </pre>

make 3.80 is required, version 3.79.1 has been seen to not work.

If this doesn't work for you: prerequisites for building GPE
applications are libgpewidget and gpe-icons. Depending on
the applications that you build, you may also need the
below packages (-dev or -devel according to your distribution):
<ul>
<li>libsqlite-dev (<a href="http://www.sqlite.org/download.html">sources</a>),
<li>dbus-1-dev, dbus-glib-1-dev
(<a href="http://freedesktop.org/Software/dbus/releases/">sources</a>),
<li>libmimedir (sources: use <a href="http://handhelds.org/~pb/libmimedir-20040225.tar.gz">
http://handhelds.org/~pb/libmimedir-20040225.tar.gz</a>,
or pull the sources from GNOME CVS),
<li>libbluetooth1-dev, libsdp2-dev (sources: bluez-libs from the
<a href="http://www.bluez.org/download.html">BlueZ</a> project),
<li>libgmp3-dev (<a href="http://www.swox.com/gmp/#DOWNLOAD">sources</a>),
<li>libsasl2-dev (<a href="http://asg.web.cmu.edu/cyrus/download/">sources</a>).
</ul>

So do the following before you attempt to compile one of the GPE
applications:

   <pre>
      $ cd gpe_cvs/base
      $ cd libgpewidget
      $ make
      $ make install
      $ cd ../gpe-icons
      $ make install
   </pre>

<?php include ("includes/foot.php"); ?>
