<?php
$addtitle="Documentation";
$pagename="documentation";

include ("includes/head.php");
?>

<h2>User Documentation</h2>

<p>
The following lists the user-oriented documentation for GPE we have so far. 

Most of the pages are stored in a Wiki - this means <i>you</i> can
edit them, add content and correct errors.  To do that, create a new
account with the "User Preferences" link on the upper right corner,
then use the "speech bubble" icon on the respective page to edit.
</p>
<p>
Some developer documentation and useful links can be found at the end of this page.
</p>
<h3>General</h3>

<ul>
<li><a href="http://www.linuxtogo.org/gowiki/GpeProject">GPE Project pages in the linuxtogo.org GoWiki</a>
<li><a href="http://gpe.linuxtogo.org/usermanual/usermanual.html">HTML User Manual (from Docbook)</a>
</ul>

<!--
<h3>PIM Applications</h3>

<ul>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeContacts">Using the Contacts manager</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeTodo">Using the TODO List</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeCalendar">Using the Calendar</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeSketchBook">Using the Sketchbook</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeTimeTracker">Using the Time Tracker</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeSummary">GPE Summary - A summary of your current events</a>
</ul>

<h3>Settings and Configuration</h3>

<ul>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeRosetta">Rosetta Handwriting Recognition</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeVirtualKeyboard">Virtual Keyboard</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeUserManager">User Manager</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeTimeDate">Date and Time</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeScreenSetup">Screen Setup</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeButtonConfig">Button Configuration</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeFirewall">Firewall</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeLogin">Login</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeSystemInfo">System Information</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeUserAccess">User Access</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeLookAndFeel">Look and Feel</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeOwnerInfo">Owner Information</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeSleepConfig">Sleep Configuration</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeThemes">How to create themes for GPE</a>
</ul>

<h3>Communication</h3>

<ul>
<li><a href="http://gpe.linuxtogo.org/documentation/wireless.shtml">Wireless LAN Configuration</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/BluetoothConfig">Bluetooth Configuration</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GPEIrDAConfig">IrDA Configuration</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeSerialPorts">Serial Ports</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GPE-EthernetOverUSB?action=show">USB Networking on Zaurus</a>
</ul>

<h3>Other</h3>

<ul>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeRecordMemo">Record a Memo</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpePlayMemo">Play a Memo</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GPESoundbiteConversionToMP3">Convert Memo audio format (Soundbite) to MP3</a>
<li><a href="http://www.handhelds.org/moin/moin.cgi/GpeMiscScreenShots">Miscellaneous Screenshots</a>
<li><a href="http://gpe.linuxtogo.org/gallery/gallery/">Some new Screenshots and backgrounds</a>
<li><a href="http://stag.mind.be/gpe-helpviewer.html">GPE-Helpviewer</a>
</ul>
-->

<p>
A part of this documentation has been converted to docbook.<br>You can find a HTML 
version of the docbook manual 
<a href="http://gpe.linuxtogo.org/usermanual/usermanual.html">here</a>.
</p>

<h2>Developer Documentation</h2>
<p>
This manual is work in progress but contains a lot of useful information already.
</p>
<p>
Static pages are here:
<ul>
<li><a href="http://gpe.linuxtogo.org/devmanual/">GPE Development Manual</a> (wip). 
<li><a href="http://www.kernelconcepts.de/~fuchs/gpe/doc/">API Documentaion (wip)</a>
<li><a href="http://gpe.linuxtogo.org.org/documentation/uml_gtk2_xcompile.shtml">User
    Mode Linux cross compiling environment with GTK2</a>
</ul>
</p>
<p>
<a href="http://www.linuxtogo.org/gowiki/GpeProject">The linuxtogo.org
GoWiki</a> contains quite some development information.
</p>
<p>
Most interesting ones are:
<ul>
<li><a href="http://www.linuxtogo.org/gowiki/GpeHelpSystem">GPE Help System</a>
<li><a href="http://www.linuxtogo.org/gowiki/GpeCrossCompilation">Crosscompilation Wiki</a>
<li><a href="http://www.linuxtogo.org/gowiki/GpeNativeDevelopment">Native Development</a>
<li><a href="http://www.linuxtogo.org/gowiki/GpeThemes">Themes</a>
</ul>
</p>
<p>
The list of current GPE maintainers may be found in the <a href="http://www.linuxtogo.org/gowiki/GpeMaintainerList"> Wiki</a>.
</p>
<?php include ("includes/foot.php"); ?>
