<?php
$addtitle="Documentation";
$pagename="documentation";
$author="Colin Marquardt";
$authoremail="gpe-web@marquardt-home.de";

include ("includes/head.php");
?>

<h2>Users</h2>

The following lists the user-oriented documentation we have so far. Some
docs are Wiki pages, you can add information you feel should be there
yourself.

<ul>
<li><a href="http://handhelds.org/z/wiki/GPENewbie">Getting started with GPE</a>
<li><a href="http://handhelds.org:8080/wiki/GpeContacts">Using GPE Contacts</a>
<li><a href="http://handhelds.org:8080/wiki/GpeTodo">Using GPE TODO</a>
<li><a href="http://handhelds.org:8080/wiki/GpeCalendar">Using GPE Calendar</a>
<li><a href="http://handhelds.org:8080/wiki/GpeSketchBook">Using GPE Sketchbook</a>
<li><a href="http://handhelds.org:8080/wiki/GpeTimeTracker">Using GPE Time Tracker</a>
</ul>

<ul>
<li><a href="http://handhelds.org:8080/wiki/GPEBluetoothConfig">Configuring Bluetooth</a>
<li><a href="http://gpe.handhelds.org/documentation/wireless.shtml">Configuring Wireless Networking</a>
</ul>

<ul>
<li><a href="http://www.handhelds.org:8080/wiki/GpeThemes">How to create themes for GPE</a>
</ul>


<h2>Developers</h2>

Developer documentation is mainly stored in the 
<a href="http://www.handhelds.org/z/wiki/GPE">GPE pages in the
handhelds.org wiki</a> for now.
<ul>
<li><a href="http://gpe.handhelds.org/projects/libgpewidget.shtml">libgpewidget documentation</a>
<li><a href="http://gpe.handhelds.org/developers/libgpewidget.shtml">libgpewidget api reference</a>
<li><a href="http://gpe.handhelds.org/documentation/uml_gtk2_xcompile.shtml">User
    Mode Linux cross compiling environment with GTK2</a>
</ul>

<?php include ("includes/foot.php"); ?>
