<?php
$addtitle="Download";
$pagename="download";

include ("includes/head.php");
?>

<h2>Binaries</h2>

<h3>Familiar Linux</h3>

<p>
GPE is available for 
  <a href="http://familiar.handhelds.org/">Familiar Linux</a> 
in several forms:
</p>
<ul>
<li>
   GPE image file: Choose the GPE option when getting an image from the 
   <a href="http://familiar.handhelds.org/releases/latest/">latest Familiar release</a>.
</li>

<li>
   Up-to-date (possibly unstable) packages for a running GPE system from the 
   <a href="http://familiar.handhelds.org/familiar/feeds/unstable/packages/armv4l/">Familiar unstable feed</a>.
   Not for the faint of the heart.
</li>

<li>
   Get single GPE packages or files inside a package via the 
   <a href="http://ipkgfind.handhelds.org/result.phtml?query=gpe*&searchtype=package&section=">List
   of GPE packages</a> in <a href="http://ipkgfind.handhelds.org/">ipkgfind</a>.
</li>
</ul>


<h3>Debian GNU/Linux</h3>

<p>
Some GPE packages are available for 
  <a href="http://www.debian.org/">Debian GNU/Linux</a> in
the Unstable and Testing feeds.
</p>


<h3>OpenZaurus/OpenEmbedded</h3>

<p>
GPE is included in <a href="http://openzaurus.org">OpenZaurus</a> distribution 3.5.2 and later and 
in the <a href="http://openembedded.org/">OpenEmbedded</a> build system. 
There is still some help needed to improve GPE adaption to several hardware platforms, 
so don't hestitate to contact us if you want to work on porting GPE to a particular
device.

</p>


<h2>Source</h2>
<p>
The latest development sources for GPE components can be found in the
<a href="/cvs.phtml">GPE CVS</a> archive. 

Tarballs are being collected at
<a href="http://gpe.linuxtogo.org/download/source/">http://gpe.linuxtogo.org/download/source/</a>.
</p>

<?php include ("includes/foot.php"); ?>
