<?php
$addtitle="Obtaining GPE";
$pagename="download";

include ("includes/head.php");
?>

<h2>Binaries</h2>

<h3>&Aring;ngstr&ouml;m Linux</h3>
<p>
The <a href="http://www.angstrom-distribution.org/">&Aring;ngstr&ouml;m distribution</a> ships GPE in the x11-images and provides up to date package feeds and images for various devices.
</p>



<h3>Debian GNU/Linux</h3>

<p>
Some GPE packages are available for 
  <a href="http://www.debian.org/">Debian GNU/Linux</a> in
the Unstable and Testing feeds. The packages in stable Debian (and Ubuntu) are really old.
</p>


<h3>OpenZaurus/OpenEmbedded</h3>

<p>
GPE is included in <a href="http://openzaurus.org">OpenZaurus</a> distribution 3.5.2 and later and 
in the <a href="http://openembedded.org/">OpenEmbedded</a> build system. 
There is still some help needed to improve GPE adaption to several hardware platforms, 
so do not hestitate to contact us if you want to work on porting GPE to a particular
device.
</p>


<h3>Familiar Linux</h3>

<p>
GPE is available for Familiar Linux as ready to run images for a few iPAQ devices.<br/>
Choose the GPE option when getting an image from the 
<a href="http://familiar.handhelds.org/releases/latest/">latest Familiar release</a>.
   Currently GPE in Familiar is quite outdated and there are no updated GPE packages any more in the unstable feed.
   In general Familiar is obsolete unless you use a very old iPAQ (h3xxx).
</p>

<h2>Source</h2>
<h3>Releases</h3>
<p>
Release tar archives are being collected at
<a href="http://gpe.linuxtogo.org/download/source/">http://gpe.linuxtogo.org/download/source/</a>.
</p>

<H3>Accessing the GPE Subversion repository</H3>
<p>
In short, if you are not (yet?) a developer, you do the following to get an initial copy of the GPE sources:
   <pre>
	svn checkout svn://projects.linuxtogo.org/svn/gpe/trunk gpe_svn
   </pre>
You only have to do this once. The next time you want to update
your copy of the sources, do:
   <pre>
      $ cd gpe_svn
      $ svn update
   </pre>

<P>
    For more details about accessing the Subversion repository 
    take a look at the <a href="http://projects.linuxtogo.org/scm/?group_id=21">
    GForge SCM page</a>.
</P> 


<P>
You can examine the SVN repository directly 
<A href="http://projects.linuxtogo.org/plugins/scmsvn/viewcvs.php/?root=gpe">here</A>.
</P>

<H3>Building GPE applications from SVN</H3>
<p>
There is no easy recipe for building GPE applications for the ARM
architecture yet. For a start, check the 
<A HREF="http://www.linuxtogo.org/gowiki/GpeCrossCompilation">GpeCrossCompilation
wiki page</A>.
However, GPE can be built like any other application for your
desktop.

A makefile in 'gpe_svn/base' helps you build (most of) GPE:

   <pre>
      $ make -f Makefile.gpe DESTDIR=`pwd`/tmp-install install
   </pre>

make 3.80 or later is required, version 3.79.1 has been seen to not work.

If this doesn't work for you: prerequisites for building GPE
applications are libgpewidget and gpe-icons. Depending on
the applications that you build, you may also need the
below packages (-dev or -devel according to your distribution):
<ul>
<li>libsqlite-dev (<a href="http://www.sqlite.org/download.html">sources</a>),
<li>dbus-1, dbus-glib-1-dev
(<a href="http://freedesktop.org/Software/dbus/releases/">sources</a>),
<li>libmimedir, libsoup (sources: use the sources from
<a href="http://developer.gnome.org/tools/cvs.html">GNOME's CVS</a>),
<li>libbluetooth, libsdp2 (sources: bluez-libs from the
<a href="http://www.bluez.org/download.html">BlueZ</a> project),
</ul>

So build <i>libgpewidget</i> before you attempt to compile one of the GPE
applications:

   <pre>
      $ cd gpe_svn/base
      $ cd libgpewidget
      $ ./autogen.sh
      $ ./configure
      $ make
      $ make install
      $ cd ../gpe-icons
      $ make install
   </pre>

<?php include ("includes/foot.php"); ?>
