<?php
$addtitle="The GPE Palmtop Environment";
$pagename="home";
$author="Colin Marquardt";
$authoremail="gpe-web@marquardt-home.de";

include ("includes/head.php");
?>

<h2>About GPE</h2>

<p>The GPE Palmtop Environment (GPE) is a collection of integrated
software components optimized for (but not limited to) handheld and
other input constrained and resource limited devices.  <a
href="projects/">GPE provides</a> PIM (<a
href="projects/GPE-calendar.shtml">calendaring</a>, <a
href="projects/GPE-todo.shtml">todo management</a>, <a
href="projects/GPE-Contacts.shtml">contact management</a> and <a
href="projects/gpe-sketchbook.shtml">note taking</a>), Multimedia (<a
href="projects/starling.shtml">audio playback</a> and <a
href="projects/gpe-gallery.shtml">image viewing</a>) and connectivity
solutions (<a href="projects/gpe-mini-browser.shtml">web
browsing</a>).  
Another major goal of GPE is to encourage people to work on free software 
for mobile devices and to experiment with new technologies.
<img src="images/gpe-in-use.jpg" alt="GPE in use" align="right"> 
</p>

<p>GPE provides an infrastructure for easy and powerful application
development by building on available technology including GTK+,
SQLite, DBUS and GStreamer and several more common standards defined 
by <a href="http://freedesktop.org">freedesktop.org</a>.</p>

<p>
GPE is committed to the <a href="http://www.opensource.org/">Open Source</a> idea. 
All GPE core components are released under <a href="http://www.gnu.org/licenses/licenses.html">GNU licenses</a>,
 applications using the <a href="http://www.gnu.org/licenses/gpl.html">GPL</a> and shared libraries using the 
<a href="http://www.gnu.org/licenses/lgpl.html">LGPL</a>. Those allow for the most free usability of the GPE system. 
</p>

<p>
If you are interested in more details or want to get in touch with the 
project you maybe want to check out these links:
</p>
<p>
<table nargin-left="20%" width="30%">
  <tr>
    <td><a href="/gallery/gallery/"><img src="images/screenshots.png"></a></td>
    <td valign="center"><font size=4><b><a href="/gallery/gallery/">Screenshot Gallery</a></b></font></td>
  </tr>
  <tr>
    <td><a href="http://projects.linuxtogo.org/projects/gpe"><img src="images/project.png"></a></td>
    <td valign="center"><b><font size=4><a href="http://projects.linuxtogo.org/projects/gpe">Project Website</a></b></font></td>
  </tr>
  <tr>
    <td><a href="http://linuxtogo.org/mailman/listinfo/gpe-list"><img src="images/mail.png"></a></td>
    <td valign="center"><b><font size=4><a href="http://linuxtogo.org/mailman/listinfo/gpe-list">Mailinglist</a></b></font></td>
  </tr>
  <tr>
    <td><a href="http://bugs.linuxtogo.org"><img src="images/bugs.png"></a></td>
    <td valign="center"><b><font size=4><a href="http://bugs.linuxtogo.org">Bugtracker</a></b></font></td>
  </tr>
</table>
</p>
<!--
<p>
If you are interested in how GPE looks like just take a look at our 
<a href="/gallery/gallery/">screenshot gallery</a>.
</p>
<p>
To find out more about GPE development or want to join the project please visit 
the <a href="http://projects.linuxtogo.org/projects/gpe/">project website</a>.
</p>
-->
<h2>News</h2>
<p>
<?php include ("rss2html.php"); ?>
</p>
<?php include ("includes/foot.php"); ?>
