<?php
$addtitle="The GPE Palmtop Environment";
$pagename="home";
$author="Colin Marquardt";
$authoremail="gpe-web@marquardt-home.de";

include ("includes/head.php");
?>

<!--

<h1 align="center"><font color="red">Protest against software patents</font></h1>
<blockquote>
<p>Due to the <a href="http://swpat.ffii.org/">directive validating
Software Patents</a> that will be voted on at the
<a href="http://www.europarl.eu.int/">European Parliament</a>,
we have decided to protest.</p>
<p>Citizens whose nations are part of the European Parliament -- please
sign the <a href="http://petition.eurolinux.org/">Petition for a Software
Patent Free Europe</a>.</p>
</blockquote>

<hr>

-->

<p>
The GPE Palmtop Environment aims to
provide a Free Software GUI environment for palmtop/handheld computers
running the GNU/Linux&#8482; operating system.  GPE uses the <A
href="http://freedesktop.org/Software/xorg">X Window System</A>, and the <A
href="http://www.gtk.org/">GTK+ widget toolkit</A>.
</p>

<p>
GPE is not a single piece of software, but an entire environment of components
which make it possible to use your GNU/Linux handheld
for standard tasks such as Personal Information Management (PIM). GPE
makes it easy for developers to create powerful programs, by giving
them the infrastructure they need.
</p>

<p>
Besides providing core software such as shared libraries, and perhaps more
importantly, the GPE environment fixes standards for program interaction,
such as SQL, XML, and other data schemas.
</p>

<p>
GPE is committed to the <a href="http://www.opensource.org/">Open Source</a>
idea. All GPE core components are released under
<a href="http://www.gnu.org/">GNU</a>
<a href="http://www.gnu.org/licenses/licenses.html">licenses</a>, applications
using the <a href="http://www.gnu.org/licenses/gpl.html">GPL</a> and shared
libraries using the <a href="http://www.gnu.org/licenses/lgpl.html">LGPL</a>.
Those allow for the most free usability of the GPE system.
</p>

<?php include ("gpe-news.php"); ?>

<?php include ("includes/foot.php"); ?>
