<?php
$addtitle="The GPE Palmtop Environment";
$pagename="home";
$author="N&oacute;ra Demeter";
$authoremail="gonoszvagyok-at-freemail.hu";

include ("includes/head.php");
?>

<h2>About GPE</h2>


<p>The GPE Palmtop Environment (GPE) is a collection of integrated
software components optimized for (but not limited to) handheld and
other input constrained and resource limited devices.  <a href="http://gpe.linuxtogo.org/projects/">GPE provides</a> PIM (<a href="http://gpe.linuxtogo.org/projects/GPE-calendar.shtml">calendaring</a>, <a href="http://gpe.linuxtogo.org/projects/GPE-todo.shtml">todo management</a>, <a href="http://gpe.linuxtogo.org/projects/GPE-Contacts.shtml">contact management</a> and <a href="http://gpe.linuxtogo.org/projects/gpe-sketchbook.shtml">note taking</a>), Multimedia (<a href="http://gpe.linuxtogo.org/projects/starling.shtml">audio playback</a> and <a href="http://gpe.linuxtogo.org/projects/gpe-gallery.shtml">image viewing</a>) and connectivity
solutions (<a href="http://gpe.linuxtogo.org/projects/gpe-mini-browser.shtml">web
browsing</a>).  
Another major goal of GPE is to encourage people to work on free software 
for mobile devices and to experiment with new technologies.

<img src="images/gpe-in-use.jpg" alt="GPE in use" align="right"> 
</p>

<p>GPE provides an infrastructure for easy and powerful application
development by building on available technology including GTK+,
SQLite, DBUS and GStreamer and several more common standards defined 
by <a href="http://freedesktop.org/">freedesktop.org</a>.</p>

<p>
GPE is committed to the <a href="http://www.opensource.org/">Open Source</a> idea. 
All GPE core components are released under <a href="http://www.gnu.org/licenses/licenses.html">GNU licenses</a>,
applications using the <a href="http://www.gnu.org/licenses/gpl.html">GPL</a> and shared libraries using the 

<a href="http://www.gnu.org/licenses/lgpl.html">LGPL</a>. Those allow for the most free usability of the GPE system. 
</p>

<p>
If you are interested in more details or want to get in touch with the 
project you maybe want to check out these links:
</p>
<table width="30%">
<tr>
<td><a href="http://gpe.linuxtogo.org/gallery/gallery/">
<img src="images/screenshot.png" alt="screenshots"></a>
</td>
<td align="center"><b><a href="http://gpe.linuxtogo.org/gallery/gallery/">Screenshot Gallery</a></b>
</td>
</tr>

<tr>
<td><a href="http://projects.linuxtogo.org/projects/gpe"><img src="images/development.png" alt="project"></a>
</td>
<td align="center"><b><a href="http://projects.linuxtogo.org/projects/gpe">Development</a></b>
</td>
</tr>
<tr>
<td><a href="http://linuxtogo.org/mailman/listinfo/gpe-list"><img src="images/Mail.png" alt="mail"></a>
</td>
<td align="center"><b><a href="http://linuxtogo.org/mailman/listinfo/gpe-list">Mailinglist</a></b>
</td>
</tr>
<tr>
<td><a href="http://bugs.linuxtogo.org/"><img src="images/Bugs.png" alt="bugs"></a>
</td>
<td align="center"><b><a href="http://bugs.linuxtogo.org/">Bugtracker</a></b>
</td>
</tr>
</table>
</div>

<br>
<br>
<h2>News</h2>
<br>  

<?php include ("rss2html.php"); ?>

<?php include ("includes/foot.php"); ?>
