<?php
$addtitle="Links/Resources";
$pagename="linkres";
$author="Nils Faerber";
$authoremail="nils@linuxtogo.org";

include ("includes/head.php");
?>

<H2>GPE Wiki</H2>

<UL>
<LI><A HREF="http://www.handhelds.org/moin/moin.cgi/GPEProject">http://www.handhelds.org/moin/moin.cgi/GPEProject</A>
</UL>

<H2>Related projects</H2>
<UL>
<LI>linuxtogo.org<BR>
<A HREF="http://www.linuxtogo.org/">http://www.linuxtogo.org</A>
<LI>The Familiar Project<BR>
<A HREF="http://familiar.handhelds.org/">http://familiar.handhelds.org</A>
<LI>The Matchbox Window Manager<BR>
<A HREF="http://projects.o-hand.com/matchbox/">http://projects.o-hand.com/matchbox/</A>
<LI>wxEmbedded - wxWidgets support for GPE<BR>
<A HREF="http://www.roebling.de/embedded.html">http://www.roebling.de/embedded.html</A>
<LI>VLC for GPE/Familiar<BR>
<A HREF="http://www.videolan.org/vlc/download-familiar.html">http://www.videolan.org/vlc/download-familiar.html</A>
</UL>

<H2>Related documentation</H2>
<UL>
<LI> GNOME Human Interface Guidelines (1.0)<BR>
<A HREF="http://developer.gnome.org/projects/gup/hig/1.0/">http://developer.gnome.org/projects/gup/hig/1.0/</A>
<LI> Apple Newton application interface guidelines<BR>
<A HREF="http://www.unna.org/unna/development/documentation/">http://www.unna.org/unna/development/documentation/</A>
<LI> Palm OS User Interface Guidelines<BR>
<A HREF="http://www.palmos.com/dev/support/docs/ui/UIGuidelinesTOC.html">http://www.palmos.com/dev/support/docs/ui/UIGuidelinesTOC.html</A>
<LI> XSETTINGS - configuration of settings for all applications running within a desktop<BR>
<A HREF="http://www.freedesktop.org/standards/xsettings.html">http://www.freedesktop.org/standards/xsettings.html</A>
<LI> D-BUS - a system for low-latency, low-overhead, easy to use interprocess communication (IPC)<BR>
<A HREF="http://www.freedesktop.org/software/dbus/">http://www.freedesktop.org/software/dbus/</A>
</UL>


<h2>Desktop interoperability</h2>
<p>
GPE programs aim to meet the relevant <a
href="http://www.freedesktop.org/standards/">freedesktop.org
standards</a>.
</p>

<p>GPE programs should comply with the 
<a href="http://developer.gnome.org/projects/gup/hig/1.0/">GNOME Human
Interface Guidelines</a> where it is appropriate. Some deviations have
to be made to deal with peculiarities of the palmtop environment, such
as small screens; some of these changes and additions to the GNOME HIG
can be found on the 
<a href="http://www.handhelds.org/moin/moin.cgi/GpeHIG">GPE HIG</a> Wiki page.
</p>

<p>OpenOffice has a project for Document Editing on Small Devices: 
<a href="http://xml.openoffice.org/xmerge/">XMerge</a>.
</p>
<p>Here is something that would allow to run <a
href="http://www.winehq.com/">wine</a> on ARM:
<a href="http://fabrice.bellard.free.fr/qemu/">QEMU x86 Emulator</a>.
</p>

<p>Icons:
  <ul>
    <li><a href="http://art.gnome.org/art-icons/index.php">http://art.gnome.org/art-icons/index.php</a>
    <li><a href="http://developer.ximian.com/themes/icons/">http://developer.ximian.com/themes/icons/</a>
    <li><a href="http://jimmac.musichall.cz/ikony.php3">http://jimmac.musichall.cz/ikony.php3</a>
    <li><a href="http://developer.ximian.com/themes/icons/ooo-icons.html">http://developer.ximian.com/themes/icons/ooo-icons.html</a>
    <li><a href="http://www.asturlinux.org/~jsmanrique/gpe/files/Pixmaps_NOIA.tar.gz">http://www.asturlinux.org/~jsmanrique/gpe/files/Pixmaps_NOIA.tar.gz</a>
      (icons can be seen on 
      <a href="http://www.asturlinux.org/~jsmanrique/gpe/">http://www.asturlinux.org/~jsmanrique/gpe/</a>)
  </ul>
</p>

<h2>SQL schemas</h2> 
<p>The core storage model for environment-wide data such as PIM data and
user preferences is that of a relational database, implemented
through the ubiquitous SQL (Structured Query Language).
</p>
<p>
We started to collect the database layouts used in GPE in the 
<a href="http://handhelds.org:8080/gpe/wiki?p=GpeDatabaseScheme">GpeDatabaseScheme</a>
development wiki. (currently disabled)
</p>

<h2>Data transfer</h2>
<p>
GPE supports the 
<a href="http://www.imc.org/pdi/">vCard and vCal</a> 
standards for transferring address book and calendar
information. We also plan to follow the 
<a href="http://www.imc.org/ietf-calendar/">IETF Calendaring and
Scheduling</a> standards. See also the OpenSync link below.
</p>

<H2>Interesting applications</H2>
<UL>
<LI> Sam J. Engstr&ouml;m has a nice collection<BR>
<A HREF="http://www.samengstrom.com/ipaq/">http://www.samengstrom.com/ipaq/</A>
<LI> SQLite is the database engine library used by some applications and usqld<BR>
<A HREF="http://www.sqlite.org/">http://www.sqlite.org/</A>
<LI> SyncML<BR>
<A HREF="http://www.syncml.org">http://www.syncml.org</A><BR>
SyncML library<BR>
<A HREF="http://libsyncml.sourceforge.net/">http://libsyncml.sourceforge.net/</A>

<LI> <A HREF="http://www.opensync.org/">OpenSync</A>
<LI> <A HREF="http://handhelds.org/~paxanima/">PaxAnimas minipredict, psCalc and psPim</A>
</UL>

<h2>New things on this website</h2>

Please see the <a href="http://gpe.linuxtogo.org/ChangeLog">ChangeLog</a>.

<?php include ("includes/foot.php"); ?>
