<?php
$addtitle="Subversion";
$pagename="svn";
$author="Colin Marquardt";
$authoremail="gpe-web@marquardt-home.de";

include ("includes/head.php");
?>

<H2>Accessing the GPE Subversion repository</H2>
<p>
In short, if you are not (yet?) a developer, you do the following to get an initial copy of the GPE sources:
   <pre>
	svn checkout svn://projects.linuxtogo.org/svn/gpe/trunk gpe_svn
   </pre>
You only have to do this once. The next time you want to update
your copy of the sources, do:
   <pre>
      $ cd gpe_svn
      $ svn update
   </pre>

<P>
    For more details about accessing the Subversion repository 
    take a look at the <a href="http://projects.linuxtogo.org/scm/?group_id=21">
    GForge SCM page.
</P> 


<P>
You can examine the SVN repository directly 
<A href="http://projects.linuxtogo.org/plugins/scmsvn/viewcvs.php/?root=gpe">here</A>.
</P>

<H2>Building GPE applications from SVN</H2>
<p>
There is no easy recipe for building GPE applications for the ARM
architecture yet. For a start, check the 
<A HREF="http://www.handhelds.org/moin/moin.cgi/GpeCrossCompilation">GpeCrossCompilation
wiki page</A>.
However, GPE can be built like any other application for your
desktop.

A makefile in 'gpe_svn/base' helps you build (most of) GPE:

   <pre>
      $ make -f Makefile.gpe DESTDIR=`pwd`/tmp-install install
   </pre>

make 3.80 is required, version 3.79.1 has been seen to not work.

If this doesn't work for you: prerequisites for building GPE
applications are libgpewidget and gpe-icons. Depending on
the applications that you build, you may also need the
below packages (-dev or -devel according to your distribution):
<ul>
<li>libsqlite-dev (<a href="http://www.sqlite.org/download.html">sources</a>),
<li>dbus-1-dev, dbus-glib-1-dev
(<a href="http://freedesktop.org/Software/dbus/releases/">sources</a>),
<li>libmimedir (sources: use the sources from
<a href="http://developer.gnome.org/tools/cvs.html">GNOME's CVS</a>),
<li>libbluetooth1-dev, libsdp2-dev (sources: bluez-libs from the
<a href="http://www.bluez.org/download.html">BlueZ</a> project),
</ul>

So build <i>libgpewidget</i> before you attempt to compile one of the GPE
applications:

   <pre>
      $ cd gpe_svn/base
      $ cd libgpewidget
      $ ./autogen.sh
      $ ./configure
      $ make
      $ make install
      $ cd ../gpe-icons
      $ make install
   </pre>

<?php include ("includes/foot.php"); ?>
