#!/bin/sh

MODEL="PNG"
test -e /etc/scap.conf && USER=`cat /etc/scap.conf`
#RES="1024x768"
(echo "POST /scap/capture.cgi?$MODEL+$USER+$RES HTTP/1.1"
 echo -n Content-length:
 cat $1 | wc -c
 echo "Content-Type: image/gif"
 echo "Host: www.handhelds.org"
 echo ""
 cat $1) | nc www.handhelds.org 80
