.\" tp-keygen.1 - create display migration authentication key
.\" Copyright 2003  Moray Allan
.TH tp\-keygen 1 "Oct 13 2003" "version 0.31.1"
.SH NAME
tp\-keygen \- create display migration authentication key 
.SH SYNOPSIS
.B tp\-keygen
.SH DESCRIPTION
.B tp\-keygen
generates a key file for teleport(1) to use for authentication when moving windows between displays.

.SH SEE ALSO

.BR teleport (1),
.BR /usr/share/doc/libdisplaymigration0-dev/spec.txt .

.SH AUTHOR
.B tp\-keygen
was written by Philip Blundell <philb@gnu.org>.

