/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_SaveChanges (void);
GtkWidget* create_GeneralHelpWin (void);
GtkWidget* create_RFParamsHelp (void);
GtkWidget* create_WEPHelpWin (void);
GtkWidget* create_EncKeysHelpWin (void);
GtkWidget* create_ExpertHelpWin (void);
GtkWidget* create_DeleteVerify (void);
GtkWidget* create_SchemeHelpWin (void);
GtkWidget* create_GPE_WLANCFG (void);
