/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_GPEBatMon (void)
{
  GtkWidget *GPEBatMon;
  GtkWidget *vbox1;
  GtkWidget *MainMenu;
  GtkWidget *file1;
  GtkWidget *file1_menu;
  GtkAccelGroup *file1_menu_accels;
  GtkWidget *exit1;
  GtkWidget *options1;
  GtkWidget *options1_menu;
  GtkAccelGroup *options1_menu_accels;
  GtkWidget *preferences1;
  GtkWidget *help1;
  GtkWidget *help1_menu;
  GtkAccelGroup *help1_menu_accels;
  GtkWidget *about1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *notebook1;
  GtkWidget *hbox1;
  GtkWidget *BatBar0;
  GtkWidget *table1;
  GtkWidget *label1;
  GtkWidget *Bat0Life;
  GtkWidget *Bat0Perc;
  GtkWidget *Bat0Volt;
  GtkWidget *Bat0Stat;
  GtkWidget *Bat0Chem;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *tab1;
  GtkWidget *hbox2;
  GtkWidget *BatBar1;
  GtkWidget *table2;
  GtkWidget *label12;
  GtkWidget *Bat1Life;
  GtkWidget *Bat1Perc;
  GtkWidget *Bat1Volt;
  GtkWidget *Bat1Stat;
  GtkWidget *Bat1Chem;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *tab2;

  GPEBatMon = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (GPEBatMon), "GPEBatMon", GPEBatMon);
  gtk_window_set_title (GTK_WINDOW (GPEBatMon), _("GPE Battery Monitor"));
  gtk_window_set_default_size (GTK_WINDOW (GPEBatMon), 240, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (GPEBatMon), vbox1);

  MainMenu = gtk_menu_bar_new ();
  gtk_widget_ref (MainMenu);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "MainMenu", MainMenu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (MainMenu);
  gtk_box_pack_start (GTK_BOX (vbox1), MainMenu, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label (_("File"));
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "file1", file1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (MainMenu), file1);

  file1_menu = gtk_menu_new ();
  gtk_widget_ref (file1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "file1_menu", file1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file1), file1_menu);
  file1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file1_menu));

  exit1 = gtk_menu_item_new_with_label (_("Exit"));
  gtk_widget_ref (exit1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "exit1", exit1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit1);
  gtk_container_add (GTK_CONTAINER (file1_menu), exit1);

  options1 = gtk_menu_item_new_with_label (_("Options"));
  gtk_widget_ref (options1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "options1", options1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options1);
  gtk_container_add (GTK_CONTAINER (MainMenu), options1);

  options1_menu = gtk_menu_new ();
  gtk_widget_ref (options1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "options1_menu", options1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (options1), options1_menu);
  options1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (options1_menu));

  preferences1 = gtk_menu_item_new_with_label (_("Preferences"));
  gtk_widget_ref (preferences1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "preferences1", preferences1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preferences1);
  gtk_container_add (GTK_CONTAINER (options1_menu), preferences1);

  help1 = gtk_menu_item_new_with_label (_("Help"));
  gtk_widget_ref (help1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "help1", help1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help1);
  gtk_container_add (GTK_CONTAINER (MainMenu), help1);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help1));

  help1_menu = gtk_menu_new ();
  gtk_widget_ref (help1_menu);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "help1_menu", help1_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help1), help1_menu);
  help1_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help1_menu));

  about1 = gtk_menu_item_new_with_label (_("About"));
  gtk_widget_ref (about1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "about1", about1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (help1_menu), about1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox1), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (viewport1), notebook1);
  gtk_container_set_border_width (GTK_CONTAINER (notebook1), 2);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebook1), FALSE);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox1);

  BatBar0 = gtk_progress_bar_new ();
  gtk_widget_ref (BatBar0);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "BatBar0", BatBar0,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (BatBar0);
  gtk_box_pack_start (GTK_BOX (hbox1), BatBar0, TRUE, FALSE, 0);
  gtk_progress_bar_set_orientation (GTK_PROGRESS_BAR (BatBar0), GTK_PROGRESS_BOTTOM_TO_TOP);
  gtk_progress_set_show_text (GTK_PROGRESS (BatBar0), TRUE);
  gtk_progress_set_format_string (GTK_PROGRESS (BatBar0), _("%P%%"));

  table1 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (hbox1), table1, TRUE, TRUE, 0);

  label1 = gtk_label_new (_("Chemistry:"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);

  Bat0Life = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat0Life);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat0Life", Bat0Life,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat0Life);
  gtk_table_attach (GTK_TABLE (table1), Bat0Life, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat0Life), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat0Life), 0, 0.5);

  Bat0Perc = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat0Perc);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat0Perc", Bat0Perc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat0Perc);
  gtk_table_attach (GTK_TABLE (table1), Bat0Perc, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat0Perc), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat0Perc), 0, 0.5);

  Bat0Volt = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat0Volt);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat0Volt", Bat0Volt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat0Volt);
  gtk_table_attach (GTK_TABLE (table1), Bat0Volt, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat0Volt), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat0Volt), 0, 0.5);

  Bat0Stat = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat0Stat);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat0Stat", Bat0Stat,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat0Stat);
  gtk_table_attach (GTK_TABLE (table1), Bat0Stat, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat0Stat), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat0Stat), 0, 0.5);

  Bat0Chem = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat0Chem);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat0Chem", Bat0Chem,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat0Chem);
  gtk_table_attach (GTK_TABLE (table1), Bat0Chem, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat0Chem), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat0Chem), 0, 0.5);

  label2 = gtk_label_new (_("Status:"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);

  label3 = gtk_label_new (_("Voltage:"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  label4 = gtk_label_new (_("Percentage:"));
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);

  label5 = gtk_label_new (_("Life (rem.):"));
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  tab1 = gtk_label_new (_("Battery #0"));
  gtk_widget_ref (tab1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "tab1", tab1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tab1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), tab1);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox2);

  BatBar1 = gtk_progress_bar_new ();
  gtk_widget_ref (BatBar1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "BatBar1", BatBar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (BatBar1);
  gtk_box_pack_start (GTK_BOX (hbox2), BatBar1, TRUE, FALSE, 0);
  gtk_progress_bar_set_orientation (GTK_PROGRESS_BAR (BatBar1), GTK_PROGRESS_BOTTOM_TO_TOP);
  gtk_progress_set_show_text (GTK_PROGRESS (BatBar1), TRUE);
  gtk_progress_set_format_string (GTK_PROGRESS (BatBar1), _("%P%%"));

  table2 = gtk_table_new (5, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (hbox2), table2, TRUE, TRUE, 0);

  label12 = gtk_label_new (_("Chemistry:"));
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label12), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  Bat1Life = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat1Life);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat1Life", Bat1Life,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat1Life);
  gtk_table_attach (GTK_TABLE (table2), Bat1Life, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat1Life), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat1Life), 0, 0.5);

  Bat1Perc = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat1Perc);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat1Perc", Bat1Perc,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat1Perc);
  gtk_table_attach (GTK_TABLE (table2), Bat1Perc, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat1Perc), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat1Perc), 0, 0.5);

  Bat1Volt = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat1Volt);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat1Volt", Bat1Volt,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat1Volt);
  gtk_table_attach (GTK_TABLE (table2), Bat1Volt, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat1Volt), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat1Volt), 0, 0.5);

  Bat1Stat = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat1Stat);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat1Stat", Bat1Stat,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat1Stat);
  gtk_table_attach (GTK_TABLE (table2), Bat1Stat, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat1Stat), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat1Stat), 0, 0.5);

  Bat1Chem = gtk_label_new (_("unkn."));
  gtk_widget_ref (Bat1Chem);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "Bat1Chem", Bat1Chem,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Bat1Chem);
  gtk_table_attach (GTK_TABLE (table2), Bat1Chem, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 5, 0);
  gtk_label_set_justify (GTK_LABEL (Bat1Chem), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (Bat1Chem), 0, 0.5);

  label18 = gtk_label_new (_("Status:"));
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Voltage:"));
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("Percentage:"));
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table2), label20, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("Life (rem.):"));
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  tab2 = gtk_label_new (_("Battery #1"));
  gtk_widget_ref (tab2);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMon), "tab2", tab2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), tab2);

  gtk_signal_connect (GTK_OBJECT (GPEBatMon), "delete_event",
                      GTK_SIGNAL_FUNC (on_GPEBatMon_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPEBatMon), "destroy_event",
                      GTK_SIGNAL_FUNC (on_GPEBatMon_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPEBatMon), "destroy",
                      GTK_SIGNAL_FUNC (on_GPEBatMon_de_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPEBatMon), "key_press_event",
                      GTK_SIGNAL_FUNC (on_GPEBatMon_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GPEBatMon), "button_press_event",
                      GTK_SIGNAL_FUNC (on_GPEBatMon_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (MainMenu), "deactivate",
                      GTK_SIGNAL_FUNC (on_MainMenu_deactivate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (exit1), "activate",
                      GTK_SIGNAL_FUNC (on_exit1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (preferences1), "activate",
                      GTK_SIGNAL_FUNC (on_preferences1_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about1), "activate",
                      GTK_SIGNAL_FUNC (on_about1_activate),
                      NULL);

  return GPEBatMon;
}

GtkWidget*
create_GPEBatMonAbout (void)
{
  GtkWidget *GPEBatMonAbout;
  GtkWidget *dialog_vbox1;
  GtkWidget *label22;
  GtkWidget *dialog_action_area1;
  GtkWidget *hbuttonbox1;
  GtkWidget *AboutOK;

  GPEBatMonAbout = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (GPEBatMonAbout), "GPEBatMonAbout", GPEBatMonAbout);
  gtk_window_set_title (GTK_WINDOW (GPEBatMonAbout), _("About"));
  GTK_WINDOW (GPEBatMonAbout)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (GPEBatMonAbout), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (GPEBatMonAbout), TRUE);
  gtk_window_set_default_size (GTK_WINDOW (GPEBatMonAbout), 160, 180);

  dialog_vbox1 = GTK_DIALOG (GPEBatMonAbout)->vbox;
  gtk_object_set_data (GTK_OBJECT (GPEBatMonAbout), "dialog_vbox1", dialog_vbox1);
  gtk_widget_show (dialog_vbox1);

  label22 = gtk_label_new (_("\nGPE-BatMon\n\nBattery monitor application\n(c) 2002 by Nils Faerber\n<nils@kernelconcepts.de>\n\nLicense: GPL\n"));
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonAbout), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), label22, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label22), 10, 0);

  dialog_action_area1 = GTK_DIALOG (GPEBatMonAbout)->action_area;
  gtk_object_set_data (GTK_OBJECT (GPEBatMonAbout), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area1), 10);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonAbout), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (dialog_action_area1), hbuttonbox1, TRUE, TRUE, 0);

  AboutOK = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (AboutOK);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonAbout), "AboutOK", AboutOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (AboutOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), AboutOK);
  GTK_WIDGET_SET_FLAGS (AboutOK, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (AboutOK), "clicked",
                      GTK_SIGNAL_FUNC (on_AboutOK_clicked),
                      NULL);

  return GPEBatMonAbout;
}

GtkWidget*
create_GPEBatMonPrefs (void)
{
  GtkWidget *GPEBatMonPrefs;
  GtkWidget *dialog_vbox2;
  GtkWidget *table3;
  GtkWidget *label23;
  GtkObject *UpdateInterval_adj;
  GtkWidget *UpdateInterval;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *checkbutton1;
  GtkWidget *dialog_action_area2;
  GtkWidget *hbuttonbox2;
  GtkWidget *PrefsCancel;
  GtkWidget *PrefsOK;

  GPEBatMonPrefs = gtk_dialog_new ();
  gtk_object_set_data (GTK_OBJECT (GPEBatMonPrefs), "GPEBatMonPrefs", GPEBatMonPrefs);
  gtk_window_set_title (GTK_WINDOW (GPEBatMonPrefs), _("Preferences"));
  GTK_WINDOW (GPEBatMonPrefs)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (GPEBatMonPrefs), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (GPEBatMonPrefs), TRUE);

  dialog_vbox2 = GTK_DIALOG (GPEBatMonPrefs)->vbox;
  gtk_object_set_data (GTK_OBJECT (GPEBatMonPrefs), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  table3 = gtk_table_new (2, 3, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), table3, TRUE, TRUE, 0);

  label23 = gtk_label_new (_("Update\ninterval"));
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table3), label23, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label23), 2, 2);

  UpdateInterval_adj = gtk_adjustment_new (5, 0.1, 1000, 0.1, 1, 10);
  UpdateInterval = gtk_spin_button_new (GTK_ADJUSTMENT (UpdateInterval_adj), 1, 1);
  gtk_widget_ref (UpdateInterval);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "UpdateInterval", UpdateInterval,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (UpdateInterval);
  gtk_table_attach (GTK_TABLE (table3), UpdateInterval, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label24 = gtk_label_new (_("Secs."));
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table3), label24, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new (_("Always\nshow\nmenubar"));
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table3), label25, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label25), 2, 2);

  checkbutton1 = gtk_check_button_new ();
  gtk_widget_ref (checkbutton1);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "checkbutton1", checkbutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton1);
  gtk_table_attach (GTK_TABLE (table3), checkbutton1, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  dialog_action_area2 = GTK_DIALOG (GPEBatMonPrefs)->action_area;
  gtk_object_set_data (GTK_OBJECT (GPEBatMonPrefs), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_action_area2), 10);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (dialog_action_area2), hbuttonbox2, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox2), 20);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox2), 70, 25);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox2), 5, -1);

  PrefsCancel = gtk_button_new_with_label (_("Cancel"));
  gtk_widget_ref (PrefsCancel);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "PrefsCancel", PrefsCancel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (PrefsCancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), PrefsCancel);
  GTK_WIDGET_SET_FLAGS (PrefsCancel, GTK_CAN_DEFAULT);

  PrefsOK = gtk_button_new_with_label (_("OK"));
  gtk_widget_ref (PrefsOK);
  gtk_object_set_data_full (GTK_OBJECT (GPEBatMonPrefs), "PrefsOK", PrefsOK,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (PrefsOK);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), PrefsOK);
  GTK_WIDGET_SET_FLAGS (PrefsOK, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (PrefsCancel), "clicked",
                      GTK_SIGNAL_FUNC (on_PrefsCancel_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (PrefsOK), "clicked",
                      GTK_SIGNAL_FUNC (on_PrefsOK_clicked),
                      NULL);

  return GPEBatMonPrefs;
}

