#!/bin/sh
#

XSERVER=Xipaq
if [ -f /usr/bin/Xfbdev ]; then
  XSERVER=Xfbdev
fi

. /etc/profile

module_id() {
    ## used to read from assets, but sometimes assets is corrupted
    # grep "Module ID" /proc/hal/assets | sed "s/.*://"
    ## used to read from /proc/hal/model, but that is removed in 2.6
    # echo ' iPAQ' `cat /proc/hal/model`
    awk 'BEGIN { FS=": " } /Hardware/ { print $2 } ' </proc/cpuinfo
}

export USER=root
export HOME=/root

ARGS="-dpi 100 -br"

# start off server in conventional location.
case `module_id` in
	"HP iPAQ 3100" | "HP iPAQ 3800")
		ARGS="$ARGS -screen 240x320@90 -rgba vrgb" ;;
	"HP iPAQ 3600" | "HP iPAQ 3700" | "HP iPAQ 3900")
		ARGS="$ARGS -screen 240x320@270 -rgba vbgr" ;;
	"HP iPAQ 5400")
		ARGS="$ARGS -rgba rgb" ;;
esac

exec $XSERVER $ARGS $*
