/* Generated by GOB (v2.0.2) on Fri Oct 25 15:37:36 2002
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 2

#define selfp (self->_priv)


#line 3 "gpeiconlist.gob"

/*
  gpeiconlist - an icon list widget
  Copyright (C) 2002  Robert Mibus <mibus@handhelds.org>

  This library is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2.1 of the License, or (at your option) any later version.

  This library is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

#include <stdlib.h>
#include <stdio.h>
#include <gtk/gtk.h>
#include "gpe-iconlist.h"

struct ILIcon
{
	char *title;
	char *icon;
	gpointer udata;
	GdkPixbuf *pb;
};


#line 49 "gpe-iconlist.c"
/* self casting macros */
#define SELF(x) GPE_ICONLIST(x)
#define SELF_CONST(x) GPE_ICONLIST_CONST(x)
#define IS_SELF(x) GPE_IS_ICONLIST(x)
#define TYPE_SELF GPE_TYPE_ICONLIST
#define SELF_CLASS(x) GPE_ICONLIST_CLASS(x)

#define SELF_GET_CLASS(x) GPE_ICONLIST_GET_CLASS(x)

/* self typedefs */
typedef GPEIconList Self;
typedef GPEIconListClass SelfClass;

struct _GPEIconListPrivate {
#line 39 "gpeiconlist.gob"
	GList * icons;
#line 40 "gpeiconlist.gob"
	GdkPixbuf * bgpixbuf;
#line 41 "gpeiconlist.gob"
	int rows;
#line 42 "gpeiconlist.gob"
	int cols;
#line 43 "gpeiconlist.gob"
	int mcol;
#line 44 "gpeiconlist.gob"
	int mrow;
#line 76 "gpe-iconlist.c"
};
/* here are local prototypes */
static void gpe_iconlist_class_init (GPEIconListClass * c) G_GNUC_UNUSED;
static void gpe_iconlist_init (GPEIconList * self) G_GNUC_UNUSED;
static gint gpe_iconlist__title_height (GtkWidget * widget) G_GNUC_UNUSED;
static gboolean gpe_iconlist__expose (GtkWidget * widget, GdkEventExpose * event, gpointer data) G_GNUC_UNUSED;
static struct ILIcon * gpe_iconlist_new_icon (char * title, char * icon, gpointer udata) G_GNUC_UNUSED;
static void ___9_gpe_iconlist_size_allocate (GtkWidget * self, GtkAllocation * allocation) G_GNUC_UNUSED;
static void gpe_iconlist__get_rowcol (GtkWidget * widget, int x, int y, int * col, int * row) G_GNUC_UNUSED;
static void gpe_iconlist__refresh_containing (GtkWidget * widget, int col, int row) G_GNUC_UNUSED;
static gint gpe_iconlist__button_release (GtkWidget * widget, GdkEventButton * event) G_GNUC_UNUSED;
static gint gpe_iconlist__button_press (GtkWidget * widget, GdkEventButton * event, gpointer user_data) G_GNUC_UNUSED;

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__clicked(object,func,data)	gpe_iconlist_connect__clicked((object),(func),(data))
#define self_connect_after__clicked(object,func,data)	gpe_iconlist_connect_after__clicked((object),(func),(data))
#define self_connect_data__clicked(object,func,data,destroy_data,flags)	gpe_iconlist_connect_data__clicked((object),(func),(data),(destroy_data),(flags))

typedef void  (*___Sig1) (GPEIconList *, gpointer , gpointer);

static void
___marshal_Sig1 (GClosure *closure,
	GValue *return_value,
	guint n_param_values,
	const GValue *param_values,
	gpointer invocation_hint,
	gpointer marshal_data)
{
	register ___Sig1 callback;
	register GCClosure *cc = (GCClosure*) closure;
	register gpointer data1, data2;

	g_return_if_fail (n_param_values == 2);

	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = g_value_peek_pointer (param_values + 0);
	} else {
		data1 = g_value_peek_pointer (param_values + 0);
		data2 = closure->data;
	}

	callback = (___Sig1) (marshal_data != NULL ? marshal_data : cc->callback);

	callback ((GPEIconList *)data1,
		(gpointer ) g_value_get_pointer (param_values + 1),
		data2);
}


enum {
	CLICKED_SIGNAL,
	LAST_SIGNAL
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GtkScrolledWindowClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_clicked(args...) gpe_iconlist_clicked(args)
#define self_new() gpe_iconlist_new()
#define self_set_bg(args...) gpe_iconlist_set_bg(args)
#define self__title_height(args...) gpe_iconlist__title_height(args)
#define self__expose(args...) gpe_iconlist__expose(args)
#define self_new_icon(args...) gpe_iconlist_new_icon(args)
#define self_add_item(args...) gpe_iconlist_add_item(args)
#define self__get_rowcol(args...) gpe_iconlist__get_rowcol(args)
#define self__refresh_containing(args...) gpe_iconlist__refresh_containing(args)
#define self__button_release(args...) gpe_iconlist__button_release(args)
#define self__button_press(args...) gpe_iconlist__button_press(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_clicked) (GPEIconList * self, gpointer udata) = gpe_iconlist_clicked;
static GtkWidget * (* const self_new) (void) = gpe_iconlist_new;
static void (* const self_set_bg) (GPEIconList * self, char * bg) = gpe_iconlist_set_bg;
static gint (* const self__title_height) (GtkWidget * widget) = gpe_iconlist__title_height;
static gboolean (* const self__expose) (GtkWidget * widget, GdkEventExpose * event, gpointer data) = gpe_iconlist__expose;
static struct ILIcon * (* const self_new_icon) (char * title, char * icon, gpointer udata) = gpe_iconlist_new_icon;
static void (* const self_add_item) (GPEIconList * self, char * title, char * icon, gpointer udata) = gpe_iconlist_add_item;
static void (* const self__get_rowcol) (GtkWidget * widget, int x, int y, int * col, int * row) = gpe_iconlist__get_rowcol;
static void (* const self__refresh_containing) (GtkWidget * widget, int col, int row) = gpe_iconlist__refresh_containing;
static gint (* const self__button_release) (GtkWidget * widget, GdkEventButton * event) = gpe_iconlist__button_release;
static gint (* const self__button_press) (GtkWidget * widget, GdkEventButton * event, gpointer user_data) = gpe_iconlist__button_press;

GType
gpe_iconlist_get_type (void)
{
	static GType type = 0;

	if (type == 0) {
		static const GTypeInfo info = {
			sizeof (GPEIconListClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) gpe_iconlist_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (GPEIconList),
			0 /* n_preallocs */,
			(GInstanceInitFunc) gpe_iconlist_init,
		};

		type = g_type_register_static (GTK_TYPE_SCROLLED_WINDOW, "GPEIconList", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((GPEIconList *)g_object_new(gpe_iconlist_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static GPEIconList * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static GPEIconList *
GET_NEW_VARG (const char *first, ...)
{
	GPEIconList *ret;
	va_list ap;
	va_start (ap, first);
	ret = (GPEIconList *)g_object_new_valist (gpe_iconlist_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "GPE:IconList::finalize"
	GPEIconList *self = GPE_ICONLIST (obj_self);
	gpointer priv = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
	g_free (priv);
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
gpe_iconlist_class_init (GPEIconListClass * c)
{
#define __GOB_FUNCTION__ "GPE:IconList::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;
	GtkWidgetClass *gtk_widget_class = (GtkWidgetClass *)c;

	parent_class = g_type_class_ref (GTK_TYPE_SCROLLED_WINDOW);

	object_signals[CLICKED_SIGNAL] =
		g_signal_new ("clicked",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_LAST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (GPEIconListClass, clicked),
			NULL, NULL,
			___marshal_Sig1,
			G_TYPE_NONE, 1,
			G_TYPE_POINTER);
	if(sizeof(gpointer ) != sizeof(gpointer )) {
		g_error("gpeiconlist.gob line 47: Type mismatch of \"clicked\" signal signature");
	}

	c->clicked = NULL;
#line 344 "gpeiconlist.gob"
	gtk_widget_class->size_allocate = ___9_gpe_iconlist_size_allocate;
#line 248 "gpe-iconlist.c"
	g_object_class->finalize = ___finalize;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 51 "gpeiconlist.gob"
static void 
gpe_iconlist_init (GPEIconList * self)
#line 258 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::init"
	self->_priv = g_new0 (GPEIconListPrivate, 1);
#line 3 "gpeiconlist.gob"
	self->_priv->icons = NULL;
#line 264 "gpe-iconlist.c"
#line 3 "gpeiconlist.gob"
	self->_priv->bgpixbuf = NULL;
#line 267 "gpe-iconlist.c"
#line 3 "gpeiconlist.gob"
	self->_priv->rows = 1;
#line 270 "gpe-iconlist.c"
#line 3 "gpeiconlist.gob"
	self->_priv->cols = 1;
#line 273 "gpe-iconlist.c"
#line 3 "gpeiconlist.gob"
	self->_priv->mcol = -1;
#line 276 "gpe-iconlist.c"
#line 3 "gpeiconlist.gob"
	self->_priv->mrow = -1;
#line 279 "gpe-iconlist.c"
 {
#line 52 "gpeiconlist.gob"

		GtkWidget *vp, *da;

		gtk_scrolled_window_set_hadjustment (GTK_SCROLLED_WINDOW(self), NULL);
		gtk_scrolled_window_set_vadjustment (GTK_SCROLLED_WINDOW(self), NULL);

		gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW(GTK_SCROLLED_WINDOW(self)),
						GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);

		vp = gtk_viewport_new (NULL, NULL);
		gtk_container_add (GTK_CONTAINER(self), vp);

		da = gtk_drawing_area_new ();
		gtk_widget_add_events (GTK_WIDGET (da), GDK_BUTTON_PRESS_MASK |
				       GDK_BUTTON_RELEASE_MASK);
		gtk_signal_connect (GTK_OBJECT(da), "expose_event",
				    (GtkSignalFunc)gpe_iconlist__expose, NULL);
		gtk_signal_connect (GTK_OBJECT(da), "button_release_event",
				    GTK_SIGNAL_FUNC(gpe_iconlist__button_release), NULL);
		gtk_signal_connect (GTK_OBJECT(da), "button_press_event",
				    GTK_SIGNAL_FUNC(gpe_iconlist__button_press), NULL);
		gtk_container_add (GTK_CONTAINER(vp), da);

		gtk_object_set_data (GTK_OBJECT (self), "da", da);
		gtk_object_set_data (GTK_OBJECT (da), "il", self);
		gtk_object_set_data (GTK_OBJECT (da), "va", gtk_viewport_get_vadjustment(GTK_VIEWPORT(vp)));

		gtk_widget_show_all (vp);
	
#line 311 "gpe-iconlist.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


#line 47 "gpeiconlist.gob"
void 
gpe_iconlist_clicked (GPEIconList * self, gpointer udata)
#line 322 "gpe-iconlist.c"
{
	GValue ___param_values[2];
	GValue ___return_val = {0};

#line 47 "gpeiconlist.gob"
	g_return_if_fail (self != NULL);
#line 47 "gpeiconlist.gob"
	g_return_if_fail (GPE_IS_ICONLIST (self));
#line 331 "gpe-iconlist.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	___param_values[1].g_type = 0;
	g_value_init (&___param_values[1], G_TYPE_POINTER);
	g_value_set_pointer (&___param_values[1], (gpointer ) udata);

	g_signal_emitv (___param_values,
		object_signals[CLICKED_SIGNAL],
		0 /* detail */,
		&___return_val);
}


#line 82 "gpeiconlist.gob"
GtkWidget * 
gpe_iconlist_new (void)
#line 351 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::new"
{
#line 84 "gpeiconlist.gob"
	
		return GTK_WIDGET(GET_NEW);
	}}
#line 359 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 89 "gpeiconlist.gob"
void 
gpe_iconlist_set_bg (GPEIconList * self, char * bg)
#line 365 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::set_bg"
{
#line 90 "gpeiconlist.gob"
	
		if (self->_priv->bgpixbuf)
			gdk_pixbuf_unref (self->_priv->bgpixbuf);
		if (bg)
			self->_priv->bgpixbuf = gdk_pixbuf_new_from_file (bg, NULL);
		else
			self->_priv->bgpixbuf = NULL;
	}}
#line 378 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 100 "gpeiconlist.gob"
static gint 
gpe_iconlist__title_height (GtkWidget * widget)
#line 384 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::_title_height"
{
#line 100 "gpeiconlist.gob"
	
		PangoContext *pc;
		PangoLayout *pl;
		PangoRectangle pr;
		int label_height;

		printf ("_title_height\n");
		/* Pango font rendering setup */
		if ((pc = gtk_widget_get_pango_context (GTK_WIDGET(widget))) == NULL)
			pc = gtk_widget_create_pango_context (GTK_WIDGET(widget));
		pl = pango_layout_new (pc);
		
		/* Find out how tall icon labels will be */
		pango_layout_set_text (pl, "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm\nQWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm", -1);
		pango_layout_get_pixel_extents  (pl, NULL, &pr);
		label_height = pr.height;

		return label_height;
	}}
#line 408 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 121 "gpeiconlist.gob"
static gboolean 
gpe_iconlist__expose (GtkWidget * widget, GdkEventExpose * event, gpointer data)
#line 414 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::_expose"
{
#line 122 "gpeiconlist.gob"
	
		GPEIconList *il;
		GList *icons;
		GdkPixbuf *dest;
		int row=0, col=0;
		GtkAdjustment *va;
		PangoContext *pc;
		PangoLayout *pl;
		int label_height;
		int i;

		printf ("iconlist_expose\n");
		il = GPE_ICONLIST(gtk_object_get_data (GTK_OBJECT(widget), "il"));

		/* Pango font rendering setup */
		if ((pc = gtk_widget_get_pango_context (widget)) == NULL)
			pc = gtk_widget_create_pango_context (widget);
		pl = pango_layout_new (pc);
		pango_layout_set_width (pl, 70 * PANGO_SCALE);
		pango_layout_set_alignment (pl, PANGO_ALIGN_CENTER);
		//pango_layout_set_wrap (pl, PANGO_WRAP_CHAR);

		label_height = gpe_iconlist__title_height (widget);

		/* Get the GtkAdjustment used for the vertical scrollbar
		   va->value is the current displacement of the view as compared to the widget */
		va = gtk_object_get_data (GTK_OBJECT (widget), "va");

		/* No idea ;-) */
		gdk_window_set_back_pixmap (widget->window, NULL, FALSE);

		/* Make a new pixbuf for rendering icons to */
		dest = gdk_pixbuf_new (GDK_COLORSPACE_RGB, FALSE, 8,
				       event->area.width, event->area.height);

		/* Whiten the background
		   -> for use with a transparent bg? cool... */
		gdk_pixbuf_fill (dest, 0xffffffff);

		/* Paint the background image, scaled */
/*
			gdk_pixbuf_composite (il->_priv->bgpixbuf, dest,
					      0, i, event->area.width, event->area.height,
					      -event->area.x, -event->area.y + i,
					      1,//(double) widget->allocation.width / gdk_pixbuf_get_width (il->_priv->bgpixbuf),
					      1,//(double) widget->allocation.height / gdk_pixbuf_get_height (il->_priv->bgpixbuf),
					      GDK_INTERP_BILINEAR, 255);
*/

		if (il->_priv->bgpixbuf)
			for (i=0; i < il->_priv->rows * (60 + label_height); i += gdk_pixbuf_get_height(il->_priv->bgpixbuf)) {
				GdkRectangle r1, dst;
				r1.x = 0; r1.y = i;
				r1.width = gdk_pixbuf_get_width (il->_priv->bgpixbuf);
				r1.height = gdk_pixbuf_get_height (il->_priv->bgpixbuf);

				printf ("placing bg image at (0,%d)\n", i);
				printf ("of maximum height %d\n", il->_priv->rows * (60 + label_height));
				printf ("image height = %d\n", gdk_pixbuf_get_height (il->_priv->bgpixbuf));
				if (gdk_rectangle_intersect (&r1, &(event->area), &dst)) {
					gdk_pixbuf_composite (il->_priv->bgpixbuf, dest,
							      dst.x-event->area.x,
							      dst.y-event->area.y,
							      dst.width, dst.height,
							      r1.x-event->area.x, r1.y-event->area.y,
							      1,
							      1,
							      GDK_INTERP_BILINEAR, 255);
				}
			}


		icons = il->_priv->icons;
		while (icons) {
			GdkRectangle r1, r2, dst;
			struct ILIcon *icon;
			icon = icons->data;
			
			/* Compute & render the icon */
			r1.x=col * 70 + 11;
			r1.y=row * (60 + label_height) + 5;
			r1.width = 48; // gdk_pixbuf_get_width(pixbuf);
			r1.height = 48; // gdk_pixbuf_get_height(pixbuf);

			r2.x = event->area.x;
			r2.y = event->area.y;
			r2.width = event->area.width;
			r2.height = event->area.height;
	  
			if (gdk_rectangle_intersect (&r1, &r2, &dst)) {
				GdkPixbuf *pixbuf=NULL;

				/* Get the icon from the cache if its there, if not put it there :) */
				if (icon->pb)
					pixbuf = icon->pb;
				else
					icon->pb = pixbuf = gdk_pixbuf_new_from_file (icon->icon, NULL);

				if (pixbuf) {
					gdk_pixbuf_composite (pixbuf, dest, // from, to
							      dst.x - event->area.x, //dest_x
							      dst.y - event->area.y,// + va->value, // dest_y
							      dst.width, dst.height, // dest_width, dest_height
							      r1.x-event->area.x, // offset_x
							      r1.y-event->area.y,// + va->value, // offset_y
							      (double)48/gdk_pixbuf_get_width (pixbuf), // scale_x
							      (double)48/gdk_pixbuf_get_width (pixbuf), // scale y
							      GDK_INTERP_BILINEAR, // filtering
							      //(gpe_iconlist__contains (r1, il->_priv->mx, il->_priv->my)) ? 128 : 255); // forced whole-alpha
							      col == il->_priv->mcol && row == il->_priv->mrow ? 128 : 255);
				//gdk_pixbuf_unref (pixbuf);
				}
			}

			if (++col == il->_priv->cols) {
				col = 0; row++;
			}

			icons = icons->next;
		}

		/* Dump to drawingarea */
		gdk_pixbuf_render_to_drawable (dest, widget->window, widget->style->fg_gc[GTK_STATE_NORMAL],
					       0, 0, event->area.x, event->area.y,
					       event->area.width, event->area.height,
					       GDK_RGB_DITHER_NORMAL, event->area.x, event->area.y);

		gdk_pixbuf_unref (dest);

		col = row = 0;

		icons = il->_priv->icons;
		while (icons) {
			GdkRectangle r1, r2, dst;
			struct ILIcon *icon;
			icon = icons->data;

			/* Compute & render the title */
			r1.x=col * 70;
			r1.y=row * (60 + label_height) + 55;
			r1.width = 70;
			r1.height = label_height;

			r2.x = event->area.x;
			r2.y = event->area.y;
			r2.width = event->area.width;
			r2.height = event->area.height;
	  
			if (gdk_rectangle_intersect (&r1, &r2, &dst)) {
				char *stxt; int slen;
				int selected=0;
				PangoRectangle pr;

				stxt=icon->title;
				slen = strlen (stxt);

				selected = (il->_priv->mrow == row && il->_priv->mcol == col);
				if (selected) {
					char *newtxt;
					newtxt = g_strdup_printf ("<b>%s</b>", stxt);
					pango_layout_set_markup (pl, newtxt, -1);
					g_free (newtxt);
				} else
					pango_layout_set_text (pl, stxt, -1);

				pango_layout_get_pixel_extents  (pl, NULL, &pr);

				while ((pango_layout_get_line_count (pl) > 2 ||
					pr.width > 70) && slen>0) {
					char *newtxt;
					char *fmt;
					if (stxt[slen-2] == ' ')
						slen--;

					if (selected)
						fmt = g_strdup_printf ("<b>%%.%ds...</b>", --slen);
					else
						fmt = g_strdup_printf ("%%.%ds...", --slen);

					newtxt = g_strdup_printf (fmt, stxt);
					g_free (fmt);

					if (selected)
						pango_layout_set_markup (pl, newtxt, -1);
					else
						pango_layout_set_text (pl, newtxt, -1);
					g_free (newtxt);

					pango_layout_get_pixel_extents  (pl, NULL, &pr);
				}

				gtk_paint_layout (widget->style, widget->window, GTK_WIDGET_STATE (widget),
						  FALSE, &dst,
						  widget, "detail?wtf?", r1.x, r1.y, pl);
			}

			if (++col == il->_priv->cols) {
				col = 0; row++;
			}
			icons = icons->next;
		}

		printf ("done expose\n");
		return TRUE;
	}}
#line 624 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 328 "gpeiconlist.gob"
static struct ILIcon * 
gpe_iconlist_new_icon (char * title, char * icon, gpointer udata)
#line 630 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::new_icon"
{
#line 329 "gpeiconlist.gob"
	
		struct ILIcon *ret;
		ret = (struct ILIcon *) malloc (sizeof (struct ILIcon));
		ret->title = title;
		ret->icon = icon;
		ret->udata = udata;
		ret->pb = NULL;
		return ret;
	}}
#line 644 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 339 "gpeiconlist.gob"
void 
gpe_iconlist_add_item (GPEIconList * self, char * title, char * icon, gpointer udata)
#line 650 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::add_item"
#line 339 "gpeiconlist.gob"
	g_return_if_fail (self != NULL);
#line 339 "gpeiconlist.gob"
	g_return_if_fail (GPE_IS_ICONLIST (self));
#line 657 "gpe-iconlist.c"
{
#line 340 "gpeiconlist.gob"
	
		self->_priv->icons = g_list_append (self->_priv->icons, gpe_iconlist_new_icon (title, icon, udata));
	}}
#line 663 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 344 "gpeiconlist.gob"
static void 
___9_gpe_iconlist_size_allocate (GtkWidget * self, GtkAllocation * allocation)
#line 669 "gpe-iconlist.c"
#define PARENT_HANDLER(___self,___allocation) \
	{ if(GTK_WIDGET_CLASS(parent_class)->size_allocate) \
		(* GTK_WIDGET_CLASS(parent_class)->size_allocate)(___self,___allocation); }
{
#define __GOB_FUNCTION__ "GPE:IconList::size_allocate"
{
#line 347 "gpeiconlist.gob"
	
		int count=0;
		int label_height;
		GPEIconList *il;
		il = GPE_ICONLIST(self);

		printf ("iconlist: size_allocate\n");

		if ((int)gtk_object_get_data (GTK_OBJECT(il), "size_x") == allocation->width &&
		    (int)gtk_object_get_data (GTK_OBJECT(il), "size_y") == allocation->height)
			return;

		printf ("new size: %dx%d\n", allocation->width, allocation->height);

		gtk_object_set_data (GTK_OBJECT(il), "size_x", (gpointer)allocation->width);
		gtk_object_set_data (GTK_OBJECT(il), "size_y", (gpointer)allocation->height);
		
		if (allocation->width - 15 > 70) 
			il->_priv->cols = (allocation->width - 15) / 70;
		else
			il->_priv->cols = 1;
		
		count = g_list_length (il->_priv->icons);
		
		il->_priv->rows = ((count+il->_priv->cols-1)/il->_priv->cols);
		
		label_height = gpe_iconlist__title_height (GTK_WIDGET(il));
		
		gtk_drawing_area_size (
			GTK_DRAWING_AREA(gtk_object_get_data (GTK_OBJECT(il), "da")),
			allocation->width, il->_priv->rows * (60 + label_height) + 5);
		
		PARENT_HANDLER (self, allocation);
	}}
#line 711 "gpe-iconlist.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 382 "gpeiconlist.gob"
static void 
gpe_iconlist__get_rowcol (GtkWidget * widget, int x, int y, int * col, int * row)
#line 718 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::_get_rowcol"
{
#line 382 "gpeiconlist.gob"
	
		int label_height;

		label_height = gpe_iconlist__title_height (GTK_WIDGET(widget));

		*col = (double)x / (double)70;
		*row = (double)y / (double)(60 + label_height);
	}}
#line 731 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 391 "gpeiconlist.gob"
static void 
gpe_iconlist__refresh_containing (GtkWidget * widget, int col, int row)
#line 737 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::_refresh_containing"
{
#line 391 "gpeiconlist.gob"
	
		int x, y;
		int label_height;

		label_height = gpe_iconlist__title_height (GTK_WIDGET(widget));

		x=col * 70;
		y=row * (60 + label_height);

		gtk_widget_queue_draw_area (widget, x, y, 70, 60 + label_height + 5);
	}}
#line 753 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 403 "gpeiconlist.gob"
static gint 
gpe_iconlist__button_release (GtkWidget * widget, GdkEventButton * event)
#line 759 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::_button_release"
{
#line 403 "gpeiconlist.gob"
	
		GPEIconList *il;
		int col, row;
		il = GPE_ICONLIST(gtk_object_get_data (GTK_OBJECT(widget), "il"));

		gpe_iconlist__refresh_containing (GTK_WIDGET(widget), il->_priv->mcol, il->_priv->mrow);

		gpe_iconlist__get_rowcol (widget, event->x, event->y, &(col), &(row));
		if (col == il->_priv->mcol && row == il->_priv->mrow) {
			int i;
			GList *icons;

			icons = il->_priv->icons;
			for (i=0;i<il->_priv->mrow*il->_priv->cols+il->_priv->mcol;i++)
				icons = icons->next;

			gpe_iconlist_clicked (il, ((struct ILIcon *)icons->data)->udata);
		}

		il->_priv->mcol = il->_priv->mrow = -1;

		return TRUE;
	}}
#line 787 "gpe-iconlist.c"
#undef __GOB_FUNCTION__

#line 427 "gpeiconlist.gob"
static gint 
gpe_iconlist__button_press (GtkWidget * widget, GdkEventButton * event, gpointer user_data)
#line 793 "gpe-iconlist.c"
{
#define __GOB_FUNCTION__ "GPE:IconList::_button_press"
{
#line 427 "gpeiconlist.gob"
	
		GPEIconList *il;

		il = GPE_ICONLIST(gtk_object_get_data (GTK_OBJECT(widget), "il"));

//		printf ("btn_press\n");
//		printf ("(%f,%f) btn %d\n", event->x, event->y, event->button);

		//il->_priv->mx = event->x;
		//il->_priv->my = event->y;

		gpe_iconlist__get_rowcol (widget, event->x, event->y, &(il->_priv->mcol), &(il->_priv->mrow));
		gpe_iconlist__refresh_containing (widget, il->_priv->mcol, il->_priv->mrow);

		return TRUE;
	}}
#line 814 "gpe-iconlist.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___gpe_iconlist_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_clicked)();
	((void (*)(void))self_new)();
	((void (*)(void))self_set_bg)();
	((void (*)(void))self__title_height)();
	((void (*)(void))self__expose)();
	((void (*)(void))self_new_icon)();
	((void (*)(void))self_add_item)();
	((void (*)(void))self__get_rowcol)();
	((void (*)(void))self__refresh_containing)();
	((void (*)(void))self__button_release)();
	((void (*)(void))self__button_press)();
	___gpe_iconlist_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

