<?php
$addtitle="Projects";
$pagename="projects";
$author="Nils Faerber";
$authoremail="nils@handhelds.org";

include ("../includes/head.php");
?>

<h2>Base software/libraries</h2>
<ul> 
<LI> <A HREF="http://www.gtk.org">GTK+ widget toolkit</A> (not maintained by the GPE project)
<LI> <A HREF="libgpewidget.shtml">libgpewidget</A>
<LI> <A HREF="GPE-usqld.shtml">uSQLd Database Engine</A> (based on <a href="http://www.hwaci.com/sw/sqlite/">SQLite</a>)
</UL>

<h2>Applications</h2>
 	<UL>
	<LI> <A HREF="GPE-address.shtml">Address book</A>
	<LI> <A HREF="GPE-alarms.shtml">Alarm clock</A> (not yet started)
	<LI> <A HREF="GPE-appmgr.shtml">Application Manager</A>
	<LI> <A HREF="GPE-calendar.shtml">Calendar</A>
	<LI> <A HREF="GPE-today.shtml">Daily summary</A>
	<LI> <A HREF="GPE-games.shtml">Games</A>
	<LI> <A HREF="GPE-mail.shtml">Mail client</A>
	<LI> <A HREF="GPE-media.shtml">Media player</A>
	<LI> <A HREF="GPE-notebook.shtml">Notebook</A>
	<LI> <A HREF="GPE-time-tracker.shtml">Time tracker</A>
	<LI> <A HREF="GPE-todo.shtml">Todo list</A>
	<LI> <A HREF="GPE-soundbite.shtml">Voice memo recorder</A>
	<LI> ... and for sure many more to come
</UL>

<h2>Utilities</h2>
<UL>
	<LI> <A HREF="bluez-pin.shtml">Bluetooth PIN
		    manager</A>
	<LI> <A HREF="GPE-what.shtml">Modal help system</A>
	<LI> <A HREF="GPE-login.shtml">Multi-user login</A>
	<LI> <A HREF="GPE-setup.shtml">System setup</A>
</UL>


<p>
See the Wiki page <A href="http://www.handhelds.org/z/wiki/CurrentThingsToDo">CurrentThingsToDo</A> for a list of things that particularly need attention.
</p>

<?php include ("../includes/foot.php"); ?>
