<?php
$addtitle="Projects";
$pagename="projects";
$author="Nils Faerber";
$authoremail="nils@handhelds.org";

include ("../includes/head.php");
?>

<h2>Base software/libraries</h2>
<ul> 
<LI> <A HREF="http://www.gtk.org">GTK+ widget toolkit</A> (not maintained by the GPE project)
<LI> <A HREF="http://www.sqlite.org">SQLite database engine</A> (not maintained by the GPE project)
<LI> <A HREF="libgpewidget.shtml">libgpewidget</A>
<!--<LI> <A HREF="libgpevtype.shtml">libgpevtype</A>
<LI> <A HREF="libgpepimc.shtml">libgpepimc</A>
-->
</UL>

<h2>Applications</h2>
 	<UL>
	<LI> <A HREF="GPE-address.shtml">Contacts Manager</A>
	<LI> <A HREF="GPE-alarms.shtml">Alarm clock</A>
	<LI> <A HREF="GPE-appmgr.shtml">Application Manager</A> (outdated)
	<LI> <A HREF="GPE-calendar.shtml">Calendar</A>
	<LI> <A HREF="GPE-today.shtml">Daily summary</A>
	<LI> <A HREF="GPE-games.shtml">Games</A>
	<LI> <A HREF="GPE-mail.shtml">Mail client</A> (deprecated)
	<LI> <A HREF="GPE-media.shtml">NMF Media player</A>
	<LI> <A HREF="GPE-notebook.shtml">Sketchbook</A>
	<LI> <A HREF="GPE-time-tracker.shtml">Time Tracker</A>
	<LI> <A HREF="GPE-todo.shtml">Todo List</A>
	<LI> <A HREF="GPE-soundbite.shtml">Voice Memo Recorder</A>
	<LI> ... and for sure many more to come
</UL>

<h2>Utilities</h2>
<UL>
	<LI> <A HREF="bluez-pin.shtml">Bluetooth PIN manager</A>
	<LI> <A HREF="GPE-what.shtml">Modal Help System</A>
	<LI> <A HREF="GPE-login.shtml">Multi-user Login</A>
	<LI> <A HREF="GPE-setup.shtml">Configuration Tools</A>
</UL>


<p>
See the Wiki page <A href="http://handhelds.org/moin/moin.cgi/GpeThingsTodo">GpeThingsToDo</A> for a list of things that particularly need attention.
</p>

<?php include ("../includes/foot.php"); ?>
