#! /bin/sh

if test -x /usr/bin/update-menus; then
    update-menus;
fi

if test -d /etc/X11/Xsession-gpe.d/; then 
    ln -fs /etc/X11/Xsession.d/99gpe-calendar /etc/X11/Xsession-gpe.d/99gpe-calendar
fi

# return success
exit 0;
