#! /bin/sh

# remove dangling symlink:
if [ -L /etc/gpe/gpe-login-bg.png ]; then
   rm -f /etc/gpe/gpe-login-bg.png
fi
## *don't* remove /etc/gpe/gpe-login-bg.dontshow so that the user
## has it for the next time

# always return true:
return 0
